package net.mcreator.xillysorespawn.entity.renderer;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.mcreator.xillysorespawn.entity.DragonEntity;

@OnlyIn(Dist.CLIENT)
public class DragonRenderer {
    private static final String TEXTURE = "xillys_orespawn:textures/entities/dragon.png";
    private static final String WHITE_TEXTURE = "xillys_orespawn:textures/entities/whitedragon.png";
    public static class ModelRegisterHandler {
        @SubscribeEvent @OnlyIn(Dist.CLIENT)
        public void registerModels(ModelRegistryEvent event) {
            RenderingRegistry.registerEntityRenderingHandler(DragonEntity.entity, manager ->
                new MobRenderer(manager, new ModelDragon(1.0F), 0.5F) {
                    @Override public ResourceLocation getEntityTexture(Entity entity) {
                        return new ResourceLocation(((DragonEntity.CustomEntity) entity).getDragonType() == 0
                            ? TEXTURE : WHITE_TEXTURE);
                    }
                });
        }
    }

public static class ModelDragon extends EntityModel<Entity> {
    // Exact legacy render order recovered from bytecode; do not add a second addChild rig.
    private Entity frameEntity;
    private float frameSwing, frameAmount, frameAge, frameYaw, framePitch;
    @Override public void setRotationAngles(Entity entity, float swing, float amount, float age, float yaw, float pitch) {
        frameEntity=entity; frameSwing=swing; frameAmount=amount; frameAge=age; frameYaw=yaw; framePitch=pitch;
    }

    private float wingspeed = 1.0f;
    private final ModelRenderer horn1;
    private final ModelRenderer horn2;
    private final ModelRenderer tail6;
    private final ModelRenderer wing15;
    private final ModelRenderer spike1;
    private final ModelRenderer spike2;
    private final ModelRenderer spike3;
    private final ModelRenderer spike4;
    private final ModelRenderer wing14;
    private final ModelRenderer spike5;
    private final ModelRenderer spike6;
    private final ModelRenderer spike7;
    private final ModelRenderer spike8;
    private final ModelRenderer spike9;
    private final ModelRenderer spike10;
    private final ModelRenderer head;
    private final ModelRenderer body;
    private final ModelRenderer leg1;
    private final ModelRenderer leg2;
    private final ModelRenderer leg3;
    private final ModelRenderer leg4;
    private final ModelRenderer body2;
    private final ModelRenderer neck1;
    private final ModelRenderer body3;
    private final ModelRenderer neck2;
    private final ModelRenderer neck3;
    private final ModelRenderer leg5;
    private final ModelRenderer leg6;
    private final ModelRenderer leg7;
    private final ModelRenderer leg9;
    private final ModelRenderer foot1;
    private final ModelRenderer foot2;
    private final ModelRenderer leg10;
    private final ModelRenderer leg11;
    private final ModelRenderer foot3;
    private final ModelRenderer foot4;
    private final ModelRenderer tail1;
    private final ModelRenderer tail2;
    private final ModelRenderer tail3;
    private final ModelRenderer mouth1;
    private final ModelRenderer mouth2;
    private final ModelRenderer tail5;
    private final ModelRenderer wing1;
    private final ModelRenderer wing2;
    private final ModelRenderer wing3;
    private final ModelRenderer wing4;
    private final ModelRenderer wing5;
    private final ModelRenderer wing6;
    private final ModelRenderer wing7;
    private final ModelRenderer wing8;
    private final ModelRenderer wing9;
    private final ModelRenderer wing10;
    private final ModelRenderer wing11;
    private final ModelRenderer wing12;
    private final ModelRenderer tail4;

    public ModelDragon(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.horn1 = new ModelRenderer(this, 0, 39);
        this.horn1.addBox(2.0f, -4.0f, 1.0f, 2, 2, 6);
        this.horn1.setRotationPoint(0.0f, 6.0f, -23.0f);
        this.horn1.mirror = true;
        this.setRotation(this.horn1, 0.4089647f, 0.2602503f, 0.0f);
        this.horn2 = new ModelRenderer(this, 0, 39);
        this.horn2.addBox(-4.0f, -4.0f, 1.0f, 2, 2, 6);
        this.horn2.setRotationPoint(0.0f, 6.0f, -23.0f);
        this.horn2.mirror = true;
        this.setRotation(this.horn2, 0.4089647f, -0.2602503f, 0.0f);
        this.tail6 = new ModelRenderer(this, 0, 49);
        this.tail6.addBox(-1.0f, 0.0f, -2.0f, 2, 6, 4);
        this.tail6.setRotationPoint(0.0f, 7.0f, 43.0f);
        this.tail6.mirror = true;
        this.setRotation(this.tail6, 1.570796f, 0.0f, 0.0f);
        this.wing15 = new ModelRenderer(this, 0, 62);
        this.wing15.addBox(1.0f, -1.0f, 1.0f, 12, 1, 8);
        this.wing15.setRotationPoint(4.0f, 3.0f, -5.0f);
        this.wing15.mirror = true;
        this.setRotation(this.wing15, -0.0743572f, -0.4089594f, 0.0f);
        this.spike1 = new ModelRenderer(this, 0, 73);
        this.spike1.addBox(-1.0f, -3.0f, -5.0f, 2, 2, 4);
        this.spike1.setRotationPoint(0.0f, 6.0f, -17.0f);
        this.spike1.mirror = true;
        this.setRotation(this.spike1, 0.0f, 0.0f, 0.0f);
        this.spike2 = new ModelRenderer(this, 0, 73);
        this.spike2.addBox(-1.0f, -3.0f, -5.0f, 2, 2, 4);
        this.spike2.setRotationPoint(0.0f, 6.0f, -11.0f);
        this.spike2.mirror = true;
        this.setRotation(this.spike2, 0.0f, 0.0f, 0.0f);
        this.spike3 = new ModelRenderer(this, 0, 73);
        this.spike3.addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4);
        this.spike3.setRotationPoint(0.0f, 7.0f, 25.0f);
        this.spike3.mirror = true;
        this.setRotation(this.spike3, 0.0f, 0.0f, 0.0f);
        this.spike4 = new ModelRenderer(this, 0, 73);
        this.spike4.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4);
        this.spike4.setRotationPoint(0.0f, 3.0f, -7.0f);
        this.spike4.mirror = true;
        this.setRotation(this.spike4, 0.0f, 0.0f, 0.0f);
        this.wing14 = new ModelRenderer(this, 0, 62);
        this.wing14.addBox(-13.0f, -1.0f, 0.0f, 12, 1, 8);
        this.wing14.setRotationPoint(-4.0f, 3.0f, -5.0f);
        this.wing14.mirror = true;
        this.setRotation(this.wing14, -0.0698132f, 0.4089656f, 0.0f);
        this.spike5 = new ModelRenderer(this, 0, 73);
        this.spike5.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4);
        this.spike5.setRotationPoint(0.0f, 3.0f, -1.0f);
        this.spike5.mirror = true;
        this.setRotation(this.spike5, 0.0f, 0.0f, 0.0f);
        this.spike6 = new ModelRenderer(this, 0, 73);
        this.spike6.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 4);
        this.spike6.setRotationPoint(0.0f, 3.0f, 5.0f);
        this.spike6.mirror = true;
        this.setRotation(this.spike6, 0.0f, 0.0f, 0.0f);
        this.spike7 = new ModelRenderer(this, 0, 73);
        this.spike7.addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4);
        this.spike7.setRotationPoint(0.0f, 7.0f, 13.0f);
        this.spike7.mirror = true;
        this.setRotation(this.spike7, 0.0f, 0.0f, 0.0f);
        this.spike8 = new ModelRenderer(this, 0, 73);
        this.spike8.addBox(-1.0f, -2.0f, 1.0f, 2, 2, 4);
        this.spike8.setRotationPoint(0.0f, 5.0f, 19.0f);
        this.spike8.mirror = true;
        this.setRotation(this.spike8, 0.0f, 0.0f, 0.0f);
        this.spike9 = new ModelRenderer(this, 0, 73);
        this.spike9.addBox(-1.0f, -4.0f, 1.0f, 2, 2, 4);
        this.spike9.setRotationPoint(0.0f, 7.0f, 31.0f);
        this.spike9.mirror = true;
        this.setRotation(this.spike9, 0.0f, 0.0f, 0.0f);
        this.spike10 = new ModelRenderer(this, 0, 73);
        this.spike10.addBox(-1.0f, -4.0f, 2.0f, 2, 2, 4);
        this.spike10.setRotationPoint(0.0f, 7.0f, 36.0f);
        this.spike10.mirror = true;
        this.setRotation(this.spike10, 0.0f, 0.0f, 0.0f);
        this.head = new ModelRenderer(this, 0, 81);
        this.head.addBox(-4.0f, -4.0f, -8.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, 6.0f, -23.0f);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        this.body = new ModelRenderer(this, 1, 99);
        this.body.addBox(-6.0f, -10.0f, -7.0f, 12, 18, 10);
        this.body.setRotationPoint(0.0f, 5.0f, 2.0f);
        this.body.mirror = true;
        this.setRotation(this.body, 1.570796f, 0.0f, 0.0f);
        this.leg1 = new ModelRenderer(this, 47, 112);
        this.leg1.addBox(-4.0f, -1.0f, -2.0f, 4, 9, 5);
        this.leg1.setRotationPoint(-4.0f, 11.0f, 8.0f);
        this.leg1.mirror = true;
        this.setRotation(this.leg1, -0.6320364f, 0.0f, 0.0f);
        this.leg2 = new ModelRenderer(this, 47, 112);
        this.leg2.addBox(1.0f, -1.0f, -2.0f, 4, 9, 5);
        this.leg2.setRotationPoint(3.0f, 11.0f, 8.0f);
        this.leg2.mirror = true;
        this.setRotation(this.leg2, -0.6320364f, 0.0f, 0.0f);
        this.leg3 = new ModelRenderer(this, 18, 47);
        this.leg3.addBox(-3.0f, -2.0f, -2.0f, 4, 9, 4);
        this.leg3.setRotationPoint(-4.0f, 11.0f, -5.0f);
        this.leg3.mirror = true;
        this.setRotation(this.leg3, 0.5576792f, 0.0f, 0.0f);
        this.leg4 = new ModelRenderer(this, 18, 47);
        this.leg4.addBox(0.0f, -2.0f, -2.0f, 4, 9, 4);
        this.leg4.setRotationPoint(3.0f, 11.0f, -5.0f);
        this.leg4.mirror = true;
        this.setRotation(this.leg4, 0.5576792f, 0.0f, 0.0f);
        this.body2 = new ModelRenderer(this, 68, 94);
        this.body2.addBox(-5.0f, 0.0f, 0.0f, 10, 22, 10);
        this.body2.setRotationPoint(0.0f, 12.0f, -10.0f);
        this.body2.mirror = true;
        this.setRotation(this.body2, 1.570796f, 0.0f, 0.0f);
        this.neck1 = new ModelRenderer(this, 43, 85);
        this.neck1.addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6);
        this.neck1.setRotationPoint(0.0f, 7.0f, 25.0f);
        this.neck1.mirror = true;
        this.setRotation(this.neck1, 0.0f, 0.0f, 0.0f);
        this.body3 = new ModelRenderer(this, 70, 59);
        this.body3.addBox(-4.0f, 0.0f, 0.0f, 8, 24, 8);
        this.body3.setRotationPoint(0.0f, 11.0f, -11.0f);
        this.body3.mirror = true;
        this.setRotation(this.body3, 1.570796f, 0.0f, 0.0f);
        this.neck2 = new ModelRenderer(this, 43, 85);
        this.neck2.addBox(-3.0f, -2.0f, -6.0f, 6, 6, 6);
        this.neck2.setRotationPoint(0.0f, 6.0f, -11.0f);
        this.neck2.mirror = true;
        this.setRotation(this.neck2, 0.0f, 0.0f, 0.0f);
        this.neck3 = new ModelRenderer(this, 43, 85);
        this.neck3.addBox(-3.0f, -2.0f, -6.0f, 6, 6, 6);
        this.neck3.setRotationPoint(0.0f, 6.0f, -17.0f);
        this.neck3.mirror = true;
        this.setRotation(this.neck3, 0.0f, 0.0f, 0.0f);
        this.leg5 = new ModelRenderer(this, 47, 99);
        this.leg5.addBox(0.0f, 3.0f, 3.0f, 4, 8, 4);
        this.leg5.setRotationPoint(3.0f, 11.0f, -5.0f);
        this.leg5.mirror = true;
        this.setRotation(this.leg5, -0.5576792f, 0.0f, 0.0f);
        this.leg6 = new ModelRenderer(this, 47, 99);
        this.leg6.addBox(-3.0f, 3.0f, 3.0f, 4, 8, 4);
        this.leg6.setRotationPoint(-4.0f, 11.0f, -5.0f);
        this.leg6.mirror = true;
        this.setRotation(this.leg6, -0.5576792f, 0.0f, 0.0f);
        this.leg7 = new ModelRenderer(this, 38, 73);
        this.leg7.addBox(1.0f, 2.0f, -8.0f, 4, 5, 4);
        this.leg7.setRotationPoint(3.0f, 11.0f, 8.0f);
        this.leg7.mirror = true;
        this.setRotation(this.leg7, 0.8922867f, 0.0f, 0.0f);
        this.leg9 = new ModelRenderer(this, 38, 73);
        this.leg9.addBox(-4.0f, 2.0f, -8.0f, 4, 5, 4);
        this.leg9.setRotationPoint(-4.0f, 11.0f, 8.0f);
        this.leg9.mirror = true;
        this.setRotation(this.leg9, 0.8922867f, 0.0f, 0.0f);
        this.foot1 = new ModelRenderer(this, 43, 63);
        this.foot1.addBox(-3.0f, 11.0f, -5.0f, 4, 2, 6);
        this.foot1.setRotationPoint(-4.0f, 11.0f, -5.0f);
        this.foot1.mirror = true;
        this.setRotation(this.foot1, 0.0f, 0.0f, 0.0f);
        this.foot2 = new ModelRenderer(this, 43, 63);
        this.foot2.addBox(0.0f, 11.0f, -5.0f, 4, 2, 6);
        this.foot2.setRotationPoint(3.0f, 11.0f, -5.0f);
        this.foot2.mirror = true;
        this.setRotation(this.foot2, 0.0f, 0.0f, 0.0f);
        this.leg10 = new ModelRenderer(this, 39, 52);
        this.leg10.addBox(1.0f, 6.0f, 2.0f, 4, 5, 4);
        this.leg10.setRotationPoint(3.0f, 11.0f, 8.0f);
        this.leg10.mirror = true;
        this.setRotation(this.leg10, -0.5576792f, 0.0f, 0.0f);
        this.leg11 = new ModelRenderer(this, 39, 52);
        this.leg11.addBox(-4.0f, 6.0f, 2.0f, 4, 5, 4);
        this.leg11.setRotationPoint(-4.0f, 11.0f, 8.0f);
        this.leg11.mirror = true;
        this.setRotation(this.leg11, -0.5576792f, 0.0f, 0.0f);
        this.foot3 = new ModelRenderer(this, 43, 63);
        this.foot3.addBox(1.0f, 11.0f, -7.0f, 4, 2, 6);
        this.foot3.setRotationPoint(3.0f, 11.0f, 8.0f);
        this.foot3.mirror = true;
        this.setRotation(this.foot3, 0.0f, 0.0f, 0.0f);
        this.foot4 = new ModelRenderer(this, 43, 63);
        this.foot4.addBox(-4.0f, 11.0f, -7.0f, 4, 2, 6);
        this.foot4.setRotationPoint(-4.0f, 11.0f, 8.0f);
        this.foot4.mirror = true;
        this.setRotation(this.foot4, 0.0f, 0.0f, 0.0f);
        this.tail1 = new ModelRenderer(this, 43, 85);
        this.tail1.addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6);
        this.tail1.setRotationPoint(0.0f, 7.0f, 13.0f);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, 0.0f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer(this, 43, 85);
        this.tail2.addBox(-3.0f, -3.0f, 0.0f, 6, 6, 6);
        this.tail2.setRotationPoint(0.0f, 7.0f, 19.0f);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, 0.0f, 0.0f, 0.0f);
        this.tail3 = new ModelRenderer(this, 56, 45);
        this.tail3.addBox(-3.0f, -3.0f, 0.0f, 4, 6, 6);
        this.tail3.setRotationPoint(1.0f, 7.0f, 31.0f);
        this.tail3.mirror = true;
        this.setRotation(this.tail3, 0.0f, 0.0f, 0.0f);
        this.mouth1 = new ModelRenderer(this, 90, 22);
        this.mouth1.addBox(-3.0f, -1.0f, -15.0f, 6, 3, 8);
        this.mouth1.setRotationPoint(0.0f, 6.0f, -23.0f);
        this.mouth1.mirror = true;
        this.setRotation(this.mouth1, 0.0f, 0.0f, 0.0f);
        this.mouth2 = new ModelRenderer(this, 90, 6);
        this.mouth2.addBox(-2.0f, 1.0f, -5.0f, 4, 2, 8);
        this.mouth2.setRotationPoint(0.0f, 7.0f, -32.0f);
        this.mouth2.mirror = true;
        this.setRotation(this.mouth2, 0.0698132f, 0.0f, 0.0f);
        this.tail5 = new ModelRenderer(this, 87, 36);
        this.tail5.addBox(0.0f, 0.0f, -5.0f, 0, 11, 10);
        this.tail5.setRotationPoint(0.0f, 7.0f, 49.0f);
        this.tail5.mirror = true;
        this.setRotation(this.tail5, 1.570796f, 0.0f, 0.0f);
        this.wing1 = new ModelRenderer(this, 26, 40);
        this.wing1.addBox(0.0f, -1.0f, -1.0f, 11, 2, 2);
        this.wing1.setRotationPoint(4.0f, 3.0f, -5.0f);
        this.wing1.mirror = true;
        this.setRotation(this.wing1, 0.0f, -0.4833219f, 0.0f);
        this.wing2 = new ModelRenderer(this, 110, 88);
        this.wing2.addBox(-1.0f, -1.0f, 0.0f, 2, 2, 36);
        this.wing2.setRotationPoint(19.0f, 3.0f, -23.0f);
        this.wing2.mirror = true;
        this.setRotation(this.wing2, 0.0f, 1.041001f, 0.0f);
        this.wing3 = new ModelRenderer(this, 109, 60);
        this.wing3.addBox(-1.0f, -1.0f, -24.0f, 2, 2, 24);
        this.wing3.setRotationPoint(12.0f, 3.0f, -1.0f);
        this.wing3.mirror = true;
        this.setRotation(this.wing3, -0.0090881f, -0.3497888f, 0.0f);
        this.wing4 = new ModelRenderer(this, 26, 40);
        this.wing4.addBox(-11.0f, -1.0f, -1.0f, 11, 2, 2);
        this.wing4.setRotationPoint(-4.0f, 3.0f, -5.0f);
        this.wing4.mirror = true;
        this.setRotation(this.wing4, 0.0f, 0.4833166f, 0.0f);
        this.wing5 = new ModelRenderer(this, 109, 60);
        this.wing5.addBox(-1.0f, -1.0f, -24.0f, 2, 2, 24);
        this.wing5.setRotationPoint(-12.0f, 3.0f, -1.0f);
        this.wing5.mirror = true;
        this.setRotation(this.wing5, -0.0090932f, 0.3323281f, 0.0f);
        this.wing6 = new ModelRenderer(this, 110, 88);
        this.wing6.addBox(-1.0f, -1.0f, 0.0f, 2, 2, 36);
        this.wing6.setRotationPoint(-20.0f, 3.0f, -23.0f);
        this.wing6.mirror = true;
        this.setRotation(this.wing6, 0.0f, -1.041002f, 0.0f);
        this.wing7 = new ModelRenderer(this, 124, 21);
        this.wing7.addBox(-8.0f, 0.0f, 1.0f, 8, 1, 36);
        this.wing7.setRotationPoint(19.0f, 2.0f, -23.0f);
        this.wing7.mirror = true;
        this.setRotation(this.wing7, 0.0f, 1.041001f, 0.0f);
        this.wing8 = new ModelRenderer(this, 122, 10);
        this.wing8.addBox(-11.0f, -1.0f, 0.0f, 28, 1, 8);
        this.wing8.setRotationPoint(12.0f, 3.0f, -1.0f);
        this.wing8.mirror = true;
        this.setRotation(this.wing8, 0.002272f, 1.264073f, -0.0174533f);
        this.wing9 = new ModelRenderer(this, 0, 10);
        this.wing9.addBox(-25.0f, -1.0f, 7.0f, 18, 1, 26);
        this.wing9.setRotationPoint(19.0f, 3.0f, -23.0f);
        this.wing9.mirror = true;
        this.setRotation(this.wing9, 0.002272f, 1.264073f, 0.0f);
        this.wing10 = new ModelRenderer(this, 122, 10);
        this.wing10.addBox(-23.0f, -1.0f, 0.0f, 33, 1, 8);
        this.wing10.setRotationPoint(-12.0f, 3.0f, -1.0f);
        this.wing10.mirror = true;
        this.setRotation(this.wing10, -0.0022689f, -1.226894f, 0.0f);
        this.wing11 = new ModelRenderer(this, 124, 21);
        this.wing11.addBox(0.0f, -1.0f, 1.0f, 8, 1, 36);
        this.wing11.setRotationPoint(-20.0f, 3.0f, -23.0f);
        this.wing11.mirror = true;
        this.setRotation(this.wing11, 0.0f, -1.041002f, 0.0f);
        this.wing12 = new ModelRenderer(this, 0, 10);
        this.wing12.addBox(7.0f, -1.0f, 7.0f, 18, 1, 26);
        this.wing12.setRotationPoint(-20.0f, 3.0f, -23.0f);
        this.wing12.mirror = true;
        this.setRotation(this.wing12, 0.002272f, -1.264072f, 0.0f);
        this.tail4 = new ModelRenderer(this, 56, 45);
        this.tail4.addBox(-3.0f, -3.0f, 0.0f, 4, 6, 6);
        this.tail4.setRotationPoint(1.0f, 7.0f, 37.0f);
        this.tail4.mirror = true;
        this.setRotation(this.tail4, 0.0f, 0.0f, 0.0f);
    }

    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        if (frameEntity == null) return;
        Entity entity=frameEntity;
        float f=frameSwing, f1=frameAmount, f2=frameAge, f3=frameYaw, f4=framePitch, f5=0.0625F;
        matrixStack.push();
this.horn1.setRotationPoint(0.0f, 6.0f, -23.0f);
this.setRotation(this.horn1, 0.4089647f, 0.2602503f, 0.0f);
this.horn2.setRotationPoint(0.0f, 6.0f, -23.0f);
this.setRotation(this.horn2, 0.4089647f, -0.2602503f, 0.0f);
this.tail6.setRotationPoint(0.0f, 7.0f, 43.0f);
this.setRotation(this.tail6, 1.570796f, 0.0f, 0.0f);
this.wing15.setRotationPoint(4.0f, 3.0f, -5.0f);
this.setRotation(this.wing15, -0.0743572f, -0.4089594f, 0.0f);
this.spike1.setRotationPoint(0.0f, 6.0f, -17.0f);
this.setRotation(this.spike1, 0.0f, 0.0f, 0.0f);
this.spike2.setRotationPoint(0.0f, 6.0f, -11.0f);
this.setRotation(this.spike2, 0.0f, 0.0f, 0.0f);
this.spike3.setRotationPoint(0.0f, 7.0f, 25.0f);
this.setRotation(this.spike3, 0.0f, 0.0f, 0.0f);
this.spike4.setRotationPoint(0.0f, 3.0f, -7.0f);
this.setRotation(this.spike4, 0.0f, 0.0f, 0.0f);
this.wing14.setRotationPoint(-4.0f, 3.0f, -5.0f);
this.setRotation(this.wing14, -0.0698132f, 0.4089656f, 0.0f);
this.spike5.setRotationPoint(0.0f, 3.0f, -1.0f);
this.setRotation(this.spike5, 0.0f, 0.0f, 0.0f);
this.spike6.setRotationPoint(0.0f, 3.0f, 5.0f);
this.setRotation(this.spike6, 0.0f, 0.0f, 0.0f);
this.spike7.setRotationPoint(0.0f, 7.0f, 13.0f);
this.setRotation(this.spike7, 0.0f, 0.0f, 0.0f);
this.spike8.setRotationPoint(0.0f, 5.0f, 19.0f);
this.setRotation(this.spike8, 0.0f, 0.0f, 0.0f);
this.spike9.setRotationPoint(0.0f, 7.0f, 31.0f);
this.setRotation(this.spike9, 0.0f, 0.0f, 0.0f);
this.spike10.setRotationPoint(0.0f, 7.0f, 36.0f);
this.setRotation(this.spike10, 0.0f, 0.0f, 0.0f);
this.head.setRotationPoint(0.0f, 6.0f, -23.0f);
this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
this.body.setRotationPoint(0.0f, 5.0f, 2.0f);
this.setRotation(this.body, 1.570796f, 0.0f, 0.0f);
this.leg1.setRotationPoint(-4.0f, 11.0f, 8.0f);
this.setRotation(this.leg1, -0.6320364f, 0.0f, 0.0f);
this.leg2.setRotationPoint(3.0f, 11.0f, 8.0f);
this.setRotation(this.leg2, -0.6320364f, 0.0f, 0.0f);
this.leg3.setRotationPoint(-4.0f, 11.0f, -5.0f);
this.setRotation(this.leg3, 0.5576792f, 0.0f, 0.0f);
this.leg4.setRotationPoint(3.0f, 11.0f, -5.0f);
this.setRotation(this.leg4, 0.5576792f, 0.0f, 0.0f);
this.body2.setRotationPoint(0.0f, 12.0f, -10.0f);
this.setRotation(this.body2, 1.570796f, 0.0f, 0.0f);
this.neck1.setRotationPoint(0.0f, 7.0f, 25.0f);
this.setRotation(this.neck1, 0.0f, 0.0f, 0.0f);
this.body3.setRotationPoint(0.0f, 11.0f, -11.0f);
this.setRotation(this.body3, 1.570796f, 0.0f, 0.0f);
this.neck2.setRotationPoint(0.0f, 6.0f, -11.0f);
this.setRotation(this.neck2, 0.0f, 0.0f, 0.0f);
this.neck3.setRotationPoint(0.0f, 6.0f, -17.0f);
this.setRotation(this.neck3, 0.0f, 0.0f, 0.0f);
this.leg5.setRotationPoint(3.0f, 11.0f, -5.0f);
this.setRotation(this.leg5, -0.5576792f, 0.0f, 0.0f);
this.leg6.setRotationPoint(-4.0f, 11.0f, -5.0f);
this.setRotation(this.leg6, -0.5576792f, 0.0f, 0.0f);
this.leg7.setRotationPoint(3.0f, 11.0f, 8.0f);
this.setRotation(this.leg7, 0.8922867f, 0.0f, 0.0f);
this.leg9.setRotationPoint(-4.0f, 11.0f, 8.0f);
this.setRotation(this.leg9, 0.8922867f, 0.0f, 0.0f);
this.foot1.setRotationPoint(-4.0f, 11.0f, -5.0f);
this.setRotation(this.foot1, 0.0f, 0.0f, 0.0f);
this.foot2.setRotationPoint(3.0f, 11.0f, -5.0f);
this.setRotation(this.foot2, 0.0f, 0.0f, 0.0f);
this.leg10.setRotationPoint(3.0f, 11.0f, 8.0f);
this.setRotation(this.leg10, -0.5576792f, 0.0f, 0.0f);
this.leg11.setRotationPoint(-4.0f, 11.0f, 8.0f);
this.setRotation(this.leg11, -0.5576792f, 0.0f, 0.0f);
this.foot3.setRotationPoint(3.0f, 11.0f, 8.0f);
this.setRotation(this.foot3, 0.0f, 0.0f, 0.0f);
this.foot4.setRotationPoint(-4.0f, 11.0f, 8.0f);
this.setRotation(this.foot4, 0.0f, 0.0f, 0.0f);
this.tail1.setRotationPoint(0.0f, 7.0f, 13.0f);
this.setRotation(this.tail1, 0.0f, 0.0f, 0.0f);
this.tail2.setRotationPoint(0.0f, 7.0f, 19.0f);
this.setRotation(this.tail2, 0.0f, 0.0f, 0.0f);
this.tail3.setRotationPoint(1.0f, 7.0f, 31.0f);
this.setRotation(this.tail3, 0.0f, 0.0f, 0.0f);
this.mouth1.setRotationPoint(0.0f, 6.0f, -23.0f);
this.setRotation(this.mouth1, 0.0f, 0.0f, 0.0f);
this.mouth2.setRotationPoint(0.0f, 7.0f, -32.0f);
this.setRotation(this.mouth2, 0.0698132f, 0.0f, 0.0f);
this.tail5.setRotationPoint(0.0f, 7.0f, 49.0f);
this.setRotation(this.tail5, 1.570796f, 0.0f, 0.0f);
this.wing1.setRotationPoint(4.0f, 3.0f, -5.0f);
this.setRotation(this.wing1, 0.0f, -0.4833219f, 0.0f);
this.wing2.setRotationPoint(19.0f, 3.0f, -23.0f);
this.setRotation(this.wing2, 0.0f, 1.041001f, 0.0f);
this.wing3.setRotationPoint(12.0f, 3.0f, -1.0f);
this.setRotation(this.wing3, -0.0090881f, -0.3497888f, 0.0f);
this.wing4.setRotationPoint(-4.0f, 3.0f, -5.0f);
this.setRotation(this.wing4, 0.0f, 0.4833166f, 0.0f);
this.wing5.setRotationPoint(-12.0f, 3.0f, -1.0f);
this.setRotation(this.wing5, -0.0090932f, 0.3323281f, 0.0f);
this.wing6.setRotationPoint(-20.0f, 3.0f, -23.0f);
this.setRotation(this.wing6, 0.0f, -1.041002f, 0.0f);
this.wing7.setRotationPoint(19.0f, 2.0f, -23.0f);
this.setRotation(this.wing7, 0.0f, 1.041001f, 0.0f);
this.wing8.setRotationPoint(12.0f, 3.0f, -1.0f);
this.setRotation(this.wing8, 0.002272f, 1.264073f, -0.0174533f);
this.wing9.setRotationPoint(19.0f, 3.0f, -23.0f);
this.setRotation(this.wing9, 0.002272f, 1.264073f, 0.0f);
this.wing10.setRotationPoint(-12.0f, 3.0f, -1.0f);
this.setRotation(this.wing10, -0.0022689f, -1.226894f, 0.0f);
this.wing11.setRotationPoint(-20.0f, 3.0f, -23.0f);
this.setRotation(this.wing11, 0.0f, -1.041002f, 0.0f);
this.wing12.setRotationPoint(-20.0f, 3.0f, -23.0f);
this.setRotation(this.wing12, 0.002272f, -1.264072f, 0.0f);
this.tail4.setRotationPoint(1.0f, 7.0f, 37.0f);
this.setRotation(this.tail4, 0.0f, 0.0f, 0.0f);

        DragonEntity.CustomEntity e = (DragonEntity.CustomEntity)entity;
        float newangle = 0.0f;
        float lspeed = 0.0f;
        RenderInfo r = null;
        float tailspeed = 0.76f;
        float tailamp = 0.45f;
        this.legacyAngles(f, f1, f2, f3, f4, f5, entity);
        r = e.getRenderInfo();
        if ((double)f1 > 0.001) {
            lspeed = (float)((e.prevPosX - e.getPosX()) * (e.prevPosX - e.getPosX()) + (e.prevPosZ - e.getPosZ()) * (e.prevPosZ - e.getPosZ()));
            lspeed = (float)Math.sqrt(lspeed);
            newangle = MathHelper.cos((float)(f2 * 1.25f * this.wingspeed)) * (float)Math.PI * lspeed * 0.6f;
        } else {
            newangle = 0.0f;
        }
        if (e.getActivity() != 0) {
            newangle = 1.0f;
            this.leg4.rotateAngleX = 0.557f - newangle;
            this.leg5.rotateAngleX = -0.557f - newangle;
            this.foot2.rotateAngleX = -newangle;
            this.leg3.rotateAngleX = 0.557f - newangle;
            this.leg6.rotateAngleX = -0.557f - newangle;
            this.foot1.rotateAngleX = -newangle;
            this.leg2.rotateAngleX = -0.632f + newangle;
            this.leg7.rotateAngleX = 0.89f + newangle;
            this.leg10.rotateAngleX = -0.557f + newangle;
            this.foot3.rotateAngleX = newangle;
            this.leg1.rotateAngleX = -0.632f + newangle;
            this.leg9.rotateAngleX = 0.89f + newangle;
            this.leg11.rotateAngleX = -0.557f + newangle;
            this.foot4.rotateAngleX = newangle;
        } else {
            this.leg4.rotateAngleX = 0.557f + newangle;
            this.leg5.rotateAngleX = -0.557f + newangle;
            this.foot2.rotateAngleX = newangle;
            this.leg3.rotateAngleX = 0.557f - newangle;
            this.leg6.rotateAngleX = -0.557f - newangle;
            this.foot1.rotateAngleX = -newangle;
            this.leg2.rotateAngleX = -0.632f - newangle;
            this.leg7.rotateAngleX = 0.89f - newangle;
            this.leg10.rotateAngleX = -0.557f - newangle;
            this.foot3.rotateAngleX = -newangle;
            this.leg1.rotateAngleX = -0.632f + newangle;
            this.leg9.rotateAngleX = 0.89f + newangle;
            this.leg11.rotateAngleX = -0.557f + newangle;
            this.foot4.rotateAngleX = newangle;
        }
        newangle = e.getAttacking() != 0 ? (e.getActivity() != 0 ? MathHelper.cos((float)(f2 * 0.75f * this.wingspeed)) * (float)Math.PI * 0.28f : -0.45f + MathHelper.cos((float)(f2 * 0.85f * this.wingspeed)) * (float)Math.PI * 0.2f) : (e.getActivity() != 0 ? MathHelper.cos((float)(f2 * 0.75f * this.wingspeed)) * (float)Math.PI * 0.28f : -0.85f + MathHelper.cos((float)(f2 * 0.2f * this.wingspeed)) * (float)Math.PI * 0.028f);
        this.wing1.rotateAngleZ = newangle;
        this.wing15.rotateAngleZ = newangle;
        this.wing3.rotateAngleZ = newangle * 4.0f / 3.0f;
        this.wing3.rotationPointY = this.wing1.rotationPointY + (float)Math.sin(this.wing1.rotateAngleZ) * 7.0f;
        this.wing3.rotationPointX = this.wing1.rotationPointX + (float)Math.cos(this.wing1.rotateAngleZ) * 7.0f;
        this.wing8.rotateAngleZ = newangle * 4.0f / 3.0f;
        this.wing8.rotationPointY = this.wing3.rotationPointY;
        this.wing8.rotationPointX = this.wing3.rotationPointX;
        this.wing2.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.wing2.rotationPointY = this.wing3.rotationPointY + (float)Math.sin(this.wing3.rotateAngleZ) * 6.0f;
        this.wing2.rotationPointX = this.wing3.rotationPointX + (float)Math.cos(this.wing3.rotateAngleZ) * 6.0f;
        this.wing7.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.wing7.rotationPointY = this.wing2.rotationPointY;
        this.wing7.rotationPointX = this.wing2.rotationPointX;
        this.wing9.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.wing9.rotationPointY = this.wing2.rotationPointY;
        this.wing9.rotationPointX = this.wing2.rotationPointX;
        this.wing4.rotateAngleZ = -newangle;
        this.wing14.rotateAngleZ = -newangle;
        this.wing5.rotateAngleZ = -newangle * 4.0f / 3.0f;
        this.wing5.rotationPointY = this.wing4.rotationPointY - (float)Math.sin(this.wing4.rotateAngleZ) * 7.0f;
        this.wing5.rotationPointX = this.wing4.rotationPointX - (float)Math.cos(this.wing4.rotateAngleZ) * 7.0f;
        this.wing10.rotateAngleZ = -newangle * 4.0f / 3.0f;
        this.wing10.rotationPointY = this.wing5.rotationPointY;
        this.wing10.rotationPointX = this.wing5.rotationPointX;
        this.wing6.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.wing6.rotationPointY = this.wing5.rotationPointY - (float)Math.sin(this.wing5.rotateAngleZ) * 6.0f;
        this.wing6.rotationPointX = this.wing5.rotationPointX - (float)Math.cos(this.wing5.rotateAngleZ) * 6.0f;
        this.wing11.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.wing11.rotationPointY = this.wing6.rotationPointY;
        this.wing11.rotationPointX = this.wing6.rotationPointX;
        this.wing12.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.wing12.rotationPointY = this.wing6.rotationPointY;
        this.wing12.rotationPointX = this.wing6.rotationPointX;
        if (e.getAttacking() != 0) {
            tailspeed = 0.96f;
            tailamp = 0.75f;
        }
        if (e.getActivity() == 0 && e.getAttacking() == 0) {
            tailspeed = 0.22f;
            tailamp = 0.22f;
        }
        if (e.isChildModel()) {
            tailspeed = 0.0f;
            tailamp = 0.0f;
        }
        this.tail1.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * 0.04f;
        this.spike10.rotationPointZ = this.tail1.rotationPointZ;
        this.spike10.rotationPointX = this.tail1.rotationPointX;
        this.spike10.rotateAngleY = this.tail1.rotateAngleY;
        this.tail2.rotationPointZ = this.tail1.rotationPointZ + (float)Math.cos(this.tail1.rotateAngleY) * 6.0f;
        this.tail2.rotationPointX = this.tail1.rotationPointX + (float)Math.sin(this.tail1.rotateAngleY) * 6.0f;
        this.tail2.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.125f;
        this.spike7.rotationPointZ = this.tail2.rotationPointZ;
        this.spike7.rotationPointX = this.tail2.rotationPointX;
        this.spike7.rotateAngleY = this.tail2.rotateAngleY;
        this.neck1.rotationPointZ = this.tail2.rotationPointZ + (float)Math.cos(this.tail2.rotateAngleY) * 6.0f;
        this.neck1.rotationPointX = this.tail2.rotationPointX + (float)Math.sin(this.tail2.rotateAngleY) * 6.0f;
        this.neck1.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.25f;
        this.spike8.rotationPointZ = this.neck1.rotationPointZ;
        this.spike8.rotationPointX = this.neck1.rotationPointX;
        this.spike8.rotateAngleY = this.neck1.rotateAngleY;
        this.tail3.rotationPointZ = this.neck1.rotationPointZ + (float)Math.cos(this.neck1.rotateAngleY) * 6.0f;
        this.tail3.rotationPointX = this.neck1.rotationPointX + 1.0f + (float)Math.sin(this.neck1.rotateAngleY) * 6.0f;
        this.tail3.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.375f;
        this.spike3.rotationPointZ = this.tail3.rotationPointZ;
        this.spike3.rotationPointX = this.tail3.rotationPointX - 1.0f;
        this.spike3.rotateAngleY = this.tail3.rotateAngleY;
        this.tail4.rotationPointZ = this.tail3.rotationPointZ + (float)Math.cos(this.tail3.rotateAngleY) * 6.0f;
        this.tail4.rotationPointX = this.tail3.rotationPointX + (float)Math.sin(this.tail3.rotateAngleY) * 6.0f;
        this.tail4.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.5f;
        this.spike9.rotationPointZ = this.tail4.rotationPointZ;
        this.spike9.rotationPointX = this.tail4.rotationPointX - 1.0f;
        this.spike9.rotateAngleY = this.tail4.rotateAngleY;
        this.tail6.rotationPointZ = this.tail4.rotationPointZ + (float)Math.cos(this.tail4.rotateAngleY) * 6.0f;
        this.tail6.rotationPointX = this.tail4.rotationPointX - 1.0f + (float)Math.sin(this.tail4.rotateAngleY) * 6.0f;
        this.tail6.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.625f;
        this.tail5.rotationPointZ = this.tail6.rotationPointZ + (float)Math.cos(this.tail6.rotateAngleY) * 6.0f;
        this.tail5.rotationPointX = this.tail6.rotationPointX - 0.5f + (float)Math.sin(this.tail6.rotateAngleY) * 6.0f;
        this.tail5.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp * 0.75f;
        if (e.getActivity() == 1) {
            f3 = (e.prevRotationYaw - e.rotationYaw) * 8.0f;
            f3 = -f3;
            r.rf1 += (f3 - r.rf1) / 60.0f;
            if (r.rf1 > 50.0f) {
                r.rf1 = 50.0f;
            }
            if (r.rf1 < -50.0f) {
                r.rf1 = -50.0f;
            }
            f3 = r.rf1;
        } else {
            f3 /= 2.0f;
        }
        this.spike2.rotateAngleY = this.neck2.rotateAngleY = (float)Math.toRadians(f3) * 0.25f;
        this.neck3.rotationPointZ = this.neck2.rotationPointZ - (float)Math.cos(this.neck2.rotateAngleY) * 6.0f;
        this.neck3.rotationPointX = this.neck2.rotationPointX - (float)Math.sin(this.neck2.rotateAngleY) * 6.0f;
        this.neck3.rotateAngleY = (float)Math.toRadians(f3) * 0.5f;
        this.spike1.rotationPointZ = this.neck3.rotationPointZ;
        this.spike1.rotationPointX = this.neck3.rotationPointX;
        this.spike1.rotateAngleY = this.neck3.rotateAngleY;
        this.head.rotationPointZ = this.neck3.rotationPointZ - (float)Math.cos(this.neck3.rotateAngleY) * 6.0f;
        this.head.rotationPointX = this.neck3.rotationPointX - (float)Math.sin(this.neck3.rotateAngleY) * 6.0f;
        this.head.rotateAngleY = (float)Math.toRadians(f3) * 0.75f;
        this.mouth1.rotationPointZ = this.head.rotationPointZ;
        this.mouth1.rotationPointX = this.head.rotationPointX;
        this.mouth1.rotateAngleY = this.head.rotateAngleY;
        this.horn1.rotationPointZ = this.head.rotationPointZ;
        this.horn1.rotationPointX = this.head.rotationPointX;
        this.horn1.rotateAngleY = this.head.rotateAngleY + 0.26f;
        this.horn2.rotationPointZ = this.head.rotationPointZ;
        this.horn2.rotationPointX = this.head.rotationPointX;
        this.horn2.rotateAngleY = this.head.rotateAngleY - 0.26f;
        this.mouth2.rotationPointZ = this.head.rotationPointZ - (float)Math.cos(this.head.rotateAngleY) * 9.0f;
        this.mouth2.rotationPointX = this.head.rotationPointX - (float)Math.sin(this.head.rotateAngleY) * 9.0f;
        this.mouth2.rotateAngleY = this.head.rotateAngleY;
        newangle = MathHelper.cos((float)(f2 * 1.5f * this.wingspeed)) * (float)Math.PI * 0.14f;
        this.mouth2.rotateAngleX = e.getAttacking() != 0 ? 0.4f + newangle : 0.07f;
        e.setRenderInfo(r);
        this.horn1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.horn2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing15.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing14.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.spike10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leg11.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.foot4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouth1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mouth2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing11.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing12.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    
        matrixStack.pop();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void legacyAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
    }
}


}
