package net.mcreator.xillysorespawn.entity.renderer;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.mcreator.xillysorespawn.entity.EmperorScorpionEntity;
import net.mcreator.xillysorespawn.entity.OreSpawnLogic;

@OnlyIn(Dist.CLIENT)
public class EmperorScorpionRenderer {
    private static final String TEXTURE = "xillys_orespawn:textures/entities/emperorscorpion.png";
    public static class ModelRegisterHandler {
        @SubscribeEvent @OnlyIn(Dist.CLIENT)
        public void registerModels(ModelRegistryEvent event) {
            RenderingRegistry.registerEntityRenderingHandler(EmperorScorpionEntity.entity, manager ->
                new MobRenderer(manager, new ModelEmperorScorpion(0.22F), 1.425F) {
                    @Override public ResourceLocation getEntityTexture(Entity entity) { return new ResourceLocation(TEXTURE); }
                    @Override protected void preRenderCallback(LivingEntity entity, MatrixStack stack, float partialTick) {
                        float modelScale = 1.5F;
                        stack.scale(modelScale, modelScale, modelScale);
                    }
                });
        }
    }

public static class ModelEmperorScorpion extends EntityModel<Entity> {
    // Exact legacy render order recovered from bytecode; do not add a second addChild rig.
    private Entity frameEntity;
    private float frameSwing, frameAmount, frameAge, frameYaw, framePitch;
    @Override public void setRotationAngles(Entity entity, float swing, float amount, float age, float yaw, float pitch) {
        frameEntity=entity; frameSwing=swing; frameAmount=amount; frameAge=age; frameYaw=yaw; framePitch=pitch;
    }

    private float wingspeed = 1.0f;
    private final ModelRenderer Head;
    private final ModelRenderer Seg1;
    private final ModelRenderer Seg2;
    private final ModelRenderer Seg3;
    private final ModelRenderer Seg4;
    private final ModelRenderer Seg5;
    private final ModelRenderer Seg6;
    private final ModelRenderer Seg7;
    private final ModelRenderer Seg8;
    private final ModelRenderer Tailseg1;
    private final ModelRenderer Tailseg2;
    private final ModelRenderer Tailseg3;
    private final ModelRenderer Tailseg4;
    private final ModelRenderer Tailseg5;
    private final ModelRenderer Tailseg6;
    private final ModelRenderer Tailseg7;
    private final ModelRenderer Tailseg8;
    private final ModelRenderer Stinger1;
    private final ModelRenderer Stinger2;
    private final ModelRenderer Stinger3;
    private final ModelRenderer LeftShoulder;
    private final ModelRenderer LeftArmSeg1;
    private final ModelRenderer LeftArmSeg2;
    private final ModelRenderer LeftArmSeg3;
    private final ModelRenderer LeftArmSeg4;
    private final ModelRenderer RightShoulder;
    private final ModelRenderer RightArmSeg1;
    private final ModelRenderer RightArmSeg2;
    private final ModelRenderer RightArmSeg3;
    private final ModelRenderer RightArmSeg4;
    private final ModelRenderer RightPincer;
    private final ModelRenderer LeftPincer;
    private final ModelRenderer Lefteye;
    private final ModelRenderer Righteye;
    private final ModelRenderer RightMandible;
    private final ModelRenderer LeftMandible;
    private final ModelRenderer RightManPart2;
    private final ModelRenderer LeftManPart2;
    private final ModelRenderer Leg1Seg1;
    private final ModelRenderer Leg1Seg2;
    private final ModelRenderer Leg1Seg3;
    private final ModelRenderer Leg1Seg4;
    private final ModelRenderer Leg1Seg5;
    private final ModelRenderer Leg2Seg1;
    private final ModelRenderer Leg2Seg2;
    private final ModelRenderer Leg2Seg3;
    private final ModelRenderer Leg2Seg4;
    private final ModelRenderer Leg2Seg5;
    private final ModelRenderer Leg3Seg1;
    private final ModelRenderer Leg3Seg2;
    private final ModelRenderer Leg3Seg3;
    private final ModelRenderer Leg3Seg4;
    private final ModelRenderer Leg3Seg5;
    private final ModelRenderer Leg4Seg1;
    private final ModelRenderer Leg4Seg2;
    private final ModelRenderer Leg4Seg3;
    private final ModelRenderer Leg4Seg4;
    private final ModelRenderer Leg4Seg5;
    private final ModelRenderer Leg5Seg1;
    private final ModelRenderer Leg5Seg2;
    private final ModelRenderer Leg5Seg3;
    private final ModelRenderer Leg5Seg4;
    private final ModelRenderer Leg5Seg5;
    private final ModelRenderer Leg6Seg1;
    private final ModelRenderer Leg6Seg2;
    private final ModelRenderer Leg6Seg3;
    private final ModelRenderer Leg6Seg4;
    private final ModelRenderer Leg6Seg5;
    private final ModelRenderer Leg7Seg1;
    private final ModelRenderer Leg7Seg2;
    private final ModelRenderer Leg7Seg3;
    private final ModelRenderer Leg7Seg4;
    private final ModelRenderer Leg7Seg5;
    private final ModelRenderer Leg8Seg1;
    private final ModelRenderer Leg8Seg2;
    private final ModelRenderer Leg8Seg3;
    private final ModelRenderer Leg8Seg4;
    private final ModelRenderer Leg8Seg5;

    public ModelEmperorScorpion(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.Head = new ModelRenderer(this, 0, 104);
        this.Head.addBox(-9.0f, -4.0f, -16.0f, 18, 8, 16);
        this.Head.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
        this.Seg1 = new ModelRenderer(this, 0, 78);
        this.Seg1.addBox(-9.0f, -4.0f, 0.0f, 18, 8, 4);
        this.Seg1.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg1.mirror = true;
        this.setRotation(this.Seg1, 0.0f, 0.0f, 0.0f);
        this.Seg2 = new ModelRenderer(this, 0, 65);
        this.Seg2.addBox(-8.5f, -4.1f, 4.0f, 17, 8, 4);
        this.Seg2.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg2.mirror = true;
        this.setRotation(this.Seg2, 0.0f, 0.0f, 0.0f);
        this.Seg3 = new ModelRenderer(this, 0, 50);
        this.Seg3.addBox(-9.5f, -4.0f, 8.0f, 19, 8, 5);
        this.Seg3.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg3.mirror = true;
        this.setRotation(this.Seg3, 0.0f, 0.0f, 0.0f);
        this.Seg4 = new ModelRenderer(this, 0, 35);
        this.Seg4.addBox(-9.0f, -4.1f, 13.0f, 18, 8, 6);
        this.Seg4.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg4.mirror = true;
        this.setRotation(this.Seg4, 0.0f, 0.0f, 0.0f);
        this.Seg5 = new ModelRenderer(this, 45, 91);
        this.Seg5.addBox(-8.5f, -4.0f, 19.0f, 17, 8, 3);
        this.Seg5.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg5.mirror = true;
        this.setRotation(this.Seg5, 0.0f, 0.0f, 0.0f);
        this.Seg6 = new ModelRenderer(this, 45, 79);
        this.Seg6.addBox(-8.0f, -4.1f, 22.0f, 16, 8, 3);
        this.Seg6.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg6.mirror = true;
        this.setRotation(this.Seg6, 0.0f, 0.0f, 0.0f);
        this.Seg7 = new ModelRenderer(this, 43, 66);
        this.Seg7.addBox(-7.0f, -4.0f, 25.0f, 14, 8, 3);
        this.Seg7.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg7.mirror = true;
        this.setRotation(this.Seg7, 0.0f, 0.0f, 0.0f);
        this.Seg8 = new ModelRenderer(this, 49, 53);
        this.Seg8.addBox(-5.5f, -4.1f, 28.0f, 11, 8, 2);
        this.Seg8.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Seg8.mirror = true;
        this.setRotation(this.Seg8, 0.0f, 0.0f, 0.0f);
        this.Tailseg1 = new ModelRenderer(this, 92, 0);
        this.Tailseg1.addBox(-4.0f, -1.0f, 0.0f, 8, 4, 10);
        this.Tailseg1.setRotationPoint(0.0f, 13.0f, 20.0f);
        this.Tailseg1.mirror = true;
        this.setRotation(this.Tailseg1, 0.5948578f, 0.0f, 0.0f);
        this.Tailseg2 = new ModelRenderer(this, 90, 15);
        this.Tailseg2.addBox(-3.5f, -2.0f, 0.0f, 7, 4, 12);
        this.Tailseg2.setRotationPoint(0.0f, 10.0f, 27.0f);
        this.Tailseg2.mirror = true;
        this.setRotation(this.Tailseg2, 1.07818f, 0.0f, 0.0f);
        this.Tailseg3 = new ModelRenderer(this, 96, 32);
        this.Tailseg3.addBox(-3.0f, -2.0f, 1.0f, 6, 4, 10);
        this.Tailseg3.setRotationPoint(0.0f, 2.0f, 32.0f);
        this.Tailseg3.mirror = true;
        this.setRotation(this.Tailseg3, 1.710216f, 0.0f, 0.0f);
        this.Tailseg4 = new ModelRenderer(this, 96, 47);
        this.Tailseg4.addBox(-2.5f, -2.0f, 0.0f, 5, 4, 11);
        this.Tailseg4.setRotationPoint(0.0f, -7.0f, 31.0f);
        this.Tailseg4.mirror = true;
        this.setRotation(this.Tailseg4, 2.267895f, 0.0f, 0.0f);
        this.Tailseg5 = new ModelRenderer(this, 98, 63);
        this.Tailseg5.addBox(-2.0f, -2.0f, 0.0f, 4, 4, 11);
        this.Tailseg5.setRotationPoint(0.0f, -14.0f, 25.0f);
        this.Tailseg5.mirror = true;
        this.setRotation(this.Tailseg5, 2.899932f, 0.0f, 0.0f);
        this.Tailseg6 = new ModelRenderer(this, 98, 79);
        this.Tailseg6.addBox(-2.0f, -2.0f, 0.0f, 4, 4, 11);
        this.Tailseg6.setRotationPoint(0.0f, -17.0f, 16.0f);
        this.Tailseg6.mirror = true;
        this.setRotation(this.Tailseg6, -2.602503f, 0.0f, 0.0f);
        this.Tailseg7 = new ModelRenderer(this, 94, 95);
        this.Tailseg7.addBox(-3.0f, -2.0f, 0.0f, 6, 4, 11);
        this.Tailseg7.setRotationPoint(0.0f, -12.0f, 8.0f);
        this.Tailseg7.mirror = true;
        this.setRotation(this.Tailseg7, -0.2230717f, 0.0f, 0.0f);
        this.Tailseg8 = new ModelRenderer(this, 102, 111);
        this.Tailseg8.addBox(-4.0f, -2.0f, 4.0f, 8, 4, 5);
        this.Tailseg8.setRotationPoint(0.0f, -12.0f, 8.0f);
        this.Tailseg8.mirror = true;
        this.setRotation(this.Tailseg8, -0.2230717f, 0.0f, 0.0f);
        this.Stinger1 = new ModelRenderer(this, 83, 0);
        this.Stinger1.addBox(-0.5f, -0.5f, 0.0f, 1, 1, 3);
        this.Stinger1.setRotationPoint(0.0f, -10.0f, 18.0f);
        this.Stinger1.mirror = true;
        this.setRotation(this.Stinger1, 0.2230717f, 0.0f, 0.0f);
        this.Stinger2 = new ModelRenderer(this, 83, 0);
        this.Stinger2.addBox(-0.5f, -0.5f, 0.0f, 1, 1, 3);
        this.Stinger2.setRotationPoint(0.0f, -10.5f, 20.5f);
        this.Stinger2.mirror = true;
        this.setRotation(this.Stinger2, -0.2602503f, 0.0f, 0.0f);
        this.Stinger3 = new ModelRenderer(this, 79, 5);
        this.Stinger3.addBox(-0.5f, -0.5f, 0.0f, 1, 1, 5);
        this.Stinger3.setRotationPoint(0.0f, -10.0f, 23.0f);
        this.Stinger3.mirror = true;
        this.setRotation(this.Stinger3, -0.8551081f, 0.0f, 0.0f);
        this.LeftShoulder = new ModelRenderer(this, 69, 103);
        this.LeftShoulder.addBox(-3.0f, -3.0f, -4.0f, 6, 6, 4);
        this.LeftShoulder.setRotationPoint(7.0f, 13.0f, -22.0f);
        this.LeftShoulder.mirror = true;
        this.setRotation(this.LeftShoulder, 0.0f, -0.8551081f, 0.0f);
        this.LeftArmSeg1 = new ModelRenderer(this, 55, 0);
        this.LeftArmSeg1.addBox(-3.0f, -3.0f, -10.0f, 4, 6, 13);
        this.LeftArmSeg1.setRotationPoint(10.0f, 13.0f, -24.0f);
        this.LeftArmSeg1.mirror = true;
        this.setRotation(this.LeftArmSeg1, 0.0f, -2.044824f, 0.0f);
        this.LeftArmSeg2 = new ModelRenderer(this, 130, 0);
        this.LeftArmSeg2.addBox(-7.0f, -3.0f, -17.0f, 8, 6, 17);
        this.LeftArmSeg2.setRotationPoint(19.0f, 13.0f, -22.0f);
        this.LeftArmSeg2.mirror = true;
        this.setRotation(this.LeftArmSeg2, 0.0f, -0.7435722f, 0.0f);
        this.LeftArmSeg3 = new ModelRenderer(this, 130, 50);
        this.LeftArmSeg3.addBox(-3.0f, -3.0f, -24.0f, 4, 6, 24);
        this.LeftArmSeg3.setRotationPoint(29.0f, 13.0f, -33.0f);
        this.LeftArmSeg3.mirror = true;
        this.setRotation(this.LeftArmSeg3, 0.0f, 0.3717861f, 0.0f);
        this.LeftArmSeg4 = new ModelRenderer(this, 181, 0);
        this.LeftArmSeg4.addBox(-3.0f, -3.0f, -14.0f, 8, 6, 12);
        this.LeftArmSeg4.setRotationPoint(29.0f, 13.0f, -33.0f);
        this.LeftArmSeg4.mirror = true;
        this.setRotation(this.LeftArmSeg4, 0.0f, 1.487144f, 0.0f);
        this.RightShoulder = new ModelRenderer(this, 69, 103);
        this.RightShoulder.addBox(-3.0f, -3.0f, -4.0f, 6, 6, 4);
        this.RightShoulder.setRotationPoint(-7.0f, 13.0f, -22.0f);
        this.RightShoulder.mirror = true;
        this.setRotation(this.RightShoulder, 0.0f, 0.8551066f, 0.0f);
        this.RightArmSeg1 = new ModelRenderer(this, 55, 0);
        this.RightArmSeg1.addBox(-1.0f, -3.0f, -10.0f, 4, 6, 13);
        this.RightArmSeg1.setRotationPoint(-10.0f, 13.0f, -24.0f);
        this.RightArmSeg1.mirror = true;
        this.setRotation(this.RightArmSeg1, 0.0f, 2.044828f, 0.0f);
        this.RightArmSeg2 = new ModelRenderer(this, 130, 0);
        this.RightArmSeg2.addBox(-1.0f, -3.0f, -17.0f, 8, 6, 17);
        this.RightArmSeg2.setRotationPoint(-19.0f, 13.0f, -22.0f);
        this.RightArmSeg2.mirror = true;
        this.setRotation(this.RightArmSeg2, 0.0f, 0.7435801f, 0.0f);
        this.RightArmSeg3 = new ModelRenderer(this, 130, 50);
        this.RightArmSeg3.addBox(-1.0f, -3.0f, -24.0f, 4, 6, 24);
        this.RightArmSeg3.setRotationPoint(-29.0f, 13.0f, -33.0f);
        this.RightArmSeg3.mirror = true;
        this.setRotation(this.RightArmSeg3, 0.0f, -0.37179f, 0.0f);
        this.RightArmSeg4 = new ModelRenderer(this, 181, 0);
        this.RightArmSeg4.addBox(-5.0f, -3.0f, -14.0f, 8, 6, 12);
        this.RightArmSeg4.setRotationPoint(-29.0f, 13.0f, -33.0f);
        this.RightArmSeg4.mirror = true;
        this.setRotation(this.RightArmSeg4, 0.0f, -1.487143f, 0.0f);
        this.RightPincer = new ModelRenderer(this, 130, 24);
        this.RightPincer.addBox(-1.0f, -3.0f, -19.0f, 2, 6, 19);
        this.RightPincer.setRotationPoint(-17.0f, 13.0f, -33.0f);
        this.RightPincer.mirror = true;
        this.setRotation(this.RightPincer, 0.0f, -0.0743611f, 0.0f);
        this.LeftPincer = new ModelRenderer(this, 130, 24);
        this.LeftPincer.addBox(-1.0f, -3.0f, -19.0f, 2, 6, 19);
        this.LeftPincer.setRotationPoint(17.0f, 13.0f, -33.0f);
        this.LeftPincer.mirror = true;
        this.setRotation(this.LeftPincer, 0.0f, 0.0743685f, 0.0f);
        this.Lefteye = new ModelRenderer(this, 0, 113);
        this.Lefteye.addBox(-0.5f, -5.0f, -7.5f, 3, 2, 3);
        this.Lefteye.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Lefteye.mirror = true;
        this.setRotation(this.Lefteye, 0.0f, 0.0f, 0.2974289f);
        this.Righteye = new ModelRenderer(this, 0, 113);
        this.Righteye.addBox(-2.5f, -5.0f, -7.5f, 3, 2, 3);
        this.Righteye.setRotationPoint(0.0f, 13.0f, -8.0f);
        this.Righteye.mirror = true;
        this.setRotation(this.Righteye, 0.0f, 0.0f, -0.2974216f);
        this.RightMandible = new ModelRenderer(this, 76, 55);
        this.RightMandible.addBox(-2.0f, -3.0f, -4.0f, 4, 4, 4);
        this.RightMandible.setRotationPoint(-2.0f, 13.0f, -23.0f);
        this.RightMandible.mirror = true;
        this.setRotation(this.RightMandible, 0.1115358f, 0.3346075f, 0.0f);
        this.LeftMandible = new ModelRenderer(this, 76, 55);
        this.LeftMandible.addBox(-2.0f, -3.0f, -4.0f, 4, 4, 4);
        this.LeftMandible.setRotationPoint(2.0f, 13.0f, -23.0f);
        this.LeftMandible.mirror = true;
        this.setRotation(this.LeftMandible, 0.111544f, -0.3346145f, 0.0f);
        this.RightManPart2 = new ModelRenderer(this, 82, 64);
        this.RightManPart2.addBox(-0.5f, -0.5f, -6.0f, 1, 1, 6);
        this.RightManPart2.setRotationPoint(-3.0f, 11.0f, -26.0f);
        this.RightManPart2.mirror = true;
        this.setRotation(this.RightManPart2, 1.189716f, 0.0f, 0.0f);
        this.LeftManPart2 = new ModelRenderer(this, 82, 64);
        this.LeftManPart2.addBox(-0.5f, -0.5f, -6.0f, 1, 1, 6);
        this.LeftManPart2.setRotationPoint(3.0f, 11.0f, -26.0f);
        this.LeftManPart2.mirror = true;
        this.setRotation(this.LeftManPart2, 1.188848f, 0.0f, 0.0f);
        this.Leg1Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg1Seg1.addBox(0.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg1Seg1.setRotationPoint(9.0f, 13.0f, -10.0f);
        this.Leg1Seg1.mirror = true;
        this.setRotation(this.Leg1Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg1Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg1Seg2.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg1Seg2.setRotationPoint(12.0f, 13.0f, -10.0f);
        this.Leg1Seg2.mirror = true;
        this.setRotation(this.Leg1Seg2, 0.0f, 0.0f, -0.9294576f);
        this.Leg1Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg1Seg3.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg1Seg3.setRotationPoint(18.0f, 3.0f, -10.0f);
        this.Leg1Seg3.mirror = true;
        this.setRotation(this.Leg1Seg3, 0.0f, 0.0f, 0.6320361f);
        this.Leg1Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg1Seg4.addBox(0.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg1Seg4.setRotationPoint(26.0f, 12.0f, -10.0f);
        this.Leg1Seg4.mirror = true;
        this.setRotation(this.Leg1Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg1Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg1Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg1Seg5.setRotationPoint(27.0f, 19.0f, -10.0f);
        this.Leg1Seg5.mirror = true;
        this.setRotation(this.Leg1Seg5, 0.0f, 0.0f, 0.669215f);
        this.Leg2Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg2Seg1.addBox(0.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg2Seg1.setRotationPoint(8.5f, 13.0f, -4.0f);
        this.Leg2Seg1.mirror = true;
        this.setRotation(this.Leg2Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg2Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg2Seg2.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg2Seg2.setRotationPoint(12.0f, 13.0f, -4.0f);
        this.Leg2Seg2.mirror = true;
        this.setRotation(this.Leg2Seg2, 0.0f, 0.0f, -0.9294576f);
        this.Leg2Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg2Seg3.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg2Seg3.setRotationPoint(18.0f, 3.0f, -4.0f);
        this.Leg2Seg3.mirror = true;
        this.setRotation(this.Leg2Seg3, 0.0f, 0.0f, 0.6320361f);
        this.Leg2Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg2Seg4.addBox(0.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg2Seg4.setRotationPoint(26.0f, 12.0f, -4.0f);
        this.Leg2Seg4.mirror = true;
        this.setRotation(this.Leg2Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg2Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg2Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg2Seg5.setRotationPoint(27.0f, 19.0f, -4.0f);
        this.Leg2Seg5.mirror = true;
        this.setRotation(this.Leg2Seg5, 0.0f, 0.0f, 0.669215f);
        this.Leg3Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg3Seg1.addBox(0.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg3Seg1.setRotationPoint(9.5f, 13.0f, 2.0f);
        this.Leg3Seg1.mirror = true;
        this.setRotation(this.Leg3Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg3Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg3Seg2.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg3Seg2.setRotationPoint(12.0f, 13.0f, 2.0f);
        this.Leg3Seg2.mirror = true;
        this.setRotation(this.Leg3Seg2, 0.0f, 0.0f, -0.9294576f);
        this.Leg3Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg3Seg3.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg3Seg3.setRotationPoint(18.0f, 3.0f, 2.0f);
        this.Leg3Seg3.mirror = true;
        this.setRotation(this.Leg3Seg3, 0.0f, 0.0f, 0.6320361f);
        this.Leg3Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg3Seg4.addBox(0.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg3Seg4.setRotationPoint(26.0f, 12.0f, 2.0f);
        this.Leg3Seg4.mirror = true;
        this.setRotation(this.Leg3Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg3Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg3Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg3Seg5.setRotationPoint(27.0f, 19.0f, 2.0f);
        this.Leg3Seg5.mirror = true;
        this.setRotation(this.Leg3Seg5, 0.0f, 0.0f, 0.669215f);
        this.Leg4Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg4Seg1.addBox(0.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg4Seg1.setRotationPoint(9.0f, 13.0f, 8.0f);
        this.Leg4Seg1.mirror = true;
        this.setRotation(this.Leg4Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg4Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg4Seg2.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg4Seg2.setRotationPoint(12.0f, 13.0f, 8.0f);
        this.Leg4Seg2.mirror = true;
        this.setRotation(this.Leg4Seg2, 0.0f, 0.0f, -0.9294576f);
        this.Leg4Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg4Seg3.addBox(0.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg4Seg3.setRotationPoint(18.0f, 3.0f, 8.0f);
        this.Leg4Seg3.mirror = true;
        this.setRotation(this.Leg4Seg3, 0.0f, 0.0f, 0.6320361f);
        this.Leg4Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg4Seg4.addBox(0.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg4Seg4.setRotationPoint(26.0f, 12.0f, 8.0f);
        this.Leg4Seg4.mirror = true;
        this.setRotation(this.Leg4Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg4Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg4Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg4Seg5.setRotationPoint(27.0f, 19.0f, 8.0f);
        this.Leg4Seg5.mirror = true;
        this.setRotation(this.Leg4Seg5, 0.0f, 0.0f, 0.669215f);
        this.Leg5Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg5Seg1.addBox(-4.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg5Seg1.setRotationPoint(-9.0f, 13.0f, -10.0f);
        this.Leg5Seg1.mirror = true;
        this.setRotation(this.Leg5Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg5Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg5Seg2.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg5Seg2.setRotationPoint(-12.0f, 14.0f, -10.0f);
        this.Leg5Seg2.mirror = true;
        this.setRotation(this.Leg5Seg2, 0.0f, 0.0f, 0.9294653f);
        this.Leg5Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg5Seg3.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg5Seg3.setRotationPoint(-18.0f, 4.0f, -10.0f);
        this.Leg5Seg3.mirror = true;
        this.setRotation(this.Leg5Seg3, 0.0f, 0.0f, -0.6320364f);
        this.Leg5Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg5Seg4.addBox(-3.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg5Seg4.setRotationPoint(-26.0f, 12.0f, -10.0f);
        this.Leg5Seg4.mirror = true;
        this.setRotation(this.Leg5Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg5Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg5Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg5Seg5.setRotationPoint(-27.0f, 19.0f, -10.0f);
        this.Leg5Seg5.mirror = true;
        this.setRotation(this.Leg5Seg5, 0.0f, 0.0f, 2.240008f);
        this.Leg6Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg6Seg1.addBox(-4.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg6Seg1.setRotationPoint(-8.5f, 13.0f, -4.0f);
        this.Leg6Seg1.mirror = true;
        this.setRotation(this.Leg6Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg6Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg6Seg2.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg6Seg2.setRotationPoint(-12.0f, 14.0f, -4.0f);
        this.Leg6Seg2.mirror = true;
        this.setRotation(this.Leg6Seg2, 0.0f, 0.0f, 0.9294576f);
        this.Leg6Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg6Seg3.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg6Seg3.setRotationPoint(-18.0f, 4.0f, -4.0f);
        this.Leg6Seg3.mirror = true;
        this.setRotation(this.Leg6Seg3, 0.0f, 0.0f, -0.6320361f);
        this.Leg6Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg6Seg4.addBox(-3.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg6Seg4.setRotationPoint(-26.0f, 12.0f, -4.0f);
        this.Leg6Seg4.mirror = true;
        this.setRotation(this.Leg6Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg6Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg6Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg6Seg5.setRotationPoint(-27.0f, 19.0f, -4.0f);
        this.Leg6Seg5.mirror = true;
        this.setRotation(this.Leg6Seg5, 0.0f, 0.0f, 2.240008f);
        this.Leg7Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg7Seg1.addBox(-4.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg7Seg1.setRotationPoint(-9.5f, 13.0f, 2.0f);
        this.Leg7Seg1.mirror = true;
        this.setRotation(this.Leg7Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg7Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg7Seg2.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg7Seg2.setRotationPoint(-12.0f, 14.0f, 2.0f);
        this.Leg7Seg2.mirror = true;
        this.setRotation(this.Leg7Seg2, 0.0f, 0.0f, 0.9294576f);
        this.Leg7Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg7Seg3.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg7Seg3.setRotationPoint(-18.0f, 4.0f, 2.0f);
        this.Leg7Seg3.mirror = true;
        this.setRotation(this.Leg7Seg3, 0.0f, 0.0f, -0.6320361f);
        this.Leg7Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg7Seg4.addBox(-3.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg7Seg4.setRotationPoint(-26.0f, 12.0f, 2.0f);
        this.Leg7Seg4.mirror = true;
        this.setRotation(this.Leg7Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg7Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg7Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg7Seg5.setRotationPoint(-27.0f, 19.0f, 2.0f);
        this.Leg7Seg5.mirror = true;
        this.setRotation(this.Leg7Seg5, 0.0f, 0.0f, 2.240008f);
        this.Leg8Seg1 = new ModelRenderer(this, 20, 20);
        this.Leg8Seg1.addBox(-4.0f, -1.5f, -2.0f, 4, 3, 4);
        this.Leg8Seg1.setRotationPoint(-9.0f, 13.0f, 8.0f);
        this.Leg8Seg1.mirror = true;
        this.setRotation(this.Leg8Seg1, 0.0f, 0.0f, 0.0f);
        this.Leg8Seg2 = new ModelRenderer(this, 21, 0);
        this.Leg8Seg2.addBox(-12.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg8Seg2.setRotationPoint(-12.0f, 14.0f, 8.0f);
        this.Leg8Seg2.mirror = true;
        this.setRotation(this.Leg8Seg2, 0.0f, 0.0f, 0.9294576f);
        this.Leg8Seg3 = new ModelRenderer(this, 15, 8);
        this.Leg8Seg3.addBox(-13.0f, -1.5f, -1.5f, 13, 3, 3);
        this.Leg8Seg3.setRotationPoint(-18.0f, 4.0f, 8.0f);
        this.Leg8Seg3.mirror = true;
        this.setRotation(this.Leg8Seg3, 0.0f, 0.0f, -0.6320361f);
        this.Leg8Seg4 = new ModelRenderer(this, 0, 14);
        this.Leg8Seg4.addBox(-3.0f, -1.5f, -1.5f, 3, 10, 3);
        this.Leg8Seg4.setRotationPoint(-26.0f, 12.0f, 8.0f);
        this.Leg8Seg4.mirror = true;
        this.setRotation(this.Leg8Seg4, 0.0f, 0.0f, 0.0f);
        this.Leg8Seg5 = new ModelRenderer(this, 0, 0);
        this.Leg8Seg5.addBox(0.0f, -1.5f, -1.5f, 7, 3, 3);
        this.Leg8Seg5.setRotationPoint(-27.0f, 19.0f, 8.0f);
        this.Leg8Seg5.mirror = true;
        this.setRotation(this.Leg8Seg5, 0.0f, 0.0f, 2.240008f);
    }

    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        if (frameEntity == null) return;
        Entity entity=frameEntity;
        float f=frameSwing, f1=frameAmount, f2=frameAge, f3=frameYaw, f4=framePitch, f5=0.0625F;
        matrixStack.push();
this.Head.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
this.Seg1.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg1, 0.0f, 0.0f, 0.0f);
this.Seg2.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg2, 0.0f, 0.0f, 0.0f);
this.Seg3.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg3, 0.0f, 0.0f, 0.0f);
this.Seg4.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg4, 0.0f, 0.0f, 0.0f);
this.Seg5.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg5, 0.0f, 0.0f, 0.0f);
this.Seg6.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg6, 0.0f, 0.0f, 0.0f);
this.Seg7.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg7, 0.0f, 0.0f, 0.0f);
this.Seg8.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Seg8, 0.0f, 0.0f, 0.0f);
this.Tailseg1.setRotationPoint(0.0f, 13.0f, 20.0f);
this.setRotation(this.Tailseg1, 0.5948578f, 0.0f, 0.0f);
this.Tailseg2.setRotationPoint(0.0f, 10.0f, 27.0f);
this.setRotation(this.Tailseg2, 1.07818f, 0.0f, 0.0f);
this.Tailseg3.setRotationPoint(0.0f, 2.0f, 32.0f);
this.setRotation(this.Tailseg3, 1.710216f, 0.0f, 0.0f);
this.Tailseg4.setRotationPoint(0.0f, -7.0f, 31.0f);
this.setRotation(this.Tailseg4, 2.267895f, 0.0f, 0.0f);
this.Tailseg5.setRotationPoint(0.0f, -14.0f, 25.0f);
this.setRotation(this.Tailseg5, 2.899932f, 0.0f, 0.0f);
this.Tailseg6.setRotationPoint(0.0f, -17.0f, 16.0f);
this.setRotation(this.Tailseg6, -2.602503f, 0.0f, 0.0f);
this.Tailseg7.setRotationPoint(0.0f, -12.0f, 8.0f);
this.setRotation(this.Tailseg7, -0.2230717f, 0.0f, 0.0f);
this.Tailseg8.setRotationPoint(0.0f, -12.0f, 8.0f);
this.setRotation(this.Tailseg8, -0.2230717f, 0.0f, 0.0f);
this.Stinger1.setRotationPoint(0.0f, -10.0f, 18.0f);
this.setRotation(this.Stinger1, 0.2230717f, 0.0f, 0.0f);
this.Stinger2.setRotationPoint(0.0f, -10.5f, 20.5f);
this.setRotation(this.Stinger2, -0.2602503f, 0.0f, 0.0f);
this.Stinger3.setRotationPoint(0.0f, -10.0f, 23.0f);
this.setRotation(this.Stinger3, -0.8551081f, 0.0f, 0.0f);
this.LeftShoulder.setRotationPoint(7.0f, 13.0f, -22.0f);
this.setRotation(this.LeftShoulder, 0.0f, -0.8551081f, 0.0f);
this.LeftArmSeg1.setRotationPoint(10.0f, 13.0f, -24.0f);
this.setRotation(this.LeftArmSeg1, 0.0f, -2.044824f, 0.0f);
this.LeftArmSeg2.setRotationPoint(19.0f, 13.0f, -22.0f);
this.setRotation(this.LeftArmSeg2, 0.0f, -0.7435722f, 0.0f);
this.LeftArmSeg3.setRotationPoint(29.0f, 13.0f, -33.0f);
this.setRotation(this.LeftArmSeg3, 0.0f, 0.3717861f, 0.0f);
this.LeftArmSeg4.setRotationPoint(29.0f, 13.0f, -33.0f);
this.setRotation(this.LeftArmSeg4, 0.0f, 1.487144f, 0.0f);
this.RightShoulder.setRotationPoint(-7.0f, 13.0f, -22.0f);
this.setRotation(this.RightShoulder, 0.0f, 0.8551066f, 0.0f);
this.RightArmSeg1.setRotationPoint(-10.0f, 13.0f, -24.0f);
this.setRotation(this.RightArmSeg1, 0.0f, 2.044828f, 0.0f);
this.RightArmSeg2.setRotationPoint(-19.0f, 13.0f, -22.0f);
this.setRotation(this.RightArmSeg2, 0.0f, 0.7435801f, 0.0f);
this.RightArmSeg3.setRotationPoint(-29.0f, 13.0f, -33.0f);
this.setRotation(this.RightArmSeg3, 0.0f, -0.37179f, 0.0f);
this.RightArmSeg4.setRotationPoint(-29.0f, 13.0f, -33.0f);
this.setRotation(this.RightArmSeg4, 0.0f, -1.487143f, 0.0f);
this.RightPincer.setRotationPoint(-17.0f, 13.0f, -33.0f);
this.setRotation(this.RightPincer, 0.0f, -0.0743611f, 0.0f);
this.LeftPincer.setRotationPoint(17.0f, 13.0f, -33.0f);
this.setRotation(this.LeftPincer, 0.0f, 0.0743685f, 0.0f);
this.Lefteye.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Lefteye, 0.0f, 0.0f, 0.2974289f);
this.Righteye.setRotationPoint(0.0f, 13.0f, -8.0f);
this.setRotation(this.Righteye, 0.0f, 0.0f, -0.2974216f);
this.RightMandible.setRotationPoint(-2.0f, 13.0f, -23.0f);
this.setRotation(this.RightMandible, 0.1115358f, 0.3346075f, 0.0f);
this.LeftMandible.setRotationPoint(2.0f, 13.0f, -23.0f);
this.setRotation(this.LeftMandible, 0.111544f, -0.3346145f, 0.0f);
this.RightManPart2.setRotationPoint(-3.0f, 11.0f, -26.0f);
this.setRotation(this.RightManPart2, 1.189716f, 0.0f, 0.0f);
this.LeftManPart2.setRotationPoint(3.0f, 11.0f, -26.0f);
this.setRotation(this.LeftManPart2, 1.188848f, 0.0f, 0.0f);
this.Leg1Seg1.setRotationPoint(9.0f, 13.0f, -10.0f);
this.setRotation(this.Leg1Seg1, 0.0f, 0.0f, 0.0f);
this.Leg1Seg2.setRotationPoint(12.0f, 13.0f, -10.0f);
this.setRotation(this.Leg1Seg2, 0.0f, 0.0f, -0.9294576f);
this.Leg1Seg3.setRotationPoint(18.0f, 3.0f, -10.0f);
this.setRotation(this.Leg1Seg3, 0.0f, 0.0f, 0.6320361f);
this.Leg1Seg4.setRotationPoint(26.0f, 12.0f, -10.0f);
this.setRotation(this.Leg1Seg4, 0.0f, 0.0f, 0.0f);
this.Leg1Seg5.setRotationPoint(27.0f, 19.0f, -10.0f);
this.setRotation(this.Leg1Seg5, 0.0f, 0.0f, 0.669215f);
this.Leg2Seg1.setRotationPoint(8.5f, 13.0f, -4.0f);
this.setRotation(this.Leg2Seg1, 0.0f, 0.0f, 0.0f);
this.Leg2Seg2.setRotationPoint(12.0f, 13.0f, -4.0f);
this.setRotation(this.Leg2Seg2, 0.0f, 0.0f, -0.9294576f);
this.Leg2Seg3.setRotationPoint(18.0f, 3.0f, -4.0f);
this.setRotation(this.Leg2Seg3, 0.0f, 0.0f, 0.6320361f);
this.Leg2Seg4.setRotationPoint(26.0f, 12.0f, -4.0f);
this.setRotation(this.Leg2Seg4, 0.0f, 0.0f, 0.0f);
this.Leg2Seg5.setRotationPoint(27.0f, 19.0f, -4.0f);
this.setRotation(this.Leg2Seg5, 0.0f, 0.0f, 0.669215f);
this.Leg3Seg1.setRotationPoint(9.5f, 13.0f, 2.0f);
this.setRotation(this.Leg3Seg1, 0.0f, 0.0f, 0.0f);
this.Leg3Seg2.setRotationPoint(12.0f, 13.0f, 2.0f);
this.setRotation(this.Leg3Seg2, 0.0f, 0.0f, -0.9294576f);
this.Leg3Seg3.setRotationPoint(18.0f, 3.0f, 2.0f);
this.setRotation(this.Leg3Seg3, 0.0f, 0.0f, 0.6320361f);
this.Leg3Seg4.setRotationPoint(26.0f, 12.0f, 2.0f);
this.setRotation(this.Leg3Seg4, 0.0f, 0.0f, 0.0f);
this.Leg3Seg5.setRotationPoint(27.0f, 19.0f, 2.0f);
this.setRotation(this.Leg3Seg5, 0.0f, 0.0f, 0.669215f);
this.Leg4Seg1.setRotationPoint(9.0f, 13.0f, 8.0f);
this.setRotation(this.Leg4Seg1, 0.0f, 0.0f, 0.0f);
this.Leg4Seg2.setRotationPoint(12.0f, 13.0f, 8.0f);
this.setRotation(this.Leg4Seg2, 0.0f, 0.0f, -0.9294576f);
this.Leg4Seg3.setRotationPoint(18.0f, 3.0f, 8.0f);
this.setRotation(this.Leg4Seg3, 0.0f, 0.0f, 0.6320361f);
this.Leg4Seg4.setRotationPoint(26.0f, 12.0f, 8.0f);
this.setRotation(this.Leg4Seg4, 0.0f, 0.0f, 0.0f);
this.Leg4Seg5.setRotationPoint(27.0f, 19.0f, 8.0f);
this.setRotation(this.Leg4Seg5, 0.0f, 0.0f, 0.669215f);
this.Leg5Seg1.setRotationPoint(-9.0f, 13.0f, -10.0f);
this.setRotation(this.Leg5Seg1, 0.0f, 0.0f, 0.0f);
this.Leg5Seg2.setRotationPoint(-12.0f, 14.0f, -10.0f);
this.setRotation(this.Leg5Seg2, 0.0f, 0.0f, 0.9294653f);
this.Leg5Seg3.setRotationPoint(-18.0f, 4.0f, -10.0f);
this.setRotation(this.Leg5Seg3, 0.0f, 0.0f, -0.6320364f);
this.Leg5Seg4.setRotationPoint(-26.0f, 12.0f, -10.0f);
this.setRotation(this.Leg5Seg4, 0.0f, 0.0f, 0.0f);
this.Leg5Seg5.setRotationPoint(-27.0f, 19.0f, -10.0f);
this.setRotation(this.Leg5Seg5, 0.0f, 0.0f, 2.240008f);
this.Leg6Seg1.setRotationPoint(-8.5f, 13.0f, -4.0f);
this.setRotation(this.Leg6Seg1, 0.0f, 0.0f, 0.0f);
this.Leg6Seg2.setRotationPoint(-12.0f, 14.0f, -4.0f);
this.setRotation(this.Leg6Seg2, 0.0f, 0.0f, 0.9294576f);
this.Leg6Seg3.setRotationPoint(-18.0f, 4.0f, -4.0f);
this.setRotation(this.Leg6Seg3, 0.0f, 0.0f, -0.6320361f);
this.Leg6Seg4.setRotationPoint(-26.0f, 12.0f, -4.0f);
this.setRotation(this.Leg6Seg4, 0.0f, 0.0f, 0.0f);
this.Leg6Seg5.setRotationPoint(-27.0f, 19.0f, -4.0f);
this.setRotation(this.Leg6Seg5, 0.0f, 0.0f, 2.240008f);
this.Leg7Seg1.setRotationPoint(-9.5f, 13.0f, 2.0f);
this.setRotation(this.Leg7Seg1, 0.0f, 0.0f, 0.0f);
this.Leg7Seg2.setRotationPoint(-12.0f, 14.0f, 2.0f);
this.setRotation(this.Leg7Seg2, 0.0f, 0.0f, 0.9294576f);
this.Leg7Seg3.setRotationPoint(-18.0f, 4.0f, 2.0f);
this.setRotation(this.Leg7Seg3, 0.0f, 0.0f, -0.6320361f);
this.Leg7Seg4.setRotationPoint(-26.0f, 12.0f, 2.0f);
this.setRotation(this.Leg7Seg4, 0.0f, 0.0f, 0.0f);
this.Leg7Seg5.setRotationPoint(-27.0f, 19.0f, 2.0f);
this.setRotation(this.Leg7Seg5, 0.0f, 0.0f, 2.240008f);
this.Leg8Seg1.setRotationPoint(-9.0f, 13.0f, 8.0f);
this.setRotation(this.Leg8Seg1, 0.0f, 0.0f, 0.0f);
this.Leg8Seg2.setRotationPoint(-12.0f, 14.0f, 8.0f);
this.setRotation(this.Leg8Seg2, 0.0f, 0.0f, 0.9294576f);
this.Leg8Seg3.setRotationPoint(-18.0f, 4.0f, 8.0f);
this.setRotation(this.Leg8Seg3, 0.0f, 0.0f, -0.6320361f);
this.Leg8Seg4.setRotationPoint(-26.0f, 12.0f, 8.0f);
this.setRotation(this.Leg8Seg4, 0.0f, 0.0f, 0.0f);
this.Leg8Seg5.setRotationPoint(-27.0f, 19.0f, 8.0f);
this.setRotation(this.Leg8Seg5, 0.0f, 0.0f, 2.240008f);

        EmperorScorpionEntity.CustomEntity e = (EmperorScorpionEntity.CustomEntity)entity;
        RenderInfo r = null;
        this.legacyAngles(f, f1, f2, f3, f4, f5, entity);
        float newangle = 0.0f;
        float upangle = 0.0f;
        float nextangle = 0.0f;
        float pi4 = 1.570795f;
        newangle = MathHelper.cos((float)(f2 * 2.0f * this.wingspeed)) * (float)Math.PI * 0.12f * f1;
        nextangle = MathHelper.cos((float)((f2 + 0.1f) * 2.0f * this.wingspeed)) * (float)Math.PI * 0.12f * f1;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = 0.47f * f1 - Math.abs(newangle);
        }
        this.doLeftLeg(this.Leg1Seg1, this.Leg1Seg2, this.Leg1Seg3, this.Leg1Seg4, this.Leg1Seg5, newangle, upangle);
        this.doRightLeg(this.Leg5Seg1, this.Leg5Seg2, this.Leg5Seg3, this.Leg5Seg4, this.Leg5Seg5, -newangle, upangle);
        newangle = MathHelper.cos((float)(f2 * 2.0f * this.wingspeed - 1.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        nextangle = MathHelper.cos((float)((f2 + 0.1f) * 2.0f * this.wingspeed - 1.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = 0.47f * f1 - Math.abs(newangle);
        }
        this.doLeftLeg(this.Leg2Seg1, this.Leg2Seg2, this.Leg2Seg3, this.Leg2Seg4, this.Leg2Seg5, newangle, upangle);
        this.doRightLeg(this.Leg6Seg1, this.Leg6Seg2, this.Leg6Seg3, this.Leg6Seg4, this.Leg6Seg5, -newangle, upangle);
        newangle = MathHelper.cos((float)(f2 * 2.0f * this.wingspeed - 2.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        nextangle = MathHelper.cos((float)((f2 + 0.1f) * 2.0f * this.wingspeed - 2.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = 0.47f * f1 - Math.abs(newangle);
        }
        this.doLeftLeg(this.Leg3Seg1, this.Leg3Seg2, this.Leg3Seg3, this.Leg3Seg4, this.Leg3Seg5, newangle, upangle);
        this.doRightLeg(this.Leg7Seg1, this.Leg7Seg2, this.Leg7Seg3, this.Leg7Seg4, this.Leg7Seg5, -newangle, upangle);
        newangle = MathHelper.cos((float)(f2 * 2.0f * this.wingspeed - 3.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        nextangle = MathHelper.cos((float)((f2 + 0.1f) * 2.0f * this.wingspeed - 3.0f * pi4)) * (float)Math.PI * 0.12f * f1;
        upangle = 0.0f;
        if (nextangle > newangle) {
            upangle = 0.47f * f1 - Math.abs(newangle);
        }
        this.doLeftLeg(this.Leg4Seg1, this.Leg4Seg2, this.Leg4Seg3, this.Leg4Seg4, this.Leg4Seg5, newangle, upangle);
        this.doRightLeg(this.Leg8Seg1, this.Leg8Seg2, this.Leg8Seg3, this.Leg8Seg4, this.Leg8Seg5, -newangle, upangle);
        newangle = e.getAttacking() == 0 ? MathHelper.cos((float)(f2 * 0.5f * this.wingspeed)) * (float)Math.PI * 0.05f : MathHelper.cos((float)(f2 * 2.5f * this.wingspeed)) * (float)Math.PI * 0.15f;
        this.LeftManPart2.rotateAngleZ = newangle;
        this.RightManPart2.rotateAngleZ = -newangle;
        r = e.getRenderInfo();
        newangle = MathHelper.cos((float)(f2 * 3.0f * this.wingspeed)) * (float)Math.PI * 0.15f;
        nextangle = MathHelper.cos((float)((f2 + 0.1f) * 3.0f * this.wingspeed)) * (float)Math.PI * 0.15f;
        if (nextangle > 0.0f && newangle < 0.0f) {
            r.ri1 = 0;
            if (e.getAttacking() == 0) {
                r.ri1 = e.getModelRandom().nextInt(20);
                r.ri2 = e.getModelRandom().nextInt(25);
            } else {
                r.ri1 = e.getModelRandom().nextInt(4);
                r.ri2 = e.getModelRandom().nextInt(3);
            }
        }
        if (r.ri1 == 1 || r.ri1 == 3) {
            this.doLeftClaw(newangle);
        } else {
            this.doLeftClaw(0.0f);
        }
        if (r.ri1 == 2 || r.ri1 == 3) {
            this.doRightClaw(newangle);
        } else {
            this.doRightClaw(0.0f);
        }
        if (r.ri2 == 1) {
            this.doTail(newangle);
        } else {
            this.doTail(0.0f);
        }
        e.setRenderInfo(r);
        this.Head.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Seg8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tailseg8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Stinger1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Stinger2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Stinger3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftShoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftArmSeg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightShoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightArmSeg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightPincer.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftPincer.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lefteye.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Righteye.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightMandible.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftMandible.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RightManPart2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LeftManPart2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg1Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg1Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg1Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg1Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg1Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg2Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg2Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg2Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg2Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg2Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg3Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg3Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg3Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg3Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg3Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg4Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg4Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg4Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg4Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg4Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg5Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg5Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg5Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg5Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg5Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg6Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg6Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg6Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg6Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg6Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg7Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg7Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg7Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg7Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg7Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg8Seg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg8Seg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg8Seg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg8Seg4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Leg8Seg5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    
        matrixStack.pop();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void legacyAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
    }

    private void doLeftLeg(ModelRenderer seg1, ModelRenderer seg2, ModelRenderer seg3, ModelRenderer seg4, ModelRenderer seg5, float angle, float upangle) {
        seg2.rotateAngleY = angle;
        seg3.rotateAngleY = angle;
        seg4.rotateAngleY = angle;
        seg5.rotateAngleY = angle;
        seg3.rotationPointZ = (float)((double)seg2.rotationPointZ - Math.sin(angle) * 6.0);
        seg3.rotationPointX = (float)((double)seg2.rotationPointX - Math.abs(Math.sin(angle) * 6.0) + 6.0);
        seg4.rotationPointZ = (float)((double)seg3.rotationPointZ - Math.sin(angle) * 9.0);
        seg4.rotationPointX = (float)((double)seg3.rotationPointX - Math.abs(Math.sin(angle) * 9.0) + 9.0);
        seg5.rotationPointZ = (float)((double)seg4.rotationPointZ - Math.sin(angle) * 1.0);
        seg5.rotationPointX = (float)((double)seg4.rotationPointX - Math.abs(Math.sin(angle) * 1.0) + 1.0);
        seg2.rotateAngleZ = -upangle - 0.929f;
        seg3.rotateAngleZ = -upangle + 0.632f;
        seg3.rotationPointY = seg2.rotationPointY + (float)(11.5 * Math.sin(seg2.rotateAngleZ));
        seg4.rotationPointY = seg3.rotationPointY + (float)(11.5 * Math.sin(seg3.rotateAngleZ));
        seg5.rotationPointY = seg4.rotationPointY + 6.5f;
    }

    private void doRightLeg(ModelRenderer seg1, ModelRenderer seg2, ModelRenderer seg3, ModelRenderer seg4, ModelRenderer seg5, float angle, float upangle) {
        seg2.rotateAngleY = angle;
        seg3.rotateAngleY = angle;
        seg4.rotateAngleY = angle;
        seg5.rotateAngleY = -angle;
        seg3.rotationPointZ = (float)((double)seg2.rotationPointZ + Math.sin(angle) * 6.0);
        seg3.rotationPointX = (float)((double)seg2.rotationPointX + Math.abs(Math.sin(angle) * 6.0) - 6.0);
        seg4.rotationPointZ = (float)((double)seg3.rotationPointZ + Math.sin(angle) * 9.0);
        seg4.rotationPointX = (float)((double)seg3.rotationPointX + Math.abs(Math.sin(angle) * 9.0) - 9.0);
        seg5.rotationPointZ = (float)((double)seg4.rotationPointZ + Math.sin(angle) * 1.0);
        seg5.rotationPointX = (float)((double)seg4.rotationPointX + Math.abs(Math.sin(angle) * 1.0) - 1.0);
        seg2.rotateAngleZ = upangle + 0.929f;
        seg3.rotateAngleZ = upangle - 0.632f;
        seg3.rotationPointY = seg2.rotationPointY - (float)(11.5 * Math.sin(seg2.rotateAngleZ));
        seg4.rotationPointY = seg3.rotationPointY - (float)(11.5 * Math.sin(seg3.rotateAngleZ));
        seg5.rotationPointY = seg4.rotationPointY + 6.5f;
    }

    private void doLeftClaw(float angle) {
        this.LeftArmSeg1.rotateAngleY = -1.57f + angle;
        this.LeftArmSeg2.rotationPointZ = (float)(-22.0 - Math.cos(this.LeftArmSeg1.rotateAngleY) * 12.0);
        this.LeftArmSeg3.rotationPointZ = this.LeftArmSeg2.rotationPointZ - 11.0f;
        this.LeftArmSeg4.rotationPointZ = this.LeftArmSeg2.rotationPointZ - 11.0f;
        this.LeftPincer.rotationPointZ = this.LeftArmSeg2.rotationPointZ - 11.0f;
        this.LeftArmSeg3.rotateAngleY = 0.074f + angle;
        this.LeftPincer.rotateAngleY = 0.371f - angle;
    }

    private void doRightClaw(float angle) {
        this.RightArmSeg1.rotateAngleY = 1.57f - angle;
        this.RightArmSeg2.rotationPointZ = (float)(-22.0 - Math.cos(this.RightArmSeg1.rotateAngleY) * 12.0);
        this.RightArmSeg3.rotationPointZ = this.RightArmSeg2.rotationPointZ - 11.0f;
        this.RightArmSeg4.rotationPointZ = this.RightArmSeg2.rotationPointZ - 11.0f;
        this.RightPincer.rotationPointZ = this.RightArmSeg2.rotationPointZ - 11.0f;
        this.RightArmSeg3.rotateAngleY = -0.074f - angle;
        this.RightPincer.rotateAngleY = -0.371f + angle;
    }

    private void doTail(float angle) {
        this.Tailseg1.rotateAngleX = 0.594f + angle;
        this.Tailseg2.rotateAngleX = this.Tailseg1.rotateAngleX + 0.48399997f + angle;
        this.Tailseg2.rotationPointY = (float)((double)this.Tailseg1.rotationPointY - Math.sin(this.Tailseg1.rotateAngleX) * 9.0);
        this.Tailseg2.rotationPointZ = (float)((double)this.Tailseg1.rotationPointZ + Math.cos(this.Tailseg1.rotateAngleX) * 9.0);
        this.Tailseg3.rotateAngleX = this.Tailseg2.rotateAngleX + 0.6320001f + angle;
        this.Tailseg3.rotationPointY = (float)((double)this.Tailseg2.rotationPointY - Math.sin(this.Tailseg2.rotateAngleX) * 10.0);
        this.Tailseg3.rotationPointZ = (float)((double)this.Tailseg2.rotationPointZ + Math.cos(this.Tailseg2.rotateAngleX) * 10.0);
        this.Tailseg4.rotateAngleX = this.Tailseg3.rotateAngleX + 0.5569999f - angle;
        this.Tailseg4.rotationPointY = (float)((double)this.Tailseg3.rotationPointY - Math.sin(this.Tailseg3.rotateAngleX) * 10.0);
        this.Tailseg4.rotationPointZ = (float)((double)this.Tailseg3.rotationPointZ + Math.cos(this.Tailseg3.rotateAngleX) * 10.0);
        this.Tailseg5.rotateAngleX = this.Tailseg4.rotateAngleX + 0.63199997f - angle;
        this.Tailseg5.rotationPointY = (float)((double)this.Tailseg4.rotationPointY - Math.sin(this.Tailseg4.rotateAngleX) * 10.0);
        this.Tailseg5.rotationPointZ = (float)((double)this.Tailseg4.rotationPointZ + Math.cos(this.Tailseg4.rotateAngleX) * 10.0);
        this.Tailseg6.rotateAngleX = this.Tailseg5.rotateAngleX + -5.501f - angle * 3.0f / 2.0f - 0.4f;
        this.Tailseg6.rotationPointY = (float)((double)this.Tailseg5.rotationPointY - Math.sin(this.Tailseg5.rotateAngleX) * 10.0);
        this.Tailseg6.rotationPointZ = (float)((double)this.Tailseg5.rotationPointZ + Math.cos(this.Tailseg5.rotateAngleX) * 10.0);
        this.Tailseg7.rotateAngleX = this.Tailseg6.rotateAngleX + -2.822f - angle * 2.5f - 2.2f;
        this.Tailseg7.rotationPointY = (float)((double)this.Tailseg6.rotationPointY - Math.sin(this.Tailseg6.rotateAngleX) * 10.0);
        this.Tailseg7.rotationPointZ = (float)((double)this.Tailseg6.rotationPointZ + Math.cos(this.Tailseg6.rotateAngleX) * 10.0);
        this.Tailseg8.rotateAngleX = this.Tailseg7.rotateAngleX;
        this.Tailseg8.rotationPointY = this.Tailseg7.rotationPointY;
        this.Tailseg8.rotationPointZ = this.Tailseg7.rotationPointZ;
        this.Stinger1.rotateAngleX = this.Tailseg7.rotateAngleX + 0.0f + angle * 0.66f;
        this.Stinger1.rotationPointY = (float)((double)this.Tailseg7.rotationPointY - Math.sin(this.Tailseg7.rotateAngleX) * 10.0);
        this.Stinger1.rotationPointZ = (float)((double)this.Tailseg7.rotationPointZ + Math.cos(this.Tailseg7.rotateAngleX) * 10.0);
        this.Stinger2.rotateAngleX = this.Stinger1.rotateAngleX + -0.48f + angle;
        this.Stinger2.rotationPointY = (float)((double)this.Stinger1.rotationPointY - Math.sin(this.Stinger1.rotateAngleX) * 3.0);
        this.Stinger2.rotationPointZ = (float)((double)this.Stinger1.rotationPointZ + Math.cos(this.Stinger1.rotateAngleX) * 3.0);
        this.Stinger3.rotateAngleX = this.Stinger2.rotateAngleX + -1.01f + angle * 1.7f;
        this.Stinger3.rotationPointY = (float)((double)this.Stinger2.rotationPointY - Math.sin(this.Stinger2.rotateAngleX) * 3.0);
        this.Stinger3.rotationPointZ = (float)((double)this.Stinger2.rotationPointZ + Math.cos(this.Stinger2.rotateAngleX) * 3.0);
    }
}


}
