package net.mcreator.xillysorespawn.entity.renderer;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.mcreator.xillysorespawn.entity.GodzillaEntity;
import net.mcreator.xillysorespawn.entity.OreSpawnLogic;

@OnlyIn(Dist.CLIENT)
public class GodzillaRenderer {
    private static final String TEXTURE = "xillys_orespawn:textures/entities/godzillatexture.png";
    public static class ModelRegisterHandler {
        @SubscribeEvent @OnlyIn(Dist.CLIENT)
        public void registerModels(ModelRegistryEvent event) {
            RenderingRegistry.registerEntityRenderingHandler(GodzillaEntity.entity, manager ->
                new MobRenderer(manager, new ModelGodzilla(0.2F), 2.0F) {
                    @Override public ResourceLocation getEntityTexture(Entity entity) { return new ResourceLocation(TEXTURE); }
                    @Override protected void preRenderCallback(LivingEntity entity, MatrixStack stack, float partialTick) {
                        float modelScale = 2.0F;
                        if (OreSpawnLogic.playNicely != 0) modelScale /= 4.0F;
                        stack.scale(modelScale, modelScale, modelScale);
                    }
                });
        }
    }

public static class ModelGodzilla extends EntityModel<Entity> {
    // Exact legacy render order recovered from bytecode; do not add a second addChild rig.
    private Entity frameEntity;
    private float frameSwing, frameAmount, frameAge, frameYaw, framePitch;
    @Override public void setRotationAngles(Entity entity, float swing, float amount, float age, float yaw, float pitch) {
        frameEntity=entity; frameSwing=swing; frameAmount=amount; frameAge=age; frameYaw=yaw; framePitch=pitch;
    }

    private float wingspeed = 1.0f;
    private final ModelRenderer LToe1;
    private final ModelRenderer LToe3;
    private final ModelRenderer LToe2;
    private final ModelRenderer LToe9;
    private final ModelRenderer LToe8;
    private final ModelRenderer LToe7;
    private final ModelRenderer LToe6;
    private final ModelRenderer LToe5;
    private final ModelRenderer LToe4;
    private final ModelRenderer RToe9;
    private final ModelRenderer RToe6;
    private final ModelRenderer RToe5;
    private final ModelRenderer RToe2;
    private final ModelRenderer RToe1;
    private final ModelRenderer RToe4;
    private final ModelRenderer RToe7;
    private final ModelRenderer RToe8;
    private final ModelRenderer RToe3;
    private final ModelRenderer LThigh;
    private final ModelRenderer LLowerLeg;
    private final ModelRenderer LUpperLeg;
    private final ModelRenderer TailTip;
    private final ModelRenderer RLegLower;
    private final ModelRenderer RLegUpper;
    private final ModelRenderer RThigh;
    private final ModelRenderer LowerJaw;
    private final ModelRenderer TailBase;
    private final ModelRenderer Tail2;
    private final ModelRenderer Tail3;
    private final ModelRenderer Tail4;
    private final ModelRenderer Tail5;
    private final ModelRenderer Tail6;
    private final ModelRenderer Tail7;
    private final ModelRenderer BodyBottom;
    private final ModelRenderer RLowerArm;
    private final ModelRenderer BodyCenter;
    private final ModelRenderer Neck;
    private final ModelRenderer TopJaw;
    private final ModelRenderer Head;
    private final ModelRenderer BodyTop;
    private final ModelRenderer RShoulder;
    private final ModelRenderer RThumbTip;
    private final ModelRenderer RUpperArm;
    private final ModelRenderer RHand;
    private final ModelRenderer RThumbBase;
    private final ModelRenderer R3rdFingerTip;
    private final ModelRenderer R3rdFingerBase;
    private final ModelRenderer RIndexTip;
    private final ModelRenderer RIndexBase;
    private final ModelRenderer LShoulder;
    private final ModelRenderer LUpperArm;
    private final ModelRenderer LLowerArm;
    private final ModelRenderer LIndexBase;
    private final ModelRenderer LIndexTip;
    private final ModelRenderer LHand;
    private final ModelRenderer LThumbBase;
    private final ModelRenderer LThumbTip;
    private final ModelRenderer L3rdFingerTip;
    private final ModelRenderer L3rdFingerBase;
    private final ModelRenderer Lspikes1;
    private final ModelRenderer Rspikes1;
    private final ModelRenderer Lspike2;
    private final ModelRenderer Rspike2;
    private final ModelRenderer Lspike3;
    private final ModelRenderer Rspike3;
    private final ModelRenderer Lspike4;
    private final ModelRenderer Rspike4;
    private final ModelRenderer Lspike5;
    private final ModelRenderer Rspike5;
    private final ModelRenderer Spike6;
    private final ModelRenderer Spikes7;

    public ModelGodzilla(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 1024;
        this.textureHeight = 1024;
        this.LToe1 = new ModelRenderer(this, 45, 1002);
        this.LToe1.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe1.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe1.mirror = true;
        this.setRotation(this.LToe1, 0.0f, 0.7853982f, 0.0f);
        this.LToe3 = new ModelRenderer(this, 0, 955);
        this.LToe3.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.LToe3.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe3.mirror = true;
        this.setRotation(this.LToe3, 0.0f, 0.7853982f, 0.0f);
        this.LToe2 = new ModelRenderer(this, 0, 1002);
        this.LToe2.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe2.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe2.mirror = true;
        this.setRotation(this.LToe2, 0.0f, 0.7853982f, 0.0f);
        this.LToe9 = new ModelRenderer(this, 0, 955);
        this.LToe9.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.LToe9.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe9.mirror = true;
        this.setRotation(this.LToe9, 0.0f, -0.7853982f, 0.0f);
        this.LToe8 = new ModelRenderer(this, 0, 1002);
        this.LToe8.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe8.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe8.mirror = true;
        this.setRotation(this.LToe8, 0.0f, -0.7853982f, 0.0f);
        this.LToe7 = new ModelRenderer(this, 45, 1002);
        this.LToe7.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe7.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe7.mirror = true;
        this.setRotation(this.LToe7, 0.0f, -0.7853982f, 0.0f);
        this.LToe6 = new ModelRenderer(this, 92, 955);
        this.LToe6.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 36);
        this.LToe6.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe6.mirror = true;
        this.setRotation(this.LToe6, 0.0f, 0.0f, 0.0f);
        this.LToe5 = new ModelRenderer(this, 0, 1002);
        this.LToe5.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.LToe5.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe5.mirror = true;
        this.setRotation(this.LToe5, 0.0f, 0.0f, 0.0f);
        this.LToe4 = new ModelRenderer(this, 45, 1002);
        this.LToe4.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.LToe4.setRotationPoint(54.0f, 16.0f, 6.0f);
        this.LToe4.mirror = true;
        this.setRotation(this.LToe4, 0.0f, 0.0f, 0.0f);
        this.RToe9 = new ModelRenderer(this, 0, 955);
        this.RToe9.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.RToe9.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe9.mirror = true;
        this.setRotation(this.RToe9, 0.0f, 0.7853982f, 0.0f);
        this.RToe6 = new ModelRenderer(this, 92, 955);
        this.RToe6.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 36);
        this.RToe6.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe6.mirror = true;
        this.setRotation(this.RToe6, 0.0f, 0.0f, 0.0f);
        this.RToe5 = new ModelRenderer(this, 0, 1002);
        this.RToe5.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe5.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe5.mirror = true;
        this.setRotation(this.RToe5, 0.0f, 0.0f, 0.0f);
        this.RToe2 = new ModelRenderer(this, 0, 1002);
        this.RToe2.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe2.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe2.mirror = true;
        this.setRotation(this.RToe2, 0.0f, -0.7853982f, 0.0f);
        this.RToe1 = new ModelRenderer(this, 45, 1002);
        this.RToe1.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe1.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe1.mirror = true;
        this.setRotation(this.RToe1, 0.0f, -0.7853982f, 0.0f);
        this.RToe4 = new ModelRenderer(this, 45, 1002);
        this.RToe4.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe4.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe4.mirror = true;
        this.setRotation(this.RToe4, 0.0f, 0.0f, 0.0f);
        this.RToe7 = new ModelRenderer(this, 45, 1002);
        this.RToe7.addBox(-5.0f, -2.0f, -40.0f, 10, 10, 6);
        this.RToe7.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe7.mirror = true;
        this.setRotation(this.RToe7, 0.0f, 0.7853982f, 0.0f);
        this.RToe8 = new ModelRenderer(this, 0, 1002);
        this.RToe8.addBox(-7.0f, -6.0f, -34.0f, 14, 14, 8);
        this.RToe8.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe8.mirror = true;
        this.setRotation(this.RToe8, 0.0f, 0.7853982f, 0.0f);
        this.RToe3 = new ModelRenderer(this, 0, 955);
        this.RToe3.addBox(-8.0f, -8.0f, -26.0f, 16, 16, 30);
        this.RToe3.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RToe3.mirror = true;
        this.setRotation(this.RToe3, 0.0f, -0.7853982f, 0.0f);
        this.LThigh = new ModelRenderer(this, 192, 350);
        this.LThigh.addBox(0.0f, -14.0f, -21.0f, 28, 28, 42);
        this.LThigh.setRotationPoint(40.0f, -91.0f, 2.0f);
        this.LThigh.mirror = true;
        this.setRotation(this.LThigh, -0.5585054f, 0.0f, 0.0f);
        this.LLowerLeg = new ModelRenderer(this, 202, 556);
        this.LLowerLeg.addBox(-15.0f, -62.0f, -15.0f, 30, 62, 30);
        this.LLowerLeg.setRotationPoint(54.0f, 14.0f, 6.0f);
        this.LLowerLeg.mirror = true;
        this.setRotation(this.LLowerLeg, 0.1745329f, -0.1308997f, 0.0f);
        this.LUpperLeg = new ModelRenderer(this, 152, 420);
        this.LUpperLeg.addBox(-16.0f, -52.0f, -16.0f, 32, 52, 32);
        this.LUpperLeg.setRotationPoint(56.0f, -36.0f, -5.0f);
        this.LUpperLeg.mirror = true;
        this.setRotation(this.LUpperLeg, -0.1745329f, -0.3926991f, -0.0872665f);
        this.TailTip = new ModelRenderer(this, 0, 694);
        this.TailTip.addBox(-6.0f, 0.0f, -5.0f, 12, 21, 10);
        this.TailTip.setRotationPoint(0.0f, 18.0f, 203.0f);
        this.TailTip.mirror = true;
        this.setRotation(this.TailTip, 1.53589f, 0.0f, 0.0f);
        this.RLegLower = new ModelRenderer(this, 200, 646);
        this.RLegLower.addBox(-15.0f, -62.0f, -15.0f, 30, 62, 30);
        this.RLegLower.setRotationPoint(-54.0f, 16.0f, 6.0f);
        this.RLegLower.mirror = true;
        this.setRotation(this.RLegLower, 0.1745329f, 0.1308997f, 0.0f);
        this.RLegUpper = new ModelRenderer(this, 152, 420);
        this.RLegUpper.addBox(-16.0f, -52.0f, -16.0f, 32, 52, 32);
        this.RLegUpper.setRotationPoint(-56.0f, -36.0f, -5.0f);
        this.RLegUpper.mirror = true;
        this.setRotation(this.RLegUpper, -0.1745329f, 0.3926991f, 0.0872665f);
        this.RThigh = new ModelRenderer(this, 192, 350);
        this.RThigh.addBox(-28.0f, -14.0f, -21.0f, 28, 28, 42);
        this.RThigh.setRotationPoint(-40.0f, -91.0f, 2.0f);
        this.RThigh.mirror = true;
        this.setRotation(this.RThigh, -0.5585054f, 0.0f, 0.0f);
        this.LowerJaw = new ModelRenderer(this, 272, 0);
        this.LowerJaw.addBox(-13.0f, -5.0f, -50.0f, 26, 11, 50);
        this.LowerJaw.setRotationPoint(0.0f, -142.0f, -109.0f);
        this.LowerJaw.mirror = true;
        this.setRotation(this.LowerJaw, 0.5235988f, 0.0f, 0.0f);
        this.TailBase = new ModelRenderer(this, 0, 240);
        this.TailBase.addBox(-32.0f, 0.0f, -29.0f, 64, 40, 58);
        this.TailBase.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.TailBase.mirror = true;
        this.setRotation(this.TailBase, 0.7853982f, 0.0f, 0.0f);
        this.Tail2 = new ModelRenderer(this, 0, 338);
        this.Tail2.addBox(-25.0f, 0.0f, -23.0f, 50, 36, 46);
        this.Tail2.setRotationPoint(0.0f, -48.0f, 48.0f);
        this.Tail2.mirror = true;
        this.setRotation(this.Tail2, 0.6981317f, 0.0f, 0.0f);
        this.Tail3 = new ModelRenderer(this, 0, 420);
        this.Tail3.addBox(-20.0f, 0.0f, -18.0f, 40, 36, 36);
        this.Tail3.setRotationPoint(0.0f, -24.0f, 66.0f);
        this.Tail3.mirror = true;
        this.setRotation(this.Tail3, 0.8726646f, 0.0f, 0.0f);
        this.Tail4 = new ModelRenderer(this, 0, 492);
        this.Tail4.addBox(-16.0f, 0.0f, -14.0f, 32, 42, 28);
        this.Tail4.setRotationPoint(0.0f, -3.0f, 87.0f);
        this.Tail4.mirror = true;
        this.setRotation(this.Tail4, 1.134464f, 0.0f, 0.0f);
        this.Tail5 = new ModelRenderer(this, 0, 556);
        this.Tail5.addBox(-13.0f, 0.0f, -11.0f, 26, 42, 22);
        this.Tail5.setRotationPoint(0.0f, 12.0f, 116.0f);
        this.Tail5.mirror = true;
        this.setRotation(this.Tail5, 1.53589f, 0.0f, 0.0f);
        this.Tail6 = new ModelRenderer(this, 0, 614);
        this.Tail6.addBox(-10.0f, 0.0f, -9.0f, 20, 32, 18);
        this.Tail6.setRotationPoint(0.0f, 14.0f, 154.0f);
        this.Tail6.mirror = true;
        this.setRotation(this.Tail6, 1.53589f, 0.0f, 0.0f);
        this.Tail7 = new ModelRenderer(this, 0, 658);
        this.Tail7.addBox(-8.0f, 0.0f, -7.0f, 16, 22, 14);
        this.Tail7.setRotationPoint(0.0f, 16.0f, 185.0f);
        this.Tail7.mirror = true;
        this.setRotation(this.Tail7, 1.53589f, 0.0f, 0.0f);
        this.BodyBottom = new ModelRenderer(this, 0, 104);
        this.BodyBottom.addBox(-40.0f, 0.0f, -36.0f, 80, 64, 72);
        this.BodyBottom.setRotationPoint(0.0f, -112.0f, -20.0f);
        this.BodyBottom.mirror = true;
        this.setRotation(this.BodyBottom, 0.8726646f, 0.0f, 0.0f);
        this.RLowerArm = new ModelRenderer(this, 245, 240);
        this.RLowerArm.addBox(-48.0f, -11.0f, -11.0f, 48, 22, 22);
        this.RLowerArm.setRotationPoint(-80.0f, -115.0f, -61.0f);
        this.RLowerArm.mirror = true;
        this.setRotation(this.RLowerArm, 0.0f, -0.7853982f, -0.2617994f);
        this.BodyCenter = new ModelRenderer(this, 0, 0);
        this.BodyCenter.addBox(-36.0f, -32.0f, -32.0f, 72, 40, 64);
        this.BodyCenter.setRotationPoint(0.0f, -112.0f, -20.0f);
        this.BodyCenter.mirror = true;
        this.setRotation(this.BodyCenter, 1.134464f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer(this, 0, 720);
        this.Neck.addBox(-23.0f, -23.0f, -32.0f, 46, 46, 32);
        this.Neck.setRotationPoint(0.0f, -144.0f, -71.0f);
        this.Neck.mirror = true;
        this.setRotation(this.Neck, -0.0698132f, 0.0f, 0.0f);
        this.TopJaw = new ModelRenderer(this, 0, 892);
        this.TopJaw.addBox(-14.0f, -8.0f, -73.0f, 28, 26, 33);
        this.TopJaw.setRotationPoint(0.0f, -156.0f, -98.0f);
        this.TopJaw.mirror = true;
        this.setRotation(this.TopJaw, 0.0872665f, 0.0f, 0.0f);
        this.Head = new ModelRenderer(this, 0, 808);
        this.Head.addBox(-17.0f, -18.0f, -40.0f, 34, 36, 40);
        this.Head.setRotationPoint(0.0f, -156.0f, -98.0f);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0872665f, 0.0f, 0.0f);
        this.BodyTop = new ModelRenderer(this, 0, 0);
        this.BodyTop.addBox(-36.0f, -32.0f, -32.0f, 72, 40, 64);
        this.BodyTop.setRotationPoint(0.0f, -126.0f, -50.0f);
        this.BodyTop.mirror = true;
        this.setRotation(this.BodyTop, 1.308997f, 0.0f, 0.0f);
        this.RShoulder = new ModelRenderer(this, 304, 96);
        this.RShoulder.addBox(-16.0f, -32.0f, -32.0f, 16, 42, 46);
        this.RShoulder.setRotationPoint(-36.0f, -130.0f, -42.0f);
        this.RShoulder.mirror = true;
        this.setRotation(this.RShoulder, 1.308997f, 0.0f, 0.0f);
        this.RThumbTip = new ModelRenderer(this, 422, 18);
        this.RThumbTip.addBox(5.0f, 1.0f, -43.0f, 8, 8, 12);
        this.RThumbTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RThumbTip.mirror = true;
        this.setRotation(this.RThumbTip, 0.0f, 0.0f, 0.0f);
        this.RUpperArm = new ModelRenderer(this, 304, 184);
        this.RUpperArm.addBox(-54.0f, -13.0f, -13.0f, 54, 26, 26);
        this.RUpperArm.setRotationPoint(-38.0f, -130.0f, -52.0f);
        this.RUpperArm.mirror = true;
        this.setRotation(this.RUpperArm, 0.0f, -0.2617994f, -0.3490659f);
        this.RHand = new ModelRenderer(this, 245, 292);
        this.RHand.addBox(-13.0f, -13.0f, -13.0f, 26, 26, 26);
        this.RHand.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RHand.mirror = true;
        this.setRotation(this.RHand, -1.071467f, 2.007129f, 0.1745329f);
        this.RThumbBase = new ModelRenderer(this, 424, 57);
        this.RThumbBase.addBox(2.0f, 1.0f, -32.0f, 8, 8, 20);
        this.RThumbBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RThumbBase.mirror = true;
        this.setRotation(this.RThumbBase, 0.0f, -0.1047198f, 0.0f);
        this.R3rdFingerTip = new ModelRenderer(this, 422, 18);
        this.R3rdFingerTip.addBox(-10.0f, 0.0f, -41.0f, 8, 8, 12);
        this.R3rdFingerTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.R3rdFingerTip.mirror = true;
        this.setRotation(this.R3rdFingerTip, 0.0f, 0.6806784f, 0.0f);
        this.R3rdFingerBase = new ModelRenderer(this, 424, 57);
        this.R3rdFingerBase.addBox(-11.0f, -3.0f, -30.0f, 8, 8, 20);
        this.R3rdFingerBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.R3rdFingerBase.mirror = true;
        this.setRotation(this.R3rdFingerBase, 0.122173f, 0.6457718f, 0.0f);
        this.RIndexTip = new ModelRenderer(this, 422, 18);
        this.RIndexTip.addBox(-4.0f, -12.0f, -43.0f, 8, 8, 12);
        this.RIndexTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RIndexTip.mirror = true;
        this.setRotation(this.RIndexTip, -0.2094395f, 0.1745329f, 0.0f);
        this.RIndexBase = new ModelRenderer(this, 424, 57);
        this.RIndexBase.addBox(-4.0f, -9.0f, -34.0f, 8, 8, 20);
        this.RIndexBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
        this.RIndexBase.mirror = true;
        this.setRotation(this.RIndexBase, -0.2792527f, 0.1570796f, 0.0f);
        this.LShoulder = new ModelRenderer(this, 304, 96);
        this.LShoulder.addBox(0.0f, -32.0f, -32.0f, 16, 42, 46);
        this.LShoulder.setRotationPoint(36.0f, -130.0f, -42.0f);
        this.LShoulder.mirror = true;
        this.setRotation(this.LShoulder, 1.308997f, 0.0f, 0.0f);
        this.LUpperArm = new ModelRenderer(this, 304, 184);
        this.LUpperArm.addBox(0.0f, -13.0f, -13.0f, 54, 26, 26);
        this.LUpperArm.setRotationPoint(38.0f, -130.0f, -52.0f);
        this.LUpperArm.mirror = true;
        this.setRotation(this.LUpperArm, 0.0f, 0.296706f, 0.3490659f);
        this.LLowerArm = new ModelRenderer(this, 245, 240);
        this.LLowerArm.addBox(0.0f, -11.0f, -11.0f, 48, 22, 22);
        this.LLowerArm.setRotationPoint(80.0f, -115.0f, -61.0f);
        this.LLowerArm.mirror = true;
        this.setRotation(this.LLowerArm, 0.0f, 0.7853982f, 0.2617994f);
        this.LIndexBase = new ModelRenderer(this, 424, 57);
        this.LIndexBase.addBox(-4.0f, -13.0f, -32.0f, 8, 8, 20);
        this.LIndexBase.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LIndexBase.mirror = true;
        this.setRotation(this.LIndexBase, -0.1570796f, -0.1396263f, 0.0f);
        this.LIndexTip = new ModelRenderer(this, 422, 18);
        this.LIndexTip.addBox(-1.0f, -18.0f, -41.0f, 8, 8, 12);
        this.LIndexTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LIndexTip.mirror = true;
        this.setRotation(this.LIndexTip, 0.0f, -0.0349066f, 0.0f);
        this.LHand = new ModelRenderer(this, 245, 292);
        this.LHand.addBox(-13.0f, -13.0f, -13.0f, 26, 26, 26);
        this.LHand.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LHand.mirror = true;
        this.setRotation(this.LHand, 0.9599311f, 1.308997f, 0.1745329f);
        this.LThumbBase = new ModelRenderer(this, 424, 57);
        this.LThumbBase.addBox(-8.0f, -2.0f, -32.0f, 8, 8, 20);
        this.LThumbBase.setRotationPoint(115.0f, -100.0f, -98.0f);
        this.LThumbBase.mirror = true;
        this.setRotation(this.LThumbBase, 0.1396263f, 0.2617994f, 0.0f);
        this.LThumbTip = new ModelRenderer(this, 422, 18);
        this.LThumbTip.addBox(-12.0f, 2.0f, -40.0f, 8, 8, 12);
        this.LThumbTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.LThumbTip.mirror = true;
        this.setRotation(this.LThumbTip, 0.0f, 0.1396263f, 0.0f);
        this.L3rdFingerTip = new ModelRenderer(this, 422, 18);
        this.L3rdFingerTip.addBox(9.0f, 2.0f, -42.0f, 8, 8, 12);
        this.L3rdFingerTip.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.L3rdFingerTip.mirror = true;
        this.setRotation(this.L3rdFingerTip, 0.0349066f, -0.3316126f, 0.0f);
        this.L3rdFingerBase = new ModelRenderer(this, 424, 57);
        this.L3rdFingerBase.addBox(4.0f, -5.0f, -33.0f, 8, 8, 20);
        this.L3rdFingerBase.setRotationPoint(115.0f, -100.0f, -99.0f);
        this.L3rdFingerBase.mirror = true;
        this.setRotation(this.L3rdFingerBase, 0.2617994f, -0.4712389f, 0.0f);
        this.Lspikes1 = new ModelRenderer(this, 500, 0);
        this.Lspikes1.addBox(0.0f, -10.0f, 0.0f, 0, 10, 11);
        this.Lspikes1.setRotationPoint(5.0f, -168.0f, -86.0f);
        this.Lspikes1.mirror = true;
        this.setRotation(this.Lspikes1, -0.0872665f, 0.0f, -0.0174533f);
        this.Rspikes1 = new ModelRenderer(this, 500, 0);
        this.Rspikes1.addBox(0.0f, -10.0f, 0.0f, 0, 10, 11);
        this.Rspikes1.setRotationPoint(-5.0f, -168.0f, -86.0f);
        this.Rspikes1.mirror = true;
        this.setRotation(this.Rspikes1, -0.0872665f, 0.0f, -0.0174533f);
        this.Lspike2 = new ModelRenderer(this, 500, 30);
        this.Lspike2.addBox(0.0f, -25.0f, 0.0f, 0, 25, 21);
        this.Lspike2.setRotationPoint(10.0f, -162.0f, -63.0f);
        this.Lspike2.mirror = true;
        this.setRotation(this.Lspike2, -0.2617994f, 0.0f, -0.0174533f);
        this.Rspike2 = new ModelRenderer(this, 500, 30);
        this.Rspike2.addBox(0.0f, -25.0f, 0.0f, 0, 25, 21);
        this.Rspike2.setRotationPoint(-10.0f, -162.0f, -63.0f);
        this.Rspike2.mirror = true;
        this.setRotation(this.Rspike2, -0.2617994f, 0.0f, -0.0174533f);
        this.Lspike3 = new ModelRenderer(this, 500, 80);
        this.Lspike3.addBox(0.0f, -45.0f, 0.0f, 0, 45, 34);
        this.Lspike3.setRotationPoint(14.0f, -153.0f, -32.0f);
        this.Lspike3.mirror = true;
        this.setRotation(this.Lspike3, -0.4363323f, 0.0f, -0.0174533f);
        this.Rspike3 = new ModelRenderer(this, 500, 80);
        this.Rspike3.addBox(0.0f, -45.0f, 0.0f, 0, 45, 34);
        this.Rspike3.setRotationPoint(-14.0f, -153.0f, -32.0f);
        this.Rspike3.mirror = true;
        this.setRotation(this.Rspike3, -0.4363323f, 0.0f, -0.0174533f);
        this.Lspike4 = new ModelRenderer(this, 500, 165);
        this.Lspike4.addBox(0.0f, -50.0f, 0.0f, 0, 50, 36);
        this.Lspike4.setRotationPoint(18.0f, -131.0f, 13.0f);
        this.Lspike4.mirror = true;
        this.setRotation(this.Lspike4, -0.715585f, 0.0f, -0.0174533f);
        this.Rspike4 = new ModelRenderer(this, 500, 165);
        this.Rspike4.addBox(0.0f, -50.0f, 0.0f, 0, 50, 36);
        this.Rspike4.setRotationPoint(-18.0f, -131.0f, 13.0f);
        this.Rspike4.mirror = true;
        this.setRotation(this.Rspike4, -0.715585f, 0.0f, -0.0174533f);
        this.Lspike5 = new ModelRenderer(this, 500, 255);
        this.Lspike5.addBox(12.0f, -67.0f, 5.0f, 0, 39, 27);
        this.Lspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.Lspike5.mirror = true;
        this.setRotation(this.Lspike5, -0.7853982f, 0.0f, -0.0174533f);
        this.Rspike5 = new ModelRenderer(this, 500, 255);
        this.Rspike5.addBox(-12.0f, -67.0f, 5.0f, 0, 39, 27);
        this.Rspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
        this.Rspike5.mirror = true;
        this.setRotation(this.Rspike5, -0.7853982f, 0.0f, -0.0174533f);
        this.Spike6 = new ModelRenderer(this, 500, 325);
        this.Spike6.addBox(0.0f, -48.0f, 11.0f, 0, 25, 21);
        this.Spike6.setRotationPoint(0.0f, -48.0f, 48.0f);
        this.Spike6.mirror = true;
        this.setRotation(this.Spike6, -0.8901179f, 0.0f, -0.0174533f);
        this.Spikes7 = new ModelRenderer(this, 500, 376);
        this.Spikes7.addBox(0.0f, -29.0f, 20.0f, 0, 10, 11);
        this.Spikes7.setRotationPoint(0.0f, -24.0f, 66.0f);
        this.Spikes7.mirror = true;
        this.setRotation(this.Spikes7, -0.7504916f, 0.0f, -0.0174533f);
    }

    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        if (frameEntity == null) return;
        Entity entity=frameEntity;
        float f=frameSwing, f1=frameAmount, f2=frameAge, f3=frameYaw, f4=framePitch, f5=0.0625F;
        matrixStack.push();
this.LToe1.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe1, 0.0f, 0.7853982f, 0.0f);
this.LToe3.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe3, 0.0f, 0.7853982f, 0.0f);
this.LToe2.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe2, 0.0f, 0.7853982f, 0.0f);
this.LToe9.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe9, 0.0f, -0.7853982f, 0.0f);
this.LToe8.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe8, 0.0f, -0.7853982f, 0.0f);
this.LToe7.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe7, 0.0f, -0.7853982f, 0.0f);
this.LToe6.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe6, 0.0f, 0.0f, 0.0f);
this.LToe5.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe5, 0.0f, 0.0f, 0.0f);
this.LToe4.setRotationPoint(54.0f, 16.0f, 6.0f);
this.setRotation(this.LToe4, 0.0f, 0.0f, 0.0f);
this.RToe9.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe9, 0.0f, 0.7853982f, 0.0f);
this.RToe6.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe6, 0.0f, 0.0f, 0.0f);
this.RToe5.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe5, 0.0f, 0.0f, 0.0f);
this.RToe2.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe2, 0.0f, -0.7853982f, 0.0f);
this.RToe1.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe1, 0.0f, -0.7853982f, 0.0f);
this.RToe4.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe4, 0.0f, 0.0f, 0.0f);
this.RToe7.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe7, 0.0f, 0.7853982f, 0.0f);
this.RToe8.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe8, 0.0f, 0.7853982f, 0.0f);
this.RToe3.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RToe3, 0.0f, -0.7853982f, 0.0f);
this.LThigh.setRotationPoint(40.0f, -91.0f, 2.0f);
this.setRotation(this.LThigh, -0.5585054f, 0.0f, 0.0f);
this.LLowerLeg.setRotationPoint(54.0f, 14.0f, 6.0f);
this.setRotation(this.LLowerLeg, 0.1745329f, -0.1308997f, 0.0f);
this.LUpperLeg.setRotationPoint(56.0f, -36.0f, -5.0f);
this.setRotation(this.LUpperLeg, -0.1745329f, -0.3926991f, -0.0872665f);
this.TailTip.setRotationPoint(0.0f, 18.0f, 203.0f);
this.setRotation(this.TailTip, 1.53589f, 0.0f, 0.0f);
this.RLegLower.setRotationPoint(-54.0f, 16.0f, 6.0f);
this.setRotation(this.RLegLower, 0.1745329f, 0.1308997f, 0.0f);
this.RLegUpper.setRotationPoint(-56.0f, -36.0f, -5.0f);
this.setRotation(this.RLegUpper, -0.1745329f, 0.3926991f, 0.0872665f);
this.RThigh.setRotationPoint(-40.0f, -91.0f, 2.0f);
this.setRotation(this.RThigh, -0.5585054f, 0.0f, 0.0f);
this.LowerJaw.setRotationPoint(0.0f, -142.0f, -109.0f);
this.setRotation(this.LowerJaw, 0.5235988f, 0.0f, 0.0f);
this.TailBase.setRotationPoint(0.0f, -73.0f, 26.0f);
this.setRotation(this.TailBase, 0.7853982f, 0.0f, 0.0f);
this.Tail2.setRotationPoint(0.0f, -48.0f, 48.0f);
this.setRotation(this.Tail2, 0.6981317f, 0.0f, 0.0f);
this.Tail3.setRotationPoint(0.0f, -24.0f, 66.0f);
this.setRotation(this.Tail3, 0.8726646f, 0.0f, 0.0f);
this.Tail4.setRotationPoint(0.0f, -3.0f, 87.0f);
this.setRotation(this.Tail4, 1.134464f, 0.0f, 0.0f);
this.Tail5.setRotationPoint(0.0f, 12.0f, 116.0f);
this.setRotation(this.Tail5, 1.53589f, 0.0f, 0.0f);
this.Tail6.setRotationPoint(0.0f, 14.0f, 154.0f);
this.setRotation(this.Tail6, 1.53589f, 0.0f, 0.0f);
this.Tail7.setRotationPoint(0.0f, 16.0f, 185.0f);
this.setRotation(this.Tail7, 1.53589f, 0.0f, 0.0f);
this.BodyBottom.setRotationPoint(0.0f, -112.0f, -20.0f);
this.setRotation(this.BodyBottom, 0.8726646f, 0.0f, 0.0f);
this.RLowerArm.setRotationPoint(-80.0f, -115.0f, -61.0f);
this.setRotation(this.RLowerArm, 0.0f, -0.7853982f, -0.2617994f);
this.BodyCenter.setRotationPoint(0.0f, -112.0f, -20.0f);
this.setRotation(this.BodyCenter, 1.134464f, 0.0f, 0.0f);
this.Neck.setRotationPoint(0.0f, -144.0f, -71.0f);
this.setRotation(this.Neck, -0.0698132f, 0.0f, 0.0f);
this.TopJaw.setRotationPoint(0.0f, -156.0f, -98.0f);
this.setRotation(this.TopJaw, 0.0872665f, 0.0f, 0.0f);
this.Head.setRotationPoint(0.0f, -156.0f, -98.0f);
this.setRotation(this.Head, 0.0872665f, 0.0f, 0.0f);
this.BodyTop.setRotationPoint(0.0f, -126.0f, -50.0f);
this.setRotation(this.BodyTop, 1.308997f, 0.0f, 0.0f);
this.RShoulder.setRotationPoint(-36.0f, -130.0f, -42.0f);
this.setRotation(this.RShoulder, 1.308997f, 0.0f, 0.0f);
this.RThumbTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.RThumbTip, 0.0f, 0.0f, 0.0f);
this.RUpperArm.setRotationPoint(-38.0f, -130.0f, -52.0f);
this.setRotation(this.RUpperArm, 0.0f, -0.2617994f, -0.3490659f);
this.RHand.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.RHand, -1.071467f, 2.007129f, 0.1745329f);
this.RThumbBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.RThumbBase, 0.0f, -0.1047198f, 0.0f);
this.R3rdFingerTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.R3rdFingerTip, 0.0f, 0.6806784f, 0.0f);
this.R3rdFingerBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.R3rdFingerBase, 0.122173f, 0.6457718f, 0.0f);
this.RIndexTip.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.RIndexTip, -0.2094395f, 0.1745329f, 0.0f);
this.RIndexBase.setRotationPoint(-115.0f, -100.0f, -99.0f);
this.setRotation(this.RIndexBase, -0.2792527f, 0.1570796f, 0.0f);
this.LShoulder.setRotationPoint(36.0f, -130.0f, -42.0f);
this.setRotation(this.LShoulder, 1.308997f, 0.0f, 0.0f);
this.LUpperArm.setRotationPoint(38.0f, -130.0f, -52.0f);
this.setRotation(this.LUpperArm, 0.0f, 0.296706f, 0.3490659f);
this.LLowerArm.setRotationPoint(80.0f, -115.0f, -61.0f);
this.setRotation(this.LLowerArm, 0.0f, 0.7853982f, 0.2617994f);
this.LIndexBase.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.LIndexBase, -0.1570796f, -0.1396263f, 0.0f);
this.LIndexTip.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.LIndexTip, 0.0f, -0.0349066f, 0.0f);
this.LHand.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.LHand, 0.9599311f, 1.308997f, 0.1745329f);
this.LThumbBase.setRotationPoint(115.0f, -100.0f, -98.0f);
this.setRotation(this.LThumbBase, 0.1396263f, 0.2617994f, 0.0f);
this.LThumbTip.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.LThumbTip, 0.0f, 0.1396263f, 0.0f);
this.L3rdFingerTip.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.L3rdFingerTip, 0.0349066f, -0.3316126f, 0.0f);
this.L3rdFingerBase.setRotationPoint(115.0f, -100.0f, -99.0f);
this.setRotation(this.L3rdFingerBase, 0.2617994f, -0.4712389f, 0.0f);
this.Lspikes1.setRotationPoint(5.0f, -168.0f, -86.0f);
this.setRotation(this.Lspikes1, -0.0872665f, 0.0f, -0.0174533f);
this.Rspikes1.setRotationPoint(-5.0f, -168.0f, -86.0f);
this.setRotation(this.Rspikes1, -0.0872665f, 0.0f, -0.0174533f);
this.Lspike2.setRotationPoint(10.0f, -162.0f, -63.0f);
this.setRotation(this.Lspike2, -0.2617994f, 0.0f, -0.0174533f);
this.Rspike2.setRotationPoint(-10.0f, -162.0f, -63.0f);
this.setRotation(this.Rspike2, -0.2617994f, 0.0f, -0.0174533f);
this.Lspike3.setRotationPoint(14.0f, -153.0f, -32.0f);
this.setRotation(this.Lspike3, -0.4363323f, 0.0f, -0.0174533f);
this.Rspike3.setRotationPoint(-14.0f, -153.0f, -32.0f);
this.setRotation(this.Rspike3, -0.4363323f, 0.0f, -0.0174533f);
this.Lspike4.setRotationPoint(18.0f, -131.0f, 13.0f);
this.setRotation(this.Lspike4, -0.715585f, 0.0f, -0.0174533f);
this.Rspike4.setRotationPoint(-18.0f, -131.0f, 13.0f);
this.setRotation(this.Rspike4, -0.715585f, 0.0f, -0.0174533f);
this.Lspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
this.setRotation(this.Lspike5, -0.7853982f, 0.0f, -0.0174533f);
this.Rspike5.setRotationPoint(0.0f, -73.0f, 26.0f);
this.setRotation(this.Rspike5, -0.7853982f, 0.0f, -0.0174533f);
this.Spike6.setRotationPoint(0.0f, -48.0f, 48.0f);
this.setRotation(this.Spike6, -0.8901179f, 0.0f, -0.0174533f);
this.Spikes7.setRotationPoint(0.0f, -24.0f, 66.0f);
this.setRotation(this.Spikes7, -0.7504916f, 0.0f, -0.0174533f);

        GodzillaEntity.CustomEntity e = (GodzillaEntity.CustomEntity)entity;
        RenderInfo r = null;
        float newangle = 0.0f;
        float newangle2 = 0.0f;
        float pscale = 1.0f;
        float pi4 = 0.7853982f;
        float clawZ = 6.0f;
        float clawY = 16.0f;
        float clawZamp = 35.0f * pscale;
        float clawYamp = 18.0f * pscale;
        float spikeamp = 1.0f;
        float spikefreq = 1.0f;
        this.legacyAngles(f, f1, f2, f3, f4, f5, entity);
        r = e.getRenderInfo();
        float t1 = 0.0f;
        float t2 = 0.0f;
        if ((double)f1 > 0.001) {
            newangle = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale));
            newangle2 = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale + pi4));
            t1 = MathHelper.sin((float)(f2 * 0.75f * this.wingspeed / pscale));
        } else {
            newangle2 = 0.0f;
            newangle = 0.0f;
            t1 = 0.0f;
            t2 = 0.0f;
        }
        if (t1 > 0.0f) {
            t2 = t1 * clawYamp * f1;
            this.LToe1.rotationPointY = clawY - t2;
        } else {
            this.LToe1.rotationPointY = clawY;
        }
        this.LToe8.rotationPointZ = this.LToe9.rotationPointZ = (this.LToe1.rotationPointZ = clawZ + clawZamp * newangle * f1);
        this.LToe7.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe6.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe5.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe4.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe3.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe2.rotationPointZ = this.LToe9.rotationPointZ;
        this.LToe8.rotationPointY = this.LToe9.rotationPointY = this.LToe1.rotationPointY;
        this.LToe7.rotationPointY = this.LToe9.rotationPointY;
        this.LToe6.rotationPointY = this.LToe9.rotationPointY;
        this.LToe5.rotationPointY = this.LToe9.rotationPointY;
        this.LToe4.rotationPointY = this.LToe9.rotationPointY;
        this.LToe3.rotationPointY = this.LToe9.rotationPointY;
        this.LToe2.rotationPointY = this.LToe9.rotationPointY;
        this.LLowerLeg.rotationPointZ = this.LToe1.rotationPointZ;
        this.LLowerLeg.rotationPointY = this.LToe1.rotationPointY;
        this.LLowerLeg.rotateAngleX = 0.22f + newangle * (float)Math.PI * 0.09f * f1;
        this.LUpperLeg.rotateAngleX = -0.17f + newangle2 * (float)Math.PI * 0.15f * f1;
        this.LUpperLeg.rotationPointY = this.LLowerLeg.rotationPointY - (float)Math.cos(this.LLowerLeg.rotateAngleX) * 55.0f;
        this.LUpperLeg.rotationPointZ = this.LLowerLeg.rotationPointZ - (float)Math.sin(this.LLowerLeg.rotateAngleX) * 55.0f;
        this.LThigh.rotateAngleX = -0.558f + newangle2 * (float)Math.PI * 0.1f * f1;
        this.LThigh.rotationPointZ = 2.0f + clawZamp * newangle * f1 / 4.0f;
        t1 = 0.0f;
        t2 = 0.0f;
        if ((double)f1 > 0.001) {
            newangle = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
            newangle2 = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale + pi4 * 5.0f));
            t1 = MathHelper.sin((float)(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
        } else {
            newangle = 0.0f;
            t1 = 0.0f;
            t2 = 0.0f;
        }
        if (t1 > 0.0f) {
            t2 = t1 * clawYamp * f1;
            this.RToe1.rotationPointY = clawY - t2;
        } else {
            this.RToe1.rotationPointY = clawY;
        }
        this.RToe8.rotationPointZ = this.RToe9.rotationPointZ = (this.RToe1.rotationPointZ = clawZ + clawZamp * newangle * f1);
        this.RToe7.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe6.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe5.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe4.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe3.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe2.rotationPointZ = this.RToe9.rotationPointZ;
        this.RToe8.rotationPointY = this.RToe9.rotationPointY = this.RToe1.rotationPointY;
        this.RToe7.rotationPointY = this.RToe9.rotationPointY;
        this.RToe6.rotationPointY = this.RToe9.rotationPointY;
        this.RToe5.rotationPointY = this.RToe9.rotationPointY;
        this.RToe4.rotationPointY = this.RToe9.rotationPointY;
        this.RToe3.rotationPointY = this.RToe9.rotationPointY;
        this.RToe2.rotationPointY = this.RToe9.rotationPointY;
        this.RLegLower.rotationPointZ = this.RToe1.rotationPointZ;
        this.RLegLower.rotationPointY = this.RToe1.rotationPointY;
        this.RLegLower.rotateAngleX = 0.22f + newangle * (float)Math.PI * 0.09f * f1;
        this.RLegUpper.rotateAngleX = -0.17f + newangle2 * (float)Math.PI * 0.15f * f1;
        this.RLegUpper.rotationPointY = this.RLegLower.rotationPointY - (float)Math.cos(this.RLegLower.rotateAngleX) * 55.0f;
        this.RLegUpper.rotationPointZ = this.RLegLower.rotationPointZ - (float)Math.sin(this.RLegLower.rotateAngleX) * 55.0f;
        this.RThigh.rotateAngleX = -0.558f + newangle2 * (float)Math.PI * 0.1f * f1;
        this.RThigh.rotationPointZ = 2.0f + clawZamp * newangle * f1 / 4.0f;
        this.LToe1.rotateAngleX = 0.0f;
        this.LToe9.rotateAngleX = 0.0f;
        this.LToe8.rotateAngleX = 0.0f;
        this.LToe7.rotateAngleX = 0.0f;
        this.LToe6.rotateAngleX = 0.0f;
        this.LToe5.rotateAngleX = 0.0f;
        this.LToe4.rotateAngleX = 0.0f;
        this.LToe3.rotateAngleX = 0.0f;
        this.LToe2.rotateAngleX = 0.0f;
        this.RToe1.rotateAngleX = 0.0f;
        this.RToe9.rotateAngleX = 0.0f;
        this.RToe8.rotateAngleX = 0.0f;
        this.RToe7.rotateAngleX = 0.0f;
        this.RToe6.rotateAngleX = 0.0f;
        this.RToe5.rotateAngleX = 0.0f;
        this.RToe4.rotateAngleX = 0.0f;
        this.RToe3.rotateAngleX = 0.0f;
        this.RToe2.rotateAngleX = 0.0f;
        newangle = e.getAttacking() != 0 ? MathHelper.cos((float)(f2 * this.wingspeed * 1.75f)) * (float)Math.PI * 0.2f : MathHelper.cos((float)(f2 * this.wingspeed * 0.75f)) * (float)Math.PI * 0.05f;
        this.doTail(newangle);
        this.Head.rotateAngleY = newangle = (float)Math.toRadians(f3) * 0.55f;
        this.TopJaw.rotateAngleY = newangle;
        this.LowerJaw.rotateAngleY = newangle;
        this.LowerJaw.rotationPointZ = this.Head.rotationPointZ - (float)Math.cos(this.Head.rotateAngleY) * 11.0f;
        this.LowerJaw.rotationPointX = this.Head.rotationPointX - (float)Math.sin(this.Head.rotateAngleY) * 11.0f;
        this.TopJaw.rotateAngleX = this.Head.rotateAngleX = (float)Math.toRadians(f4);
        newangle = MathHelper.cos((float)(f2 * this.wingspeed * 1.5f)) * (float)Math.PI * 0.12f;
        float newrf1 = f2 * 1.5f * this.wingspeed % ((float)Math.PI * 2);
        newrf1 = Math.abs(newrf1);
        if (newrf1 < r.rf2) {
            r.ri2 = 0;
            if (e.getAttacking() == 0) {
                if (e.getModelRandom().nextInt(20) == 1) {
                    r.ri2 |= 1;
                }
            } else if (e.getModelRandom().nextInt(2) == 1) {
                r.ri2 |= 1;
            }
        }
        r.rf2 = newrf1;
        if ((r.ri2 & 1) == 0) {
            newangle = 0.0f;
        }
        this.LowerJaw.rotateAngleX = 0.52f + newangle + this.TopJaw.rotateAngleX;
        newangle = newangle2 = MathHelper.sin((float)(f2 * this.wingspeed * 1.75f)) * (float)Math.PI * 0.16f;
        newrf1 = f2 * 1.75f * this.wingspeed % ((float)Math.PI * 2);
        if ((newrf1 = Math.abs(newrf1)) < r.rf1) {
            r.ri1 = 0;
            if (e.getAttacking() == 0) {
                if (e.getModelRandom().nextInt(20) == 1) {
                    r.ri1 |= 1;
                }
                if (e.getModelRandom().nextInt(20) == 1) {
                    r.ri1 |= 2;
                }
            } else {
                if (e.getModelRandom().nextInt(2) == 1) {
                    r.ri1 |= 1;
                }
                if (e.getModelRandom().nextInt(2) == 1) {
                    r.ri1 |= 2;
                }
            }
        }
        r.rf1 = newrf1;
        if ((r.ri1 & 1) == 0) {
            newangle = 0.0f;
        }
        if ((r.ri1 & 2) == 0) {
            newangle2 = 0.0f;
        }
        this.LUpperArm.rotateAngleY = 0.65f + newangle;
        this.LLowerArm.rotateAngleY = 0.78f + newangle * 3.0f / 2.0f;
        this.LLowerArm.rotationPointZ = this.LUpperArm.rotationPointZ - (float)Math.sin(this.LUpperArm.rotateAngleY) * 50.0f;
        this.LLowerArm.rotationPointX = this.LUpperArm.rotationPointX + (float)Math.cos(this.LUpperArm.rotateAngleY) * 50.0f;
        this.LLowerArm.rotationPointY = this.LUpperArm.rotationPointY - (float)Math.sin(this.LUpperArm.rotateAngleY) * 10.0f + 18.0f;
        this.LHand.rotationPointZ = this.LLowerArm.rotationPointZ - (float)Math.sin(this.LLowerArm.rotateAngleY) * 45.0f;
        this.LHand.rotationPointX = this.LLowerArm.rotationPointX + (float)Math.cos(this.LLowerArm.rotateAngleY) * 45.0f;
        this.LHand.rotationPointY = this.LLowerArm.rotationPointY - (float)Math.sin(this.LLowerArm.rotateAngleY) * 10.0f + 15.0f;
        this.LThumbBase.rotationPointZ = this.L3rdFingerBase.rotationPointZ = this.LHand.rotationPointZ;
        this.LIndexBase.rotationPointZ = this.L3rdFingerBase.rotationPointZ;
        this.LThumbTip.rotationPointZ = this.L3rdFingerTip.rotationPointZ = this.LHand.rotationPointZ;
        this.LIndexTip.rotationPointZ = this.L3rdFingerTip.rotationPointZ;
        this.LThumbBase.rotationPointY = this.L3rdFingerBase.rotationPointY = this.LHand.rotationPointY;
        this.LIndexBase.rotationPointY = this.L3rdFingerBase.rotationPointY;
        this.LThumbTip.rotationPointY = this.L3rdFingerTip.rotationPointY = this.LHand.rotationPointY;
        this.LIndexTip.rotationPointY = this.L3rdFingerTip.rotationPointY;
        this.LThumbBase.rotationPointX = this.L3rdFingerBase.rotationPointX = this.LHand.rotationPointX;
        this.LIndexBase.rotationPointX = this.L3rdFingerBase.rotationPointX;
        this.LThumbTip.rotationPointX = this.L3rdFingerTip.rotationPointX = this.LHand.rotationPointX;
        this.LIndexTip.rotationPointX = this.L3rdFingerTip.rotationPointX;
        this.LHand.rotateAngleY = 1.308f + newangle * 2.0f;
        this.LIndexBase.rotateAngleY = -0.139f + newangle * 2.0f;
        this.LIndexTip.rotateAngleY = -0.034f + newangle * 2.0f;
        this.LThumbBase.rotateAngleY = 0.261f + newangle;
        this.LThumbTip.rotateAngleY = 0.139f + newangle;
        this.L3rdFingerBase.rotateAngleY = -0.471f + newangle * 3.0f;
        this.L3rdFingerTip.rotateAngleY = -0.331f + newangle * 3.0f;
        this.RUpperArm.rotateAngleY = -0.65f - newangle2;
        this.RLowerArm.rotateAngleY = -0.78f - newangle2 * 3.0f / 2.0f;
        this.RLowerArm.rotationPointZ = this.RUpperArm.rotationPointZ + (float)Math.sin(this.RUpperArm.rotateAngleY) * 50.0f;
        this.RLowerArm.rotationPointX = this.RUpperArm.rotationPointX - (float)Math.cos(this.RUpperArm.rotateAngleY) * 50.0f;
        this.RLowerArm.rotationPointY = this.RUpperArm.rotationPointY + (float)Math.sin(this.RUpperArm.rotateAngleY) * 10.0f + 18.0f;
        this.RHand.rotationPointZ = this.RLowerArm.rotationPointZ + (float)Math.sin(this.RLowerArm.rotateAngleY) * 45.0f;
        this.RHand.rotationPointX = this.RLowerArm.rotationPointX - (float)Math.cos(this.RLowerArm.rotateAngleY) * 45.0f;
        this.RHand.rotationPointY = this.RLowerArm.rotationPointY + (float)Math.sin(this.RLowerArm.rotateAngleY) * 10.0f + 15.0f;
        this.RThumbBase.rotationPointZ = this.R3rdFingerBase.rotationPointZ = this.RHand.rotationPointZ;
        this.RIndexBase.rotationPointZ = this.R3rdFingerBase.rotationPointZ;
        this.RThumbTip.rotationPointZ = this.R3rdFingerTip.rotationPointZ = this.RHand.rotationPointZ;
        this.RIndexTip.rotationPointZ = this.R3rdFingerTip.rotationPointZ;
        this.RThumbBase.rotationPointY = this.R3rdFingerBase.rotationPointY = this.RHand.rotationPointY;
        this.RIndexBase.rotationPointY = this.R3rdFingerBase.rotationPointY;
        this.RThumbTip.rotationPointY = this.R3rdFingerTip.rotationPointY = this.RHand.rotationPointY;
        this.RIndexTip.rotationPointY = this.R3rdFingerTip.rotationPointY;
        this.RThumbBase.rotationPointX = this.R3rdFingerBase.rotationPointX = this.RHand.rotationPointX;
        this.RIndexBase.rotationPointX = this.R3rdFingerBase.rotationPointX;
        this.RThumbTip.rotationPointX = this.R3rdFingerTip.rotationPointX = this.RHand.rotationPointX;
        this.RIndexTip.rotationPointX = this.R3rdFingerTip.rotationPointX;
        this.RHand.rotateAngleY = -2.0f - newangle2 * 2.0f;
        this.RIndexBase.rotateAngleY = 0.157f - newangle2 * 2.0f;
        this.RIndexTip.rotateAngleY = 0.174f - newangle2 * 2.0f;
        this.RThumbBase.rotateAngleY = -0.104f - newangle2;
        this.RThumbTip.rotateAngleY = 0.001f - newangle2;
        this.R3rdFingerTip.rotateAngleY = 0.68f - newangle2 * 3.0f;
        this.R3rdFingerBase.rotateAngleY = 0.645f - newangle2 * 3.0f;
        e.setRenderInfo(r);
        this.LToe1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LToe4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RToe3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LThigh.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLowerLeg.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LUpperLeg.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLegLower.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLegUpper.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RThigh.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LowerJaw.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TailBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Tail7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyBottom.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RLowerArm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyCenter.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Neck.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.TopJaw.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Head.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.BodyTop.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RShoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RThumbTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RUpperArm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RHand.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RThumbBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.R3rdFingerTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.R3rdFingerBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RIndexTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.RIndexBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LShoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LUpperArm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LLowerArm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LIndexBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LIndexTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LHand.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LThumbBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.LThumbTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.L3rdFingerTip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.L3rdFingerBase.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lspikes1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rspikes1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lspike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rspike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lspike3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rspike3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lspike4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rspike4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Lspike5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Rspike5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spike6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.Spikes7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    
        matrixStack.pop();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void legacyAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
    }

    private void doTail(float angle) {
        this.Lspike5.rotateAngleY = this.Rspike5.rotateAngleY = (this.TailBase.rotateAngleY = angle * 0.25f);
        this.Tail2.rotateAngleY = angle * 0.5f;
        this.Tail2.rotationPointZ = this.TailBase.rotationPointZ + (float)Math.cos(this.TailBase.rotateAngleY) * 25.0f;
        this.Tail2.rotationPointX = this.TailBase.rotationPointX + (float)Math.sin(this.TailBase.rotateAngleY) * 25.0f;
        this.Spike6.rotateAngleY = this.Tail2.rotateAngleY;
        this.Spike6.rotationPointZ = this.Tail2.rotationPointZ;
        this.Spike6.rotationPointX = this.Tail2.rotationPointX;
        this.Tail3.rotateAngleY = angle * 0.75f;
        this.Tail3.rotationPointZ = this.Tail2.rotationPointZ + (float)Math.cos(this.Tail2.rotateAngleY) * 20.0f;
        this.Tail3.rotationPointX = this.Tail2.rotationPointX + (float)Math.sin(this.Tail2.rotateAngleY) * 20.0f;
        this.Spikes7.rotateAngleY = this.Tail3.rotateAngleY;
        this.Spikes7.rotationPointZ = this.Tail3.rotationPointZ;
        this.Spikes7.rotationPointX = this.Tail3.rotationPointX;
        this.Tail4.rotateAngleY = angle * 1.25f;
        this.Tail4.rotationPointZ = this.Tail3.rotationPointZ + (float)Math.cos(this.Tail3.rotateAngleY) * 20.0f;
        this.Tail4.rotationPointX = this.Tail3.rotationPointX + (float)Math.sin(this.Tail3.rotateAngleY) * 20.0f;
        this.Tail5.rotateAngleY = angle * 1.5f;
        this.Tail5.rotationPointZ = this.Tail4.rotationPointZ + (float)Math.cos(this.Tail4.rotateAngleY) * 25.0f;
        this.Tail5.rotationPointX = this.Tail4.rotationPointX + (float)Math.sin(this.Tail4.rotateAngleY) * 25.0f;
        this.Tail6.rotateAngleY = angle * 1.75f;
        this.Tail6.rotationPointZ = this.Tail5.rotationPointZ + (float)Math.cos(this.Tail5.rotateAngleY) * 27.0f;
        this.Tail6.rotationPointX = this.Tail5.rotationPointX + (float)Math.sin(this.Tail5.rotateAngleY) * 27.0f;
        this.Tail7.rotateAngleY = angle * 2.0f;
        this.Tail7.rotationPointZ = this.Tail6.rotationPointZ + (float)Math.cos(this.Tail6.rotateAngleY) * 28.0f;
        this.Tail7.rotationPointX = this.Tail6.rotationPointX + (float)Math.sin(this.Tail6.rotateAngleY) * 28.0f;
        this.TailTip.rotateAngleY = angle * 2.25f;
        this.TailTip.rotationPointZ = this.Tail7.rotationPointZ + (float)Math.cos(this.Tail7.rotateAngleY) * 18.0f;
        this.TailTip.rotationPointX = this.Tail7.rotationPointX + (float)Math.sin(this.Tail7.rotateAngleY) * 18.0f;
    }
}


}
