package net.mcreator.xillysorespawn.entity.renderer;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.mcreator.xillysorespawn.entity.MolenoidEntity;
import net.mcreator.xillysorespawn.entity.OreSpawnLogic;

@OnlyIn(Dist.CLIENT)
public class MolenoidRenderer {
    private static final String TEXTURE = "xillys_orespawn:textures/entities/molenoidtexture.png";
    public static class ModelRegisterHandler {
        @SubscribeEvent @OnlyIn(Dist.CLIENT)
        public void registerModels(ModelRegistryEvent event) {
            RenderingRegistry.registerEntityRenderingHandler(MolenoidEntity.entity, manager ->
                new MobRenderer(manager, new ModelMolenoid(0.5F), 1.0F) {
                    @Override public ResourceLocation getEntityTexture(Entity entity) { return new ResourceLocation(TEXTURE); }
                    @Override protected void preRenderCallback(LivingEntity entity, MatrixStack stack, float partialTick) {
                        float modelScale = 1.0F;
                        stack.scale(modelScale, modelScale, modelScale);
                    }
                });
        }
    }

public static class ModelMolenoid extends EntityModel<Entity> {
    // Exact legacy render order recovered from bytecode; do not add a second addChild rig.
    private Entity frameEntity;
    private float frameSwing, frameAmount, frameAge, frameYaw, framePitch;
    @Override public void setRotationAngles(Entity entity, float swing, float amount, float age, float yaw, float pitch) {
        frameEntity=entity; frameSwing=swing; frameAmount=amount; frameAge=age; frameYaw=yaw; framePitch=pitch;
    }

    private float wingspeed = 1.0f;
    private final ModelRenderer body;
    private final ModelRenderer shoulders;
    private final ModelRenderer head1;
    private final ModelRenderer head2;
    private final ModelRenderer head3;
    private final ModelRenderer nosestar1;
    private final ModelRenderer nosestar2;
    private final ModelRenderer nosestar3;
    private final ModelRenderer larm;
    private final ModelRenderer lhand;
    private final ModelRenderer lclaw1;
    private final ModelRenderer lclaw2;
    private final ModelRenderer lclaw3;
    private final ModelRenderer lclaw4;
    private final ModelRenderer nosestar4;
    private final ModelRenderer nosestar5;
    private final ModelRenderer nosestar6;
    private final ModelRenderer butt;
    private final ModelRenderer tail;
    private final ModelRenderer lleg;
    private final ModelRenderer lfoot;
    private final ModelRenderer ltoe1;
    private final ModelRenderer ltoe2;
    private final ModelRenderer ltoe3;
    private final ModelRenderer ltoe4;
    private final ModelRenderer rarm;
    private final ModelRenderer rhand;
    private final ModelRenderer rclaw1;
    private final ModelRenderer rclaw2;
    private final ModelRenderer rclaw3;
    private final ModelRenderer rclaw4;
    private final ModelRenderer rleg;
    private final ModelRenderer rfoot;
    private final ModelRenderer rtoe1;
    private final ModelRenderer rtoe2;
    private final ModelRenderer rtoe3;
    private final ModelRenderer rtoe4;

    public ModelMolenoid(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 256;
        this.textureHeight = 256;
        this.body = new ModelRenderer(this, 0, 176);
        this.body.addBox(-16.0f, 0.0f, 0.0f, 32, 20, 56);
        this.body.setRotationPoint(0.0f, 1.0f, 6.0f);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
        this.shoulders = new ModelRenderer(this, 0, 143);
        this.shoulders.addBox(-17.0f, 0.0f, 0.0f, 34, 17, 10);
        this.shoulders.setRotationPoint(0.0f, 3.0f, -4.0f);
        this.shoulders.mirror = true;
        this.setRotation(this.shoulders, 0.0f, 0.0f, 0.0f);
        this.head1 = new ModelRenderer(this, 0, 114);
        this.head1.addBox(-14.0f, 0.0f, 0.0f, 28, 14, 10);
        this.head1.setRotationPoint(0.0f, 5.0f, -14.0f);
        this.head1.mirror = true;
        this.setRotation(this.head1, 0.0f, 0.0f, 0.0f);
        this.head2 = new ModelRenderer(this, 0, 89);
        this.head2.addBox(-11.0f, 0.0f, 0.0f, 22, 10, 10);
        this.head2.setRotationPoint(0.0f, 6.0f, -24.0f);
        this.head2.mirror = true;
        this.setRotation(this.head2, 0.0f, 0.0f, 0.0f);
        this.head3 = new ModelRenderer(this, 0, 67);
        this.head3.addBox(-4.0f, 0.0f, 0.0f, 8, 8, 10);
        this.head3.setRotationPoint(0.0f, 7.0f, -34.0f);
        this.head3.mirror = true;
        this.setRotation(this.head3, 0.0f, 0.0f, 0.0f);
        this.nosestar1 = new ModelRenderer(this, 0, 32);
        this.nosestar1.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar1.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar1.mirror = true;
        this.setRotation(this.nosestar1, 0.0f, 0.0f, 0.0f);
        this.nosestar2 = new ModelRenderer(this, 20, 32);
        this.nosestar2.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar2.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar2.mirror = true;
        this.setRotation(this.nosestar2, 0.0f, 0.0f, 1.047198f);
        this.nosestar3 = new ModelRenderer(this, 40, 32);
        this.nosestar3.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar3.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar3.mirror = true;
        this.setRotation(this.nosestar3, 0.0f, 0.0f, -1.047198f);
        this.larm = new ModelRenderer(this, 80, 0);
        this.larm.addBox(0.0f, 0.0f, -2.0f, 17, 11, 5);
        this.larm.setRotationPoint(13.0f, 8.0f, 0.0f);
        this.larm.mirror = true;
        this.setRotation(this.larm, 0.0f, 0.6283185f, 0.0f);
        this.lhand = new ModelRenderer(this, 80, 20);
        this.lhand.addBox(0.0f, 0.0f, -2.0f, 12, 14, 4);
        this.lhand.setRotationPoint(25.0f, 7.0f, -9.0f);
        this.lhand.mirror = true;
        this.setRotation(this.lhand, 0.0f, 0.0f, 0.0f);
        this.lclaw1 = new ModelRenderer(this, 80, 42);
        this.lclaw1.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.lclaw1.setRotationPoint(35.0f, 20.0f, -9.0f);
        this.lclaw1.mirror = true;
        this.setRotation(this.lclaw1, 0.0f, -0.1745329f, 0.0f);
        this.lclaw2 = new ModelRenderer(this, 80, 52);
        this.lclaw2.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.lclaw2.setRotationPoint(35.0f, 15.0f, -9.0f);
        this.lclaw2.mirror = true;
        this.setRotation(this.lclaw2, 0.0f, -0.1745329f, 0.0f);
        this.lclaw3 = new ModelRenderer(this, 80, 62);
        this.lclaw3.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.lclaw3.setRotationPoint(35.0f, 10.0f, -9.0f);
        this.lclaw3.mirror = true;
        this.setRotation(this.lclaw3, 0.0f, -0.1745329f, 0.0f);
        this.lclaw4 = new ModelRenderer(this, 80, 72);
        this.lclaw4.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.lclaw4.setRotationPoint(35.0f, 5.0f, -9.0f);
        this.lclaw4.mirror = true;
        this.setRotation(this.lclaw4, 0.0f, -0.1745329f, 0.0f);
        this.nosestar4 = new ModelRenderer(this, 10, 32);
        this.nosestar4.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar4.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar4.mirror = true;
        this.setRotation(this.nosestar4, 0.0f, 0.0f, 0.5235988f);
        this.nosestar5 = new ModelRenderer(this, 30, 32);
        this.nosestar5.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar5.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar5.mirror = true;
        this.setRotation(this.nosestar5, 0.0f, 0.0f, 1.570796f);
        this.nosestar6 = new ModelRenderer(this, 50, 32);
        this.nosestar6.addBox(-0.5f, -8.0f, 0.0f, 1, 16, 1);
        this.nosestar6.setRotationPoint(0.0f, 11.0f, -35.0f);
        this.nosestar6.mirror = true;
        this.setRotation(this.nosestar6, 0.0f, 0.0f, -0.5235988f);
        this.butt = new ModelRenderer(this, 196, 215);
        this.butt.addBox(-11.0f, 0.0f, 0.0f, 22, 11, 5);
        this.butt.setRotationPoint(0.0f, 6.0f, 62.0f);
        this.butt.mirror = true;
        this.setRotation(this.butt, 0.0f, 0.0f, 0.0f);
        this.tail = new ModelRenderer(this, 196, 200);
        this.tail.addBox(-2.0f, 0.0f, 0.0f, 4, 3, 5);
        this.tail.setRotationPoint(0.0f, 7.0f, 67.0f);
        this.tail.mirror = true;
        this.setRotation(this.tail, 0.0f, 0.0f, 0.0f);
        this.lleg = new ModelRenderer(this, 90, 80);
        this.lleg.addBox(0.0f, 0.0f, -2.0f, 17, 11, 5);
        this.lleg.setRotationPoint(14.0f, 9.0f, 58.0f);
        this.lleg.mirror = true;
        this.setRotation(this.lleg, 0.0f, 0.6283185f, 0.0f);
        this.lfoot = new ModelRenderer(this, 90, 100);
        this.lfoot.addBox(0.0f, 0.0f, -2.0f, 12, 14, 4);
        this.lfoot.setRotationPoint(26.0f, 8.0f, 49.0f);
        this.lfoot.mirror = true;
        this.setRotation(this.lfoot, 0.0f, 0.0f, 0.0f);
        this.ltoe1 = new ModelRenderer(this, 90, 120);
        this.ltoe1.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.ltoe1.setRotationPoint(36.0f, 21.0f, 48.0f);
        this.ltoe1.mirror = true;
        this.setRotation(this.ltoe1, 0.0f, -0.2617994f, 0.0f);
        this.ltoe2 = new ModelRenderer(this, 90, 130);
        this.ltoe2.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.ltoe2.setRotationPoint(36.0f, 16.0f, 48.0f);
        this.ltoe2.mirror = true;
        this.setRotation(this.ltoe2, 0.0f, -0.2617994f, 0.0f);
        this.ltoe3 = new ModelRenderer(this, 90, 140);
        this.ltoe3.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.ltoe3.setRotationPoint(36.0f, 11.0f, 48.0f);
        this.ltoe3.mirror = true;
        this.setRotation(this.ltoe3, 0.0f, -0.2617994f, 0.0f);
        this.ltoe4 = new ModelRenderer(this, 90, 150);
        this.ltoe4.addBox(0.0f, 0.0f, -1.0f, 13, 3, 2);
        this.ltoe4.setRotationPoint(36.0f, 6.0f, 48.0f);
        this.ltoe4.mirror = true;
        this.setRotation(this.ltoe4, 0.0f, -0.2617994f, 0.0f);
        this.rarm = new ModelRenderer(this, 130, 0);
        this.rarm.addBox(-17.0f, 0.0f, -2.0f, 17, 11, 5);
        this.rarm.setRotationPoint(-14.0f, 8.0f, 0.0f);
        this.rarm.mirror = true;
        this.setRotation(this.rarm, 0.0f, -0.6283185f, 0.0f);
        this.rhand = new ModelRenderer(this, 130, 20);
        this.rhand.addBox(-12.0f, 0.0f, -2.0f, 12, 14, 4);
        this.rhand.setRotationPoint(-26.0f, 7.0f, -9.0f);
        this.rhand.mirror = true;
        this.setRotation(this.rhand, 0.0f, 0.0f, 0.0f);
        this.rclaw1 = new ModelRenderer(this, 130, 42);
        this.rclaw1.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rclaw1.setRotationPoint(-36.0f, 20.0f, -9.0f);
        this.rclaw1.mirror = true;
        this.setRotation(this.rclaw1, 0.0f, 0.1745329f, 0.0f);
        this.rclaw2 = new ModelRenderer(this, 130, 52);
        this.rclaw2.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rclaw2.setRotationPoint(-36.0f, 15.0f, -9.0f);
        this.rclaw2.mirror = true;
        this.setRotation(this.rclaw2, 0.0f, 0.1745329f, 0.0f);
        this.rclaw3 = new ModelRenderer(this, 130, 62);
        this.rclaw3.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rclaw3.setRotationPoint(-36.0f, 10.0f, -9.0f);
        this.rclaw3.mirror = true;
        this.setRotation(this.rclaw3, 0.0f, 0.1745329f, 0.0f);
        this.rclaw4 = new ModelRenderer(this, 130, 72);
        this.rclaw4.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rclaw4.setRotationPoint(-36.0f, 5.0f, -9.0f);
        this.rclaw4.mirror = true;
        this.setRotation(this.rclaw4, 0.0f, 0.1745329f, 0.0f);
        this.rleg = new ModelRenderer(this, 150, 80);
        this.rleg.addBox(-17.0f, 0.0f, -2.0f, 17, 11, 5);
        this.rleg.setRotationPoint(-14.0f, 9.0f, 58.0f);
        this.rleg.mirror = true;
        this.setRotation(this.rleg, 0.0f, -0.6283185f, 0.0f);
        this.rfoot = new ModelRenderer(this, 150, 100);
        this.rfoot.addBox(-12.0f, 0.0f, -2.0f, 12, 14, 4);
        this.rfoot.setRotationPoint(-26.0f, 8.0f, 49.0f);
        this.rfoot.mirror = true;
        this.setRotation(this.rfoot, 0.0f, 0.0f, 0.0f);
        this.rtoe1 = new ModelRenderer(this, 150, 120);
        this.rtoe1.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rtoe1.setRotationPoint(-36.0f, 21.0f, 48.0f);
        this.rtoe1.mirror = true;
        this.setRotation(this.rtoe1, 0.0f, 0.2617994f, 0.0f);
        this.rtoe2 = new ModelRenderer(this, 150, 130);
        this.rtoe2.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rtoe2.setRotationPoint(-36.0f, 16.0f, 48.0f);
        this.rtoe2.mirror = true;
        this.setRotation(this.rtoe2, 0.0f, 0.2617994f, 0.0f);
        this.rtoe3 = new ModelRenderer(this, 150, 140);
        this.rtoe3.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rtoe3.setRotationPoint(-36.0f, 11.0f, 48.0f);
        this.rtoe3.mirror = true;
        this.setRotation(this.rtoe3, 0.0f, 0.2617994f, 0.0f);
        this.rtoe4 = new ModelRenderer(this, 150, 150);
        this.rtoe4.addBox(-13.0f, 0.0f, -1.0f, 13, 3, 2);
        this.rtoe4.setRotationPoint(-36.0f, 6.0f, 48.0f);
        this.rtoe4.mirror = true;
        this.setRotation(this.rtoe4, 0.0f, 0.2617994f, 0.0f);
    }

    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        if (frameEntity == null) return;
        Entity entity=frameEntity;
        float f=frameSwing, f1=frameAmount, f2=frameAge, f3=frameYaw, f4=framePitch, f5=0.0625F;
        matrixStack.push();
this.body.setRotationPoint(0.0f, 1.0f, 6.0f);
this.setRotation(this.body, 0.0f, 0.0f, 0.0f);
this.shoulders.setRotationPoint(0.0f, 3.0f, -4.0f);
this.setRotation(this.shoulders, 0.0f, 0.0f, 0.0f);
this.head1.setRotationPoint(0.0f, 5.0f, -14.0f);
this.setRotation(this.head1, 0.0f, 0.0f, 0.0f);
this.head2.setRotationPoint(0.0f, 6.0f, -24.0f);
this.setRotation(this.head2, 0.0f, 0.0f, 0.0f);
this.head3.setRotationPoint(0.0f, 7.0f, -34.0f);
this.setRotation(this.head3, 0.0f, 0.0f, 0.0f);
this.nosestar1.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar1, 0.0f, 0.0f, 0.0f);
this.nosestar2.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar2, 0.0f, 0.0f, 1.047198f);
this.nosestar3.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar3, 0.0f, 0.0f, -1.047198f);
this.larm.setRotationPoint(13.0f, 8.0f, 0.0f);
this.setRotation(this.larm, 0.0f, 0.6283185f, 0.0f);
this.lhand.setRotationPoint(25.0f, 7.0f, -9.0f);
this.setRotation(this.lhand, 0.0f, 0.0f, 0.0f);
this.lclaw1.setRotationPoint(35.0f, 20.0f, -9.0f);
this.setRotation(this.lclaw1, 0.0f, -0.1745329f, 0.0f);
this.lclaw2.setRotationPoint(35.0f, 15.0f, -9.0f);
this.setRotation(this.lclaw2, 0.0f, -0.1745329f, 0.0f);
this.lclaw3.setRotationPoint(35.0f, 10.0f, -9.0f);
this.setRotation(this.lclaw3, 0.0f, -0.1745329f, 0.0f);
this.lclaw4.setRotationPoint(35.0f, 5.0f, -9.0f);
this.setRotation(this.lclaw4, 0.0f, -0.1745329f, 0.0f);
this.nosestar4.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar4, 0.0f, 0.0f, 0.5235988f);
this.nosestar5.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar5, 0.0f, 0.0f, 1.570796f);
this.nosestar6.setRotationPoint(0.0f, 11.0f, -35.0f);
this.setRotation(this.nosestar6, 0.0f, 0.0f, -0.5235988f);
this.butt.setRotationPoint(0.0f, 6.0f, 62.0f);
this.setRotation(this.butt, 0.0f, 0.0f, 0.0f);
this.tail.setRotationPoint(0.0f, 7.0f, 67.0f);
this.setRotation(this.tail, 0.0f, 0.0f, 0.0f);
this.lleg.setRotationPoint(14.0f, 9.0f, 58.0f);
this.setRotation(this.lleg, 0.0f, 0.6283185f, 0.0f);
this.lfoot.setRotationPoint(26.0f, 8.0f, 49.0f);
this.setRotation(this.lfoot, 0.0f, 0.0f, 0.0f);
this.ltoe1.setRotationPoint(36.0f, 21.0f, 48.0f);
this.setRotation(this.ltoe1, 0.0f, -0.2617994f, 0.0f);
this.ltoe2.setRotationPoint(36.0f, 16.0f, 48.0f);
this.setRotation(this.ltoe2, 0.0f, -0.2617994f, 0.0f);
this.ltoe3.setRotationPoint(36.0f, 11.0f, 48.0f);
this.setRotation(this.ltoe3, 0.0f, -0.2617994f, 0.0f);
this.ltoe4.setRotationPoint(36.0f, 6.0f, 48.0f);
this.setRotation(this.ltoe4, 0.0f, -0.2617994f, 0.0f);
this.rarm.setRotationPoint(-14.0f, 8.0f, 0.0f);
this.setRotation(this.rarm, 0.0f, -0.6283185f, 0.0f);
this.rhand.setRotationPoint(-26.0f, 7.0f, -9.0f);
this.setRotation(this.rhand, 0.0f, 0.0f, 0.0f);
this.rclaw1.setRotationPoint(-36.0f, 20.0f, -9.0f);
this.setRotation(this.rclaw1, 0.0f, 0.1745329f, 0.0f);
this.rclaw2.setRotationPoint(-36.0f, 15.0f, -9.0f);
this.setRotation(this.rclaw2, 0.0f, 0.1745329f, 0.0f);
this.rclaw3.setRotationPoint(-36.0f, 10.0f, -9.0f);
this.setRotation(this.rclaw3, 0.0f, 0.1745329f, 0.0f);
this.rclaw4.setRotationPoint(-36.0f, 5.0f, -9.0f);
this.setRotation(this.rclaw4, 0.0f, 0.1745329f, 0.0f);
this.rleg.setRotationPoint(-14.0f, 9.0f, 58.0f);
this.setRotation(this.rleg, 0.0f, -0.6283185f, 0.0f);
this.rfoot.setRotationPoint(-26.0f, 8.0f, 49.0f);
this.setRotation(this.rfoot, 0.0f, 0.0f, 0.0f);
this.rtoe1.setRotationPoint(-36.0f, 21.0f, 48.0f);
this.setRotation(this.rtoe1, 0.0f, 0.2617994f, 0.0f);
this.rtoe2.setRotationPoint(-36.0f, 16.0f, 48.0f);
this.setRotation(this.rtoe2, 0.0f, 0.2617994f, 0.0f);
this.rtoe3.setRotationPoint(-36.0f, 11.0f, 48.0f);
this.setRotation(this.rtoe3, 0.0f, 0.2617994f, 0.0f);
this.rtoe4.setRotationPoint(-36.0f, 6.0f, 48.0f);
this.setRotation(this.rtoe4, 0.0f, 0.2617994f, 0.0f);

        MolenoidEntity.CustomEntity e = (MolenoidEntity.CustomEntity)entity;
        this.legacyAngles(f, f1, f2, f3, f4, f5, entity);
        float newangle = 0.0f;
        newangle = e.getAttacking() != 0 ? MathHelper.cos((float)(f2 * 1.7f * this.wingspeed)) * (float)Math.PI * 0.25f : (f1 > 0.1f ? MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * (float)Math.PI * 0.25f * f1 : 0.0f);
        this.larm.rotateAngleY = newangle + 0.628f;
        this.lhand.rotationPointZ = this.larm.rotationPointZ - (float)Math.sin(this.larm.rotateAngleY) * 15.0f;
        this.lhand.rotationPointX = this.larm.rotationPointX + (float)Math.cos(this.larm.rotateAngleY) * 15.0f;
        this.lhand.rotateAngleY = newangle * 1.25f;
        this.lclaw1.rotationPointZ = this.lhand.rotationPointZ - (float)Math.sin(this.lhand.rotateAngleY) * 10.0f;
        this.lclaw1.rotationPointX = this.lhand.rotationPointX + (float)Math.cos(this.lhand.rotateAngleY) * 10.0f;
        this.lclaw1.rotateAngleY = newangle * 1.5f - 0.174f;
        this.lclaw2.rotationPointZ = this.lclaw1.rotationPointZ;
        this.lclaw2.rotationPointX = this.lclaw1.rotationPointX;
        this.lclaw2.rotateAngleY = this.lclaw1.rotateAngleY;
        this.lclaw3.rotationPointZ = this.lclaw1.rotationPointZ;
        this.lclaw3.rotationPointX = this.lclaw1.rotationPointX;
        this.lclaw3.rotateAngleY = this.lclaw1.rotateAngleY;
        this.lclaw4.rotationPointZ = this.lclaw1.rotationPointZ;
        this.lclaw4.rotationPointX = this.lclaw1.rotationPointX;
        this.lclaw4.rotateAngleY = this.lclaw1.rotateAngleY;
        this.rarm.rotateAngleY = newangle - 0.628f;
        this.rhand.rotationPointZ = this.rarm.rotationPointZ + (float)Math.sin(this.rarm.rotateAngleY) * 15.0f;
        this.rhand.rotationPointX = this.rarm.rotationPointX - (float)Math.cos(this.rarm.rotateAngleY) * 15.0f;
        this.rhand.rotateAngleY = newangle * 1.25f;
        this.rclaw1.rotationPointZ = this.rhand.rotationPointZ + (float)Math.sin(this.rhand.rotateAngleY) * 10.0f;
        this.rclaw1.rotationPointX = this.rhand.rotationPointX - (float)Math.cos(this.rhand.rotateAngleY) * 10.0f;
        this.rclaw1.rotateAngleY = newangle * 1.5f + 0.174f;
        this.rclaw2.rotationPointZ = this.rclaw1.rotationPointZ;
        this.rclaw2.rotationPointX = this.rclaw1.rotationPointX;
        this.rclaw2.rotateAngleY = this.rclaw1.rotateAngleY;
        this.rclaw3.rotationPointZ = this.rclaw1.rotationPointZ;
        this.rclaw3.rotationPointX = this.rclaw1.rotationPointX;
        this.rclaw3.rotateAngleY = this.rclaw1.rotateAngleY;
        this.rclaw4.rotationPointZ = this.rclaw1.rotationPointZ;
        this.rclaw4.rotationPointX = this.rclaw1.rotationPointX;
        this.rclaw4.rotateAngleY = this.rclaw1.rotateAngleY;
        newangle = f1 > 0.1f ? MathHelper.cos((float)(f2 * 1.3f * this.wingspeed)) * (float)Math.PI * 0.25f * f1 : 0.0f;
        this.lleg.rotateAngleY = -newangle + 0.628f;
        this.lfoot.rotationPointZ = this.lleg.rotationPointZ - (float)Math.sin(this.lleg.rotateAngleY) * 15.0f;
        this.lfoot.rotationPointX = this.lleg.rotationPointX + (float)Math.cos(this.lleg.rotateAngleY) * 15.0f;
        this.lfoot.rotateAngleY = -newangle * 1.25f;
        this.ltoe1.rotationPointZ = this.lfoot.rotationPointZ - (float)Math.sin(this.lfoot.rotateAngleY) * 10.0f;
        this.ltoe1.rotationPointX = this.lfoot.rotationPointX + (float)Math.cos(this.lfoot.rotateAngleY) * 10.0f;
        this.ltoe1.rotateAngleY = -newangle * 1.5f - 0.261f;
        this.ltoe2.rotationPointZ = this.ltoe1.rotationPointZ;
        this.ltoe2.rotationPointX = this.ltoe1.rotationPointX;
        this.ltoe2.rotateAngleY = this.ltoe1.rotateAngleY;
        this.ltoe3.rotationPointZ = this.ltoe1.rotationPointZ;
        this.ltoe3.rotationPointX = this.ltoe1.rotationPointX;
        this.ltoe3.rotateAngleY = this.ltoe1.rotateAngleY;
        this.ltoe4.rotationPointZ = this.ltoe1.rotationPointZ;
        this.ltoe4.rotationPointX = this.ltoe1.rotationPointX;
        this.ltoe4.rotateAngleY = this.ltoe1.rotateAngleY;
        this.rleg.rotateAngleY = -newangle - 0.628f;
        this.rfoot.rotationPointZ = this.rleg.rotationPointZ + (float)Math.sin(this.rleg.rotateAngleY) * 15.0f;
        this.rfoot.rotationPointX = this.rleg.rotationPointX - (float)Math.cos(this.rleg.rotateAngleY) * 15.0f;
        this.rfoot.rotateAngleY = -newangle * 1.25f;
        this.rtoe1.rotationPointZ = this.rfoot.rotationPointZ + (float)Math.sin(this.rfoot.rotateAngleY) * 10.0f;
        this.rtoe1.rotationPointX = this.rfoot.rotationPointX - (float)Math.cos(this.rfoot.rotateAngleY) * 10.0f;
        this.rtoe1.rotateAngleY = -newangle * 1.5f + 0.261f;
        this.rtoe2.rotationPointZ = this.rtoe1.rotationPointZ;
        this.rtoe2.rotationPointX = this.rtoe1.rotationPointX;
        this.rtoe2.rotateAngleY = this.rtoe1.rotateAngleY;
        this.rtoe3.rotationPointZ = this.rtoe1.rotationPointZ;
        this.rtoe3.rotationPointX = this.rtoe1.rotationPointX;
        this.rtoe3.rotateAngleY = this.rtoe1.rotateAngleY;
        this.rtoe4.rotationPointZ = this.rtoe1.rotationPointZ;
        this.rtoe4.rotationPointX = this.rtoe1.rotationPointX;
        this.rtoe4.rotateAngleY = this.rtoe1.rotateAngleY;
        this.nosestar1.rotateAngleZ = newangle = MathHelper.cos((float)(f2 * 0.1f * this.wingspeed)) * (float)Math.PI;
        this.nosestar2.rotateAngleZ = newangle + 0.523f;
        this.nosestar3.rotateAngleZ = newangle + 1.047f;
        this.nosestar4.rotateAngleZ = newangle + 1.57f;
        this.nosestar5.rotateAngleZ = newangle - 1.047f;
        this.nosestar6.rotateAngleZ = newangle - 0.523f;
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.shoulders.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.larm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lhand.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.nosestar6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.butt.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lleg.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lfoot.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltoe1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltoe2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltoe3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.ltoe4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rarm.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rhand.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rleg.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rfoot.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtoe1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtoe2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtoe3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rtoe4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    
        matrixStack.pop();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void legacyAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
    }
}


}
