package net.mcreator.xillysorespawn.entity.renderer;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.mcreator.xillysorespawn.entity.PitchBlackEntity;
import net.mcreator.xillysorespawn.entity.OreSpawnLogic;

@OnlyIn(Dist.CLIENT)
public class PitchBlackRenderer {
    private static final String TEXTURE = "xillys_orespawn:textures/entities/pitchblacktexture.png";
    public static class ModelRegisterHandler {
        @SubscribeEvent @OnlyIn(Dist.CLIENT)
        public void registerModels(ModelRegistryEvent event) {
            RenderingRegistry.registerEntityRenderingHandler(PitchBlackEntity.entity, manager ->
                new MobRenderer(manager, new ModelPitchBlack(0.65F), 1.25F) {
                    @Override public ResourceLocation getEntityTexture(Entity entity) { return new ResourceLocation(TEXTURE); }
                    @Override protected void preRenderCallback(LivingEntity entity, MatrixStack stack, float partialTick) {
                        float modelScale = ((PitchBlackEntity.CustomEntity) entity).getPitchBlackScale();
                        stack.scale(modelScale, modelScale, modelScale);
                    }
                });
        }
    }

public static class ModelPitchBlack extends EntityModel<Entity> {
    // Exact legacy render order recovered from bytecode; do not add a second addChild rig.
    private Entity frameEntity;
    private float frameSwing, frameAmount, frameAge, frameYaw, framePitch;
    @Override public void setRotationAngles(Entity entity, float swing, float amount, float age, float yaw, float pitch) {
        frameEntity=entity; frameSwing=swing; frameAmount=amount; frameAge=age; frameYaw=yaw; framePitch=pitch;
    }

    private float wingspeed = 1.0f;
    private final ModelRenderer lclaw1;
    private final ModelRenderer body;
    private final ModelRenderer leftleg1;
    private final ModelRenderer tail1;
    private final ModelRenderer leftleg2;
    private final ModelRenderer body2;
    private final ModelRenderer leftleg3;
    private final ModelRenderer tail2;
    private final ModelRenderer tail3;
    private final ModelRenderer lclaw2;
    private final ModelRenderer lclaw3;
    private final ModelRenderer lclaw4;
    private final ModelRenderer lclaw5;
    private final ModelRenderer lclaw6;
    private final ModelRenderer lclaw7;
    private final ModelRenderer tail4;
    private final ModelRenderer tail5;
    private final ModelRenderer tail6;
    private final ModelRenderer tail7;
    private final ModelRenderer tail8;
    private final ModelRenderer tail9;
    private final ModelRenderer tailpoint1;
    private final ModelRenderer tailpoint2;
    private final ModelRenderer llegspike;
    private final ModelRenderer tailspike1;
    private final ModelRenderer tailspike2;
    private final ModelRenderer tailspike3;
    private final ModelRenderer tailspike4;
    private final ModelRenderer tailspike5;
    private final ModelRenderer tailspike6;
    private final ModelRenderer neck1;
    private final ModelRenderer neck2;
    private final ModelRenderer neck3;
    private final ModelRenderer head1;
    private final ModelRenderer leye;
    private final ModelRenderer reye;
    private final ModelRenderer head2;
    private final ModelRenderer head3;
    private final ModelRenderer head4;
    private final ModelRenderer head5;
    private final ModelRenderer head6;
    private final ModelRenderer jaw1;
    private final ModelRenderer jaw2;
    private final ModelRenderer jaw3;
    private final ModelRenderer jaw4;
    private final ModelRenderer tooth1;
    private final ModelRenderer tooth2;
    private final ModelRenderer tooth3;
    private final ModelRenderer tooth4;
    private final ModelRenderer tooth5;
    private final ModelRenderer jaw5;
    private final ModelRenderer head7;
    private final ModelRenderer tooth6;
    private final ModelRenderer tooth7;
    private final ModelRenderer tooth8;
    private final ModelRenderer tooth9;
    private final ModelRenderer tooth10;
    private final ModelRenderer tooth11;
    private final ModelRenderer tooth12;
    private final ModelRenderer tooth13;
    private final ModelRenderer rightleg1;
    private final ModelRenderer rightleg2;
    private final ModelRenderer tooth14;
    private final ModelRenderer tooth15;
    private final ModelRenderer tooth16;
    private final ModelRenderer tooth17;
    private final ModelRenderer tooth18;
    private final ModelRenderer tooth19;
    private final ModelRenderer tooth20;
    private final ModelRenderer tooth21;
    private final ModelRenderer tooth22;
    private final ModelRenderer tooth23;
    private final ModelRenderer rightleg3;
    private final ModelRenderer llegspike2;
    private final ModelRenderer rclaw2;
    private final ModelRenderer rclaw4;
    private final ModelRenderer rclaw1;
    private final ModelRenderer rclaw5;
    private final ModelRenderer rclaw7;
    private final ModelRenderer rclaw3;
    private final ModelRenderer rclaw6;
    private final ModelRenderer wing1;
    private final ModelRenderer wing2;
    private final ModelRenderer wing3;
    private final ModelRenderer mem1;
    private final ModelRenderer mem2;
    private final ModelRenderer mem3;
    private final ModelRenderer wingclaw1;
    private final ModelRenderer wingclaw2;
    private final ModelRenderer wingclaw3;
    private final ModelRenderer lshoulder;
    private final ModelRenderer rshoulder;
    private final ModelRenderer rwing1;
    private final ModelRenderer rmem1;
    private final ModelRenderer rwing2;
    private final ModelRenderer rmem2;
    private final ModelRenderer rwing3;
    private final ModelRenderer rmem3;
    private final ModelRenderer rwingclaw1;
    private final ModelRenderer rwingclaw2;
    private final ModelRenderer rwingclaw3;

    public ModelPitchBlack(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 512;
        this.textureHeight = 256;
        this.lclaw1 = new ModelRenderer(this, 300, 111);
        this.lclaw1.addBox(-3.0f, 0.0f, -3.0f, 2, 3, 6);
        this.lclaw1.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw1.mirror = true;
        this.setRotation(this.lclaw1, 0.0f, 0.6632251f, 0.0f);
        this.body = new ModelRenderer(this, 400, 26);
        this.body.addBox(-6.0f, -12.0f, -9.0f, 12, 12, 9);
        this.body.setRotationPoint(0.0f, 0.0f, 9.0f);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0698132f, 0.0f, 0.0f);
        this.leftleg1 = new ModelRenderer(this, 300, 10);
        this.leftleg1.addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10);
        this.leftleg1.setRotationPoint(7.0f, 5.0f, 23.0f);
        this.leftleg1.mirror = true;
        this.setRotation(this.leftleg1, -0.5759587f, 0.0f, 0.0f);
        this.tail1 = new ModelRenderer(this, 400, 82);
        this.tail1.addBox(-5.0f, -6.0f, 0.0f, 8, 10, 12);
        this.tail1.setRotationPoint(1.0f, -3.0f, 22.0f);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, -0.1745329f, 0.0f, 0.0f);
        this.leftleg2 = new ModelRenderer(this, 300, 31);
        this.leftleg2.addBox(-1.0f, -10.0f, -4.0f, 4, 12, 5);
        this.leftleg2.setRotationPoint(7.0f, 5.0f, 23.0f);
        this.leftleg2.mirror = true;
        this.setRotation(this.leftleg2, 0.9773844f, 0.0f, 0.0f);
        this.body2 = new ModelRenderer(this, 400, 50);
        this.body2.addBox(0.0f, -3.0f, -3.0f, 12, 14, 16);
        this.body2.setRotationPoint(-6.0f, -9.0f, 10.0f);
        this.body2.mirror = true;
        this.setRotation(this.body2, -0.1047198f, 0.0f, 0.0f);
        this.leftleg3 = new ModelRenderer(this, 300, 51);
        this.leftleg3.addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4);
        this.leftleg3.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.leftleg3.mirror = true;
        this.setRotation(this.leftleg3, -0.5235988f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer(this, 400, 106);
        this.tail2.addBox(-3.0f, -4.0f, 0.0f, 6, 8, 10);
        this.tail2.setRotationPoint(0.0f, -2.0f, 33.0f);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, -0.1396263f, 0.0f, 0.0f);
        this.tail3 = new ModelRenderer(this, 400, 126);
        this.tail3.addBox(-2.0f, -2.0f, 0.0f, 4, 5, 10);
        this.tail3.setRotationPoint(0.0f, -1.0f, 42.0f);
        this.tail3.mirror = true;
        this.setRotation(this.tail3, -0.1396263f, 0.0f, 0.0f);
        this.lclaw2 = new ModelRenderer(this, 300, 76);
        this.lclaw2.addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13);
        this.lclaw2.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw2.mirror = true;
        this.setRotation(this.lclaw2, 0.0f, 0.0f, 0.0f);
        this.lclaw3 = new ModelRenderer(this, 300, 95);
        this.lclaw3.addBox(2.0f, 0.0f, -6.0f, 2, 3, 10);
        this.lclaw3.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw3.mirror = true;
        this.setRotation(this.lclaw3, 0.0f, -0.6632251f, 0.0f);
        this.lclaw4 = new ModelRenderer(this, 310, 123);
        this.lclaw4.addBox(0.0f, 1.0f, -9.0f, 1, 2, 3);
        this.lclaw4.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw4.mirror = true;
        this.setRotation(this.lclaw4, 0.0f, 0.0f, 0.0f);
        this.lclaw5 = new ModelRenderer(this, 300, 123);
        this.lclaw5.addBox(-2.5f, 1.0f, -5.0f, 1, 2, 2);
        this.lclaw5.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw5.mirror = true;
        this.setRotation(this.lclaw5, 0.0f, 0.6632251f, 0.0f);
        this.lclaw6 = new ModelRenderer(this, 322, 123);
        this.lclaw6.addBox(2.5f, 1.0f, -9.0f, 1, 2, 3);
        this.lclaw6.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw6.mirror = true;
        this.setRotation(this.lclaw6, 0.0f, -0.6632251f, 0.0f);
        this.lclaw7 = new ModelRenderer(this, 333, 123);
        this.lclaw7.addBox(0.0f, 1.0f, 7.0f, 1, 2, 3);
        this.lclaw7.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.lclaw7.mirror = true;
        this.setRotation(this.lclaw7, 0.0f, 0.0f, 0.0f);
        this.tail4 = new ModelRenderer(this, 400, 143);
        this.tail4.addBox(-2.0f, -2.0f, 0.0f, 4, 4, 10);
        this.tail4.setRotationPoint(0.0f, 0.0f, 51.0f);
        this.tail4.mirror = true;
        this.setRotation(this.tail4, -0.1396263f, 0.0f, 0.0f);
        this.tail5 = new ModelRenderer(this, 400, 159);
        this.tail5.addBox(-1.5f, -2.0f, 0.0f, 3, 3, 10);
        this.tail5.setRotationPoint(0.0f, 1.0f, 59.0f);
        this.tail5.mirror = true;
        this.setRotation(this.tail5, -0.1396263f, 0.0f, 0.0f);
        this.tail6 = new ModelRenderer(this, 400, 180);
        this.tail6.addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail6.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tail6.mirror = true;
        this.setRotation(this.tail6, -0.1396263f, 0.1745329f, 0.0f);
        this.tail7 = new ModelRenderer(this, 400, 180);
        this.tail7.addBox(-2.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail7.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tail7.mirror = true;
        this.setRotation(this.tail7, -0.1396263f, -0.1745329f, 0.0f);
        this.tail8 = new ModelRenderer(this, 400, 180);
        this.tail8.addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail8.setRotationPoint(-4.0f, 1.0f, 77.0f);
        this.tail8.mirror = true;
        this.setRotation(this.tail8, -0.1396263f, -0.1745329f, 0.0f);
        this.tail9 = new ModelRenderer(this, 400, 180);
        this.tail9.addBox(0.0f, 0.0f, 0.0f, 2, 2, 10);
        this.tail9.setRotationPoint(2.0f, 1.0f, 77.0f);
        this.tail9.mirror = true;
        this.setRotation(this.tail9, -0.1396263f, 0.1745329f, 0.0f);
        this.tailpoint1 = new ModelRenderer(this, 400, 200);
        this.tailpoint1.addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22);
        this.tailpoint1.setRotationPoint(5.0f, 3.0f, 85.0f);
        this.tailpoint1.mirror = true;
        this.setRotation(this.tailpoint1, -0.1919862f, 0.1745329f, 0.0f);
        this.tailpoint2 = new ModelRenderer(this, 400, 200);
        this.tailpoint2.addBox(-1.0f, -1.0f, 0.0f, 1, 1, 22);
        this.tailpoint2.setRotationPoint(-4.0f, 3.0f, 86.0f);
        this.tailpoint2.mirror = true;
        this.setRotation(this.tailpoint2, -0.1919862f, -0.1745329f, 0.0f);
        this.llegspike = new ModelRenderer(this, 300, 131);
        this.llegspike.addBox(0.0f, -28.0f, 1.0f, 1, 12, 1);
        this.llegspike.setRotationPoint(7.0f, 21.0f, 11.0f);
        this.llegspike.mirror = true;
        this.setRotation(this.llegspike, -0.6981317f, 0.0f, 0.0f);
        this.tailspike1 = new ModelRenderer(this, 400, 230);
        this.tailspike1.addBox(1.0f, -1.0f, 0.0f, 1, 1, 1);
        this.tailspike1.setRotationPoint(2.0f, 1.0f, 77.0f);
        this.tailspike1.mirror = true;
        this.setRotation(this.tailspike1, -0.1396263f, 0.1745329f, 0.0f);
        this.tailspike2 = new ModelRenderer(this, 400, 230);
        this.tailspike2.addBox(1.0f, -1.0f, 6.0f, 1, 1, 1);
        this.tailspike2.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike2.mirror = true;
        this.setRotation(this.tailspike2, -0.1396263f, 0.1745329f, 0.0f);
        this.tailspike3 = new ModelRenderer(this, 400, 230);
        this.tailspike3.addBox(1.0f, -1.0f, 2.0f, 1, 1, 1);
        this.tailspike3.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike3.mirror = true;
        this.setRotation(this.tailspike3, -0.1396263f, 0.1745329f, 0.0f);
        this.tailspike4 = new ModelRenderer(this, 400, 230);
        this.tailspike4.addBox(0.0f, -1.0f, 0.0f, 1, 1, 1);
        this.tailspike4.setRotationPoint(-4.0f, 1.0f, 77.0f);
        this.tailspike4.mirror = true;
        this.setRotation(this.tailspike4, -0.1396263f, -0.1745329f, 0.0f);
        this.tailspike5 = new ModelRenderer(this, 400, 230);
        this.tailspike5.addBox(-2.0f, -1.0f, 6.0f, 1, 1, 1);
        this.tailspike5.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike5.mirror = true;
        this.setRotation(this.tailspike5, -0.1396263f, -0.1745329f, 0.0f);
        this.tailspike6 = new ModelRenderer(this, 400, 230);
        this.tailspike6.addBox(-2.0f, -1.0f, 2.0f, 1, 1, 1);
        this.tailspike6.setRotationPoint(0.0f, 0.0f, 68.0f);
        this.tailspike6.mirror = true;
        this.setRotation(this.tailspike6, -0.1396263f, -0.1745329f, 0.0f);
        this.neck1 = new ModelRenderer(this, 400, 7);
        this.neck1.addBox(-4.0f, -4.0f, 0.0f, 8, 8, 8);
        this.neck1.setRotationPoint(0.0f, -4.0f, -5.0f);
        this.neck1.mirror = true;
        this.setRotation(this.neck1, 0.0872665f, 0.0f, 0.0f);
        this.neck2 = new ModelRenderer(this, 375, 10);
        this.neck2.addBox(-3.0f, -3.0f, -3.0f, 6, 6, 4);
        this.neck2.setRotationPoint(0.0f, -4.0f, -5.0f);
        this.neck2.mirror = true;
        this.setRotation(this.neck2, -0.0523599f, 0.0f, 0.0f);
        this.neck3 = new ModelRenderer(this, 375, 23);
        this.neck3.addBox(-2.0f, -2.0f, -6.0f, 4, 4, 8);
        this.neck3.setRotationPoint(0.0f, -4.0f, -9.0f);
        this.neck3.mirror = true;
        this.setRotation(this.neck3, -0.2443461f, 0.0f, 0.0f);
        this.head1 = new ModelRenderer(this, 123, 3);
        this.head1.addBox(-18.0f, -1.0f, -12.0f, 36, 1, 12);
        this.head1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head1.mirror = true;
        this.setRotation(this.head1, -0.2443461f, 0.0f, 0.0f);
        this.leye = new ModelRenderer(this, 76, 2);
        this.leye.addBox(18.0f, -1.0f, -13.0f, 3, 3, 15);
        this.leye.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.leye.mirror = true;
        this.setRotation(this.leye, -0.2443461f, 0.0f, 0.0f);
        this.reye = new ModelRenderer(this, 32, 2);
        this.reye.addBox(-21.0f, -1.0f, -13.0f, 3, 3, 15);
        this.reye.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.reye.mirror = true;
        this.setRotation(this.reye, -0.2443461f, 0.0f, 0.0f);
        this.head2 = new ModelRenderer(this, 140, 18);
        this.head2.addBox(-8.0f, -2.0f, -11.0f, 16, 1, 11);
        this.head2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head2.mirror = true;
        this.setRotation(this.head2, -0.2443461f, 0.0f, 0.0f);
        this.head3 = new ModelRenderer(this, 143, 32);
        this.head3.addBox(-2.0f, -4.0f, -14.0f, 4, 4, 16);
        this.head3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head3.mirror = true;
        this.setRotation(this.head3, -0.2443461f, 0.0f, 0.0f);
        this.head4 = new ModelRenderer(this, 152, 55);
        this.head4.addBox(-1.0f, -10.0f, -13.0f, 2, 8, 12);
        this.head4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head4.mirror = true;
        this.setRotation(this.head4, -0.3665191f, 0.0f, 0.0f);
        this.head5 = new ModelRenderer(this, 154, 77);
        this.head5.addBox(-0.5f, -18.0f, -11.0f, 1, 9, 9);
        this.head5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head5.mirror = true;
        this.setRotation(this.head5, -0.4363323f, 0.0f, 0.0f);
        this.head6 = new ModelRenderer(this, 160, 97);
        this.head6.addBox(-0.5f, -24.0f, -10.0f, 1, 8, 4);
        this.head6.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head6.mirror = true;
        this.setRotation(this.head6, -0.6632251f, 0.0f, 0.0f);
        this.jaw1 = new ModelRenderer(this, 143, 114);
        this.jaw1.addBox(-2.0f, 1.0f, -14.0f, 4, 4, 15);
        this.jaw1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw1.mirror = true;
        this.setRotation(this.jaw1, 0.1919862f, 0.0f, 0.0f);
        this.jaw2 = new ModelRenderer(this, 150, 149);
        this.jaw2.addBox(-1.0f, 4.0f, -12.0f, 2, 5, 11);
        this.jaw2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw2.mirror = true;
        this.setRotation(this.jaw2, 0.2617994f, 0.0f, 0.0f);
        this.jaw3 = new ModelRenderer(this, 154, 168);
        this.jaw3.addBox(-0.5f, 8.0f, -10.0f, 1, 4, 8);
        this.jaw3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw3.mirror = true;
        this.setRotation(this.jaw3, 0.3316126f, 0.0f, 0.0f);
        this.jaw4 = new ModelRenderer(this, 158, 182);
        this.jaw4.addBox(-0.5f, 11.0f, -7.0f, 1, 4, 4);
        this.jaw4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw4.mirror = true;
        this.setRotation(this.jaw4, 0.4014257f, 0.0f, 0.0f);
        this.tooth1 = new ModelRenderer(this, 0, 0);
        this.tooth1.addBox(-2.0f, 0.0f, -14.0f, 1, 3, 1);
        this.tooth1.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth1.mirror = true;
        this.setRotation(this.tooth1, -0.2443461f, 0.0f, 0.0f);
        this.tooth2 = new ModelRenderer(this, 0, 0);
        this.tooth2.addBox(-0.5f, 0.0f, -14.0f, 1, 2, 1);
        this.tooth2.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth2.mirror = true;
        this.setRotation(this.tooth2, -0.2443461f, 0.0f, 0.0f);
        this.tooth3 = new ModelRenderer(this, 0, 0);
        this.tooth3.addBox(1.0f, 0.0f, -14.0f, 1, 3, 1);
        this.tooth3.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth3.mirror = true;
        this.setRotation(this.tooth3, -0.2443461f, 0.0f, 0.0f);
        this.tooth4 = new ModelRenderer(this, 0, 0);
        this.tooth4.addBox(-2.0f, 0.0f, -12.0f, 1, 3, 1);
        this.tooth4.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth4.mirror = true;
        this.setRotation(this.tooth4, -0.2443461f, 0.0f, 0.0f);
        this.tooth5 = new ModelRenderer(this, 0, 0);
        this.tooth5.addBox(1.0f, 0.0f, -12.0f, 1, 3, 1);
        this.tooth5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth5.mirror = true;
        this.setRotation(this.tooth5, -0.2443461f, 0.0f, 0.0f);
        this.jaw5 = new ModelRenderer(this, 151, 135);
        this.jaw5.addBox(-3.0f, 1.0f, -4.0f, 6, 5, 7);
        this.jaw5.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.jaw5.mirror = true;
        this.setRotation(this.jaw5, 0.1919862f, 0.0f, 0.0f);
        this.head7 = new ModelRenderer(this, 185, 34);
        this.head7.addBox(-3.0f, -5.0f, -3.0f, 6, 5, 7);
        this.head7.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.head7.mirror = true;
        this.setRotation(this.head7, -0.2443461f, 0.0f, 0.0f);
        this.tooth6 = new ModelRenderer(this, 0, 0);
        this.tooth6.addBox(-2.0f, 0.0f, -10.0f, 1, 2, 1);
        this.tooth6.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth6.mirror = true;
        this.setRotation(this.tooth6, -0.2443461f, 0.0f, 0.0f);
        this.tooth7 = new ModelRenderer(this, 0, 0);
        this.tooth7.addBox(1.0f, 0.0f, -10.0f, 1, 2, 1);
        this.tooth7.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth7.mirror = true;
        this.setRotation(this.tooth7, -0.2443461f, 0.0f, 0.0f);
        this.tooth8 = new ModelRenderer(this, 0, 0);
        this.tooth8.addBox(-2.0f, 0.0f, -8.0f, 1, 2, 1);
        this.tooth8.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth8.mirror = true;
        this.setRotation(this.tooth8, -0.2443461f, 0.0f, 0.0f);
        this.tooth9 = new ModelRenderer(this, 0, 0);
        this.tooth9.addBox(1.0f, 0.0f, -8.0f, 1, 2, 1);
        this.tooth9.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth9.mirror = true;
        this.setRotation(this.tooth9, -0.2443461f, 0.0f, 0.0f);
        this.tooth10 = new ModelRenderer(this, 0, 0);
        this.tooth10.addBox(-2.0f, 0.0f, -6.0f, 1, 2, 1);
        this.tooth10.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth10.mirror = true;
        this.setRotation(this.tooth10, -0.2443461f, 0.0f, 0.0f);
        this.tooth11 = new ModelRenderer(this, 0, 0);
        this.tooth11.addBox(1.0f, 0.0f, -6.0f, 1, 2, 1);
        this.tooth11.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth11.mirror = true;
        this.setRotation(this.tooth11, -0.2443461f, 0.0f, 0.0f);
        this.tooth12 = new ModelRenderer(this, 0, 0);
        this.tooth12.addBox(-2.0f, 0.0f, -4.0f, 1, 1, 1);
        this.tooth12.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth12.mirror = true;
        this.setRotation(this.tooth12, -0.2443461f, 0.0f, 0.0f);
        this.tooth13 = new ModelRenderer(this, -1, 0);
        this.tooth13.addBox(1.0f, 0.0f, -4.0f, 1, 1, 1);
        this.tooth13.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth13.mirror = true;
        this.setRotation(this.tooth13, -0.2443461f, 0.0f, 0.0f);
        this.rightleg1 = new ModelRenderer(this, 250, 10);
        this.rightleg1.addBox(-1.0f, -5.0f, -20.0f, 5, 10, 10);
        this.rightleg1.setRotationPoint(-10.0f, 5.0f, 23.0f);
        this.rightleg1.mirror = true;
        this.setRotation(this.rightleg1, -0.5934119f, 0.0f, 0.0f);
        this.rightleg2 = new ModelRenderer(this, 250, 32);
        this.rightleg2.addBox(0.0f, -10.0f, -4.0f, 4, 12, 5);
        this.rightleg2.setRotationPoint(-10.0f, 5.0f, 23.0f);
        this.rightleg2.mirror = true;
        this.setRotation(this.rightleg2, 0.9773844f, 0.0f, 0.0f);
        this.tooth14 = new ModelRenderer(this, 0, 0);
        this.tooth14.addBox(0.5f, -2.0f, -14.0f, 1, 3, 1);
        this.tooth14.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth14.mirror = true;
        this.setRotation(this.tooth14, 0.1919862f, 0.0f, 0.0f);
        this.tooth15 = new ModelRenderer(this, 0, 0);
        this.tooth15.addBox(-1.5f, -2.0f, -14.0f, 1, 3, 1);
        this.tooth15.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth15.mirror = true;
        this.setRotation(this.tooth15, 0.1919862f, 0.0f, 0.0f);
        this.tooth16 = new ModelRenderer(this, 0, 0);
        this.tooth16.addBox(1.0f, -1.0f, -12.0f, 1, 2, 1);
        this.tooth16.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth16.mirror = true;
        this.setRotation(this.tooth16, 0.1919862f, 0.0f, 0.0f);
        this.tooth17 = new ModelRenderer(this, 0, 0);
        this.tooth17.addBox(-2.0f, -1.0f, -12.0f, 1, 2, 1);
        this.tooth17.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth17.mirror = true;
        this.setRotation(this.tooth17, 0.1919862f, 0.0f, 0.0f);
        this.tooth18 = new ModelRenderer(this, 0, 0);
        this.tooth18.addBox(1.0f, -1.0f, -10.0f, 1, 2, 1);
        this.tooth18.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth18.mirror = true;
        this.setRotation(this.tooth18, 0.1919862f, 0.0f, 0.0f);
        this.tooth19 = new ModelRenderer(this, 0, 0);
        this.tooth19.addBox(-2.0f, -1.0f, -10.0f, 1, 2, 1);
        this.tooth19.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth19.mirror = true;
        this.setRotation(this.tooth19, 0.1919862f, 0.0f, 0.0f);
        this.tooth20 = new ModelRenderer(this, 0, 0);
        this.tooth20.addBox(-2.0f, -1.0f, -8.0f, 1, 2, 1);
        this.tooth20.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth20.mirror = true;
        this.setRotation(this.tooth20, 0.1919862f, 0.0f, 0.0f);
        this.tooth21 = new ModelRenderer(this, 0, 0);
        this.tooth21.addBox(1.0f, -1.0f, -8.0f, 1, 2, 1);
        this.tooth21.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth21.mirror = true;
        this.setRotation(this.tooth21, 0.1919862f, 0.0f, 0.0f);
        this.tooth22 = new ModelRenderer(this, 0, 0);
        this.tooth22.addBox(1.0f, 0.0f, -6.0f, 1, 1, 1);
        this.tooth22.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth22.mirror = true;
        this.setRotation(this.tooth22, 0.1919862f, 0.0f, 0.0f);
        this.tooth23 = new ModelRenderer(this, 0, 0);
        this.tooth23.addBox(-2.0f, 0.0f, -6.0f, 1, 1, 1);
        this.tooth23.setRotationPoint(0.0f, -6.0f, -14.0f);
        this.tooth23.mirror = true;
        this.setRotation(this.tooth23, 0.1919862f, 0.0f, 0.0f);
        this.rightleg3 = new ModelRenderer(this, 250, 52);
        this.rightleg3.addBox(-1.0f, -19.0f, 1.0f, 3, 18, 4);
        this.rightleg3.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rightleg3.mirror = true;
        this.setRotation(this.rightleg3, -0.5235988f, 0.0f, 0.0f);
        this.llegspike2 = new ModelRenderer(this, 250, 130);
        this.llegspike2.addBox(0.0f, -28.0f, 1.0f, 1, 12, 1);
        this.llegspike2.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.llegspike2.mirror = true;
        this.setRotation(this.llegspike2, -0.6981317f, 0.0f, 0.0f);
        this.rclaw2 = new ModelRenderer(this, 250, 76);
        this.rclaw2.addBox(-1.0f, -1.0f, -6.0f, 3, 4, 13);
        this.rclaw2.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw2.mirror = true;
        this.setRotation(this.rclaw2, 0.0f, 0.0f, 0.0f);
        this.rclaw4 = new ModelRenderer(this, 250, 123);
        this.rclaw4.addBox(0.0f, 1.0f, -9.0f, 1, 2, 3);
        this.rclaw4.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw4.mirror = true;
        this.setRotation(this.rclaw4, 0.0f, 0.0f, 0.0f);
        this.rclaw1 = new ModelRenderer(this, 250, 111);
        this.rclaw1.addBox(2.0f, 0.0f, -4.0f, 2, 3, 6);
        this.rclaw1.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw1.mirror = true;
        this.setRotation(this.rclaw1, 0.0f, -0.6632251f, 0.0f);
        this.rclaw5 = new ModelRenderer(this, 261, 123);
        this.rclaw5.addBox(2.5f, 1.0f, -6.0f, 1, 2, 2);
        this.rclaw5.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw5.mirror = true;
        this.setRotation(this.rclaw5, 0.0f, -0.6632251f, 0.0f);
        this.rclaw7 = new ModelRenderer(this, 283, 123);
        this.rclaw7.addBox(0.0f, 1.0f, 7.0f, 1, 2, 3);
        this.rclaw7.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw7.mirror = true;
        this.setRotation(this.rclaw7, 0.0f, 0.0f, 0.0f);
        this.rclaw3 = new ModelRenderer(this, 250, 95);
        this.rclaw3.addBox(-3.0f, 0.0f, -6.0f, 2, 3, 10);
        this.rclaw3.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw3.mirror = true;
        this.setRotation(this.rclaw3, 0.0f, 0.6632251f, 0.0f);
        this.rclaw6 = new ModelRenderer(this, 270, 123);
        this.rclaw6.addBox(-2.5f, 1.0f, -9.0f, 1, 2, 3);
        this.rclaw6.setRotationPoint(-8.0f, 21.0f, 11.0f);
        this.rclaw6.mirror = true;
        this.setRotation(this.rclaw6, 0.0f, 0.6632251f, 0.0f);
        this.wing1 = new ModelRenderer(this, 10, 30);
        this.wing1.addBox(-1.0f, -1.0f, -1.0f, 23, 3, 3);
        this.wing1.setRotationPoint(6.0f, -12.0f, 3.0f);
        this.wing1.mirror = true;
        this.setRotation(this.wing1, 0.0f, 0.0872665f, -0.1396263f);
        this.wing2 = new ModelRenderer(this, 10, 40);
        this.wing2.addBox(-1.0f, -1.0f, -1.0f, 44, 2, 2);
        this.wing2.setRotationPoint(27.0f, -15.0f, 1.0f);
        this.wing2.mirror = true;
        this.setRotation(this.wing2, 0.0f, 0.0f, 0.0f);
        this.wing3 = new ModelRenderer(this, 10, 50);
        this.wing3.addBox(-1.0f, -1.0f, -1.0f, 23, 2, 2);
        this.wing3.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wing3.mirror = true;
        this.setRotation(this.wing3, 0.0f, -0.0872665f, 0.1745329f);
        this.mem1 = new ModelRenderer(this, 10, 60);
        this.mem1.addBox(-2.0f, 0.0f, 0.0f, 24, 1, 21);
        this.mem1.setRotationPoint(6.0f, -12.0f, 3.0f);
        this.mem1.mirror = true;
        this.setRotation(this.mem1, 0.0f, 0.0872665f, -0.1396263f);
        this.mem2 = new ModelRenderer(this, 10, 85);
        this.mem2.addBox(0.0f, 0.0f, 0.0f, 43, 1, 21);
        this.mem2.setRotationPoint(27.0f, -15.0f, 1.0f);
        this.mem2.mirror = true;
        this.setRotation(this.mem2, 0.0f, 0.0f, 0.0f);
        this.mem3 = new ModelRenderer(this, 10, 110);
        this.mem3.addBox(0.0f, 0.0f, 0.0f, 23, 1, 21);
        this.mem3.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.mem3.mirror = true;
        this.setRotation(this.mem3, 0.0f, -0.0872665f, 0.1745329f);
        this.wingclaw1 = new ModelRenderer(this, 85, 49);
        this.wingclaw1.addBox(0.0f, 0.0f, -9.0f, 1, 1, 8);
        this.wingclaw1.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wingclaw1.mirror = true;
        this.setRotation(this.wingclaw1, 0.0f, 0.0f, 0.0f);
        this.wingclaw2 = new ModelRenderer(this, 67, 50);
        this.wingclaw2.addBox(0.0f, 0.0f, -7.0f, 1, 1, 6);
        this.wingclaw2.setRotationPoint(70.0f, -15.0f, 1.0f);
        this.wingclaw2.mirror = true;
        this.setRotation(this.wingclaw2, 0.0f, 0.6108652f, 0.0f);
        this.wingclaw3 = new ModelRenderer(this, 106, 50);
        this.wingclaw3.addBox(1.0f, 0.0f, -7.0f, 1, 1, 5);
        this.wingclaw3.setRotationPoint(69.0f, -15.0f, 1.0f);
        this.wingclaw3.mirror = true;
        this.setRotation(this.wingclaw3, 0.0f, -0.6108652f, 0.0f);
        this.lshoulder = new ModelRenderer(this, 370, 40);
        this.lshoulder.addBox(0.0f, 0.0f, 0.0f, 3, 2, 6);
        this.lshoulder.setRotationPoint(3.0f, -13.0f, 1.0f);
        this.lshoulder.mirror = true;
        this.setRotation(this.lshoulder, 0.0698132f, 0.0f, 0.0f);
        this.rshoulder = new ModelRenderer(this, 370, 50);
        this.rshoulder.addBox(0.0f, 0.0f, 0.0f, 3, 2, 6);
        this.rshoulder.setRotationPoint(-6.0f, -13.0f, 1.0f);
        this.rshoulder.mirror = true;
        this.setRotation(this.rshoulder, 0.0698132f, 0.0f, 0.0f);
        this.rwing1 = new ModelRenderer(this, 10, 140);
        this.rwing1.addBox(-22.0f, -1.0f, -1.0f, 23, 3, 3);
        this.rwing1.setRotationPoint(-6.0f, -12.0f, 3.0f);
        this.rwing1.mirror = true;
        this.setRotation(this.rwing1, 0.0f, -0.0872665f, 0.1396263f);
        this.rmem1 = new ModelRenderer(this, 10, 170);
        this.rmem1.addBox(-22.0f, 0.0f, 0.0f, 24, 1, 21);
        this.rmem1.setRotationPoint(-6.0f, -12.0f, 3.0f);
        this.rmem1.mirror = true;
        this.setRotation(this.rmem1, 0.0f, -0.0872665f, 0.1396263f);
        this.rwing2 = new ModelRenderer(this, 10, 150);
        this.rwing2.addBox(-43.0f, -1.0f, -1.0f, 44, 2, 2);
        this.rwing2.setRotationPoint(-27.0f, -15.0f, 1.0f);
        this.rwing2.mirror = true;
        this.setRotation(this.rwing2, 0.0f, 0.0f, 0.0f);
        this.rmem2 = new ModelRenderer(this, 10, 195);
        this.rmem2.addBox(-43.0f, 0.0f, 0.0f, 43, 1, 21);
        this.rmem2.setRotationPoint(-27.0f, -15.0f, 1.0f);
        this.rmem2.mirror = true;
        this.setRotation(this.rmem2, 0.0f, 0.0f, 0.0f);
        this.rwing3 = new ModelRenderer(this, 10, 160);
        this.rwing3.addBox(-22.0f, -1.0f, -1.0f, 23, 2, 2);
        this.rwing3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwing3.mirror = true;
        this.setRotation(this.rwing3, 0.0f, 0.0872665f, -0.1745329f);
        this.rmem3 = new ModelRenderer(this, 10, 220);
        this.rmem3.addBox(-23.0f, 0.0f, 0.0f, 23, 1, 21);
        this.rmem3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rmem3.mirror = true;
        this.setRotation(this.rmem3, 0.0f, 0.0872665f, -0.1745329f);
        this.rwingclaw1 = new ModelRenderer(this, 81, 157);
        this.rwingclaw1.addBox(0.0f, 0.0f, -9.0f, 1, 1, 8);
        this.rwingclaw1.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw1.mirror = true;
        this.setRotation(this.rwingclaw1, 0.0f, 0.0f, 0.0f);
        this.rwingclaw2 = new ModelRenderer(this, 64, 160);
        this.rwingclaw2.addBox(0.0f, 0.0f, -7.0f, 1, 1, 6);
        this.rwingclaw2.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw2.mirror = true;
        this.setRotation(this.rwingclaw2, 0.0f, -0.6108652f, 0.0f);
        this.rwingclaw3 = new ModelRenderer(this, 103, 159);
        this.rwingclaw3.addBox(0.0f, 0.0f, -6.0f, 1, 1, 5);
        this.rwingclaw3.setRotationPoint(-70.0f, -15.0f, 1.0f);
        this.rwingclaw3.mirror = true;
        this.setRotation(this.rwingclaw3, 0.0f, 0.6108652f, 0.0f);
    }

    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        if (frameEntity == null) return;
        Entity entity=frameEntity;
        float f=frameSwing, f1=frameAmount, f2=frameAge, f3=frameYaw, f4=framePitch, f5=0.0625F;
        matrixStack.push();
this.lclaw1.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw1, 0.0f, 0.6632251f, 0.0f);
this.body.setRotationPoint(0.0f, 0.0f, 9.0f);
this.setRotation(this.body, 0.0698132f, 0.0f, 0.0f);
this.leftleg1.setRotationPoint(7.0f, 5.0f, 23.0f);
this.setRotation(this.leftleg1, -0.5759587f, 0.0f, 0.0f);
this.tail1.setRotationPoint(1.0f, -3.0f, 22.0f);
this.setRotation(this.tail1, -0.1745329f, 0.0f, 0.0f);
this.leftleg2.setRotationPoint(7.0f, 5.0f, 23.0f);
this.setRotation(this.leftleg2, 0.9773844f, 0.0f, 0.0f);
this.body2.setRotationPoint(-6.0f, -9.0f, 10.0f);
this.setRotation(this.body2, -0.1047198f, 0.0f, 0.0f);
this.leftleg3.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.leftleg3, -0.5235988f, 0.0f, 0.0f);
this.tail2.setRotationPoint(0.0f, -2.0f, 33.0f);
this.setRotation(this.tail2, -0.1396263f, 0.0f, 0.0f);
this.tail3.setRotationPoint(0.0f, -1.0f, 42.0f);
this.setRotation(this.tail3, -0.1396263f, 0.0f, 0.0f);
this.lclaw2.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw2, 0.0f, 0.0f, 0.0f);
this.lclaw3.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw3, 0.0f, -0.6632251f, 0.0f);
this.lclaw4.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw4, 0.0f, 0.0f, 0.0f);
this.lclaw5.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw5, 0.0f, 0.6632251f, 0.0f);
this.lclaw6.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw6, 0.0f, -0.6632251f, 0.0f);
this.lclaw7.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.lclaw7, 0.0f, 0.0f, 0.0f);
this.tail4.setRotationPoint(0.0f, 0.0f, 51.0f);
this.setRotation(this.tail4, -0.1396263f, 0.0f, 0.0f);
this.tail5.setRotationPoint(0.0f, 1.0f, 59.0f);
this.setRotation(this.tail5, -0.1396263f, 0.0f, 0.0f);
this.tail6.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tail6, -0.1396263f, 0.1745329f, 0.0f);
this.tail7.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tail7, -0.1396263f, -0.1745329f, 0.0f);
this.tail8.setRotationPoint(-4.0f, 1.0f, 77.0f);
this.setRotation(this.tail8, -0.1396263f, -0.1745329f, 0.0f);
this.tail9.setRotationPoint(2.0f, 1.0f, 77.0f);
this.setRotation(this.tail9, -0.1396263f, 0.1745329f, 0.0f);
this.tailpoint1.setRotationPoint(5.0f, 3.0f, 85.0f);
this.setRotation(this.tailpoint1, -0.1919862f, 0.1745329f, 0.0f);
this.tailpoint2.setRotationPoint(-4.0f, 3.0f, 86.0f);
this.setRotation(this.tailpoint2, -0.1919862f, -0.1745329f, 0.0f);
this.llegspike.setRotationPoint(7.0f, 21.0f, 11.0f);
this.setRotation(this.llegspike, -0.6981317f, 0.0f, 0.0f);
this.tailspike1.setRotationPoint(2.0f, 1.0f, 77.0f);
this.setRotation(this.tailspike1, -0.1396263f, 0.1745329f, 0.0f);
this.tailspike2.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tailspike2, -0.1396263f, 0.1745329f, 0.0f);
this.tailspike3.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tailspike3, -0.1396263f, 0.1745329f, 0.0f);
this.tailspike4.setRotationPoint(-4.0f, 1.0f, 77.0f);
this.setRotation(this.tailspike4, -0.1396263f, -0.1745329f, 0.0f);
this.tailspike5.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tailspike5, -0.1396263f, -0.1745329f, 0.0f);
this.tailspike6.setRotationPoint(0.0f, 0.0f, 68.0f);
this.setRotation(this.tailspike6, -0.1396263f, -0.1745329f, 0.0f);
this.neck1.setRotationPoint(0.0f, -4.0f, -5.0f);
this.setRotation(this.neck1, 0.0872665f, 0.0f, 0.0f);
this.neck2.setRotationPoint(0.0f, -4.0f, -5.0f);
this.setRotation(this.neck2, -0.0523599f, 0.0f, 0.0f);
this.neck3.setRotationPoint(0.0f, -4.0f, -9.0f);
this.setRotation(this.neck3, -0.2443461f, 0.0f, 0.0f);
this.head1.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head1, -0.2443461f, 0.0f, 0.0f);
this.leye.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.leye, -0.2443461f, 0.0f, 0.0f);
this.reye.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.reye, -0.2443461f, 0.0f, 0.0f);
this.head2.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head2, -0.2443461f, 0.0f, 0.0f);
this.head3.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head3, -0.2443461f, 0.0f, 0.0f);
this.head4.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head4, -0.3665191f, 0.0f, 0.0f);
this.head5.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head5, -0.4363323f, 0.0f, 0.0f);
this.head6.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head6, -0.6632251f, 0.0f, 0.0f);
this.jaw1.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.jaw1, 0.1919862f, 0.0f, 0.0f);
this.jaw2.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.jaw2, 0.2617994f, 0.0f, 0.0f);
this.jaw3.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.jaw3, 0.3316126f, 0.0f, 0.0f);
this.jaw4.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.jaw4, 0.4014257f, 0.0f, 0.0f);
this.tooth1.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth1, -0.2443461f, 0.0f, 0.0f);
this.tooth2.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth2, -0.2443461f, 0.0f, 0.0f);
this.tooth3.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth3, -0.2443461f, 0.0f, 0.0f);
this.tooth4.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth4, -0.2443461f, 0.0f, 0.0f);
this.tooth5.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth5, -0.2443461f, 0.0f, 0.0f);
this.jaw5.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.jaw5, 0.1919862f, 0.0f, 0.0f);
this.head7.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.head7, -0.2443461f, 0.0f, 0.0f);
this.tooth6.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth6, -0.2443461f, 0.0f, 0.0f);
this.tooth7.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth7, -0.2443461f, 0.0f, 0.0f);
this.tooth8.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth8, -0.2443461f, 0.0f, 0.0f);
this.tooth9.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth9, -0.2443461f, 0.0f, 0.0f);
this.tooth10.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth10, -0.2443461f, 0.0f, 0.0f);
this.tooth11.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth11, -0.2443461f, 0.0f, 0.0f);
this.tooth12.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth12, -0.2443461f, 0.0f, 0.0f);
this.tooth13.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth13, -0.2443461f, 0.0f, 0.0f);
this.rightleg1.setRotationPoint(-10.0f, 5.0f, 23.0f);
this.setRotation(this.rightleg1, -0.5934119f, 0.0f, 0.0f);
this.rightleg2.setRotationPoint(-10.0f, 5.0f, 23.0f);
this.setRotation(this.rightleg2, 0.9773844f, 0.0f, 0.0f);
this.tooth14.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth14, 0.1919862f, 0.0f, 0.0f);
this.tooth15.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth15, 0.1919862f, 0.0f, 0.0f);
this.tooth16.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth16, 0.1919862f, 0.0f, 0.0f);
this.tooth17.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth17, 0.1919862f, 0.0f, 0.0f);
this.tooth18.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth18, 0.1919862f, 0.0f, 0.0f);
this.tooth19.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth19, 0.1919862f, 0.0f, 0.0f);
this.tooth20.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth20, 0.1919862f, 0.0f, 0.0f);
this.tooth21.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth21, 0.1919862f, 0.0f, 0.0f);
this.tooth22.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth22, 0.1919862f, 0.0f, 0.0f);
this.tooth23.setRotationPoint(0.0f, -6.0f, -14.0f);
this.setRotation(this.tooth23, 0.1919862f, 0.0f, 0.0f);
this.rightleg3.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rightleg3, -0.5235988f, 0.0f, 0.0f);
this.llegspike2.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.llegspike2, -0.6981317f, 0.0f, 0.0f);
this.rclaw2.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw2, 0.0f, 0.0f, 0.0f);
this.rclaw4.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw4, 0.0f, 0.0f, 0.0f);
this.rclaw1.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw1, 0.0f, -0.6632251f, 0.0f);
this.rclaw5.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw5, 0.0f, -0.6632251f, 0.0f);
this.rclaw7.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw7, 0.0f, 0.0f, 0.0f);
this.rclaw3.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw3, 0.0f, 0.6632251f, 0.0f);
this.rclaw6.setRotationPoint(-8.0f, 21.0f, 11.0f);
this.setRotation(this.rclaw6, 0.0f, 0.6632251f, 0.0f);
this.wing1.setRotationPoint(6.0f, -12.0f, 3.0f);
this.setRotation(this.wing1, 0.0f, 0.0872665f, -0.1396263f);
this.wing2.setRotationPoint(27.0f, -15.0f, 1.0f);
this.setRotation(this.wing2, 0.0f, 0.0f, 0.0f);
this.wing3.setRotationPoint(70.0f, -15.0f, 1.0f);
this.setRotation(this.wing3, 0.0f, -0.0872665f, 0.1745329f);
this.mem1.setRotationPoint(6.0f, -12.0f, 3.0f);
this.setRotation(this.mem1, 0.0f, 0.0872665f, -0.1396263f);
this.mem2.setRotationPoint(27.0f, -15.0f, 1.0f);
this.setRotation(this.mem2, 0.0f, 0.0f, 0.0f);
this.mem3.setRotationPoint(70.0f, -15.0f, 1.0f);
this.setRotation(this.mem3, 0.0f, -0.0872665f, 0.1745329f);
this.wingclaw1.setRotationPoint(70.0f, -15.0f, 1.0f);
this.setRotation(this.wingclaw1, 0.0f, 0.0f, 0.0f);
this.wingclaw2.setRotationPoint(70.0f, -15.0f, 1.0f);
this.setRotation(this.wingclaw2, 0.0f, 0.6108652f, 0.0f);
this.wingclaw3.setRotationPoint(69.0f, -15.0f, 1.0f);
this.setRotation(this.wingclaw3, 0.0f, -0.6108652f, 0.0f);
this.lshoulder.setRotationPoint(3.0f, -13.0f, 1.0f);
this.setRotation(this.lshoulder, 0.0698132f, 0.0f, 0.0f);
this.rshoulder.setRotationPoint(-6.0f, -13.0f, 1.0f);
this.setRotation(this.rshoulder, 0.0698132f, 0.0f, 0.0f);
this.rwing1.setRotationPoint(-6.0f, -12.0f, 3.0f);
this.setRotation(this.rwing1, 0.0f, -0.0872665f, 0.1396263f);
this.rmem1.setRotationPoint(-6.0f, -12.0f, 3.0f);
this.setRotation(this.rmem1, 0.0f, -0.0872665f, 0.1396263f);
this.rwing2.setRotationPoint(-27.0f, -15.0f, 1.0f);
this.setRotation(this.rwing2, 0.0f, 0.0f, 0.0f);
this.rmem2.setRotationPoint(-27.0f, -15.0f, 1.0f);
this.setRotation(this.rmem2, 0.0f, 0.0f, 0.0f);
this.rwing3.setRotationPoint(-70.0f, -15.0f, 1.0f);
this.setRotation(this.rwing3, 0.0f, 0.0872665f, -0.1745329f);
this.rmem3.setRotationPoint(-70.0f, -15.0f, 1.0f);
this.setRotation(this.rmem3, 0.0f, 0.0872665f, -0.1745329f);
this.rwingclaw1.setRotationPoint(-70.0f, -15.0f, 1.0f);
this.setRotation(this.rwingclaw1, 0.0f, 0.0f, 0.0f);
this.rwingclaw2.setRotationPoint(-70.0f, -15.0f, 1.0f);
this.setRotation(this.rwingclaw2, 0.0f, -0.6108652f, 0.0f);
this.rwingclaw3.setRotationPoint(-70.0f, -15.0f, 1.0f);
this.setRotation(this.rwingclaw3, 0.0f, 0.6108652f, 0.0f);

        PitchBlackEntity.CustomEntity e = (PitchBlackEntity.CustomEntity)entity;
        float newangle = 0.0f;
        float lspeed = 0.0f;
        RenderInfo r = null;
        float tailspeed = 0.76f;
        float tailamp = 0.25f;
        float pi4 = 0.7853982f;
        float pscale = e.getPitchBlackScale();
        this.legacyAngles(f, f1, f2, f3, f4, f5, entity);
        r = e.getRenderInfo();
        newangle = e.getActivity() != 0 ? MathHelper.cos((float)(f2 * 0.45f * this.wingspeed / pscale)) * (float)Math.PI * 0.24f : -pi4 + MathHelper.cos((float)(f2 * 0.05f * this.wingspeed / pscale)) * (float)Math.PI * 0.02f;
        this.wing1.rotateAngleZ = newangle;
        this.mem1.rotateAngleZ = newangle;
        this.wing2.rotateAngleZ = newangle * 5.0f / 3.0f;
        this.wing2.rotationPointY = this.wing1.rotationPointY + (float)Math.sin(this.wing1.rotateAngleZ) * 21.0f;
        this.wing2.rotationPointX = this.wing1.rotationPointX + (float)Math.cos(this.wing1.rotateAngleZ) * 21.0f;
        this.mem2.rotateAngleZ = newangle * 5.0f / 3.0f;
        this.mem2.rotationPointY = this.wing2.rotationPointY;
        this.mem2.rotationPointX = this.wing2.rotationPointX;
        this.wing3.rotateAngleZ = newangle * 2.0f;
        this.wing3.rotationPointY = this.wing2.rotationPointY + (float)Math.sin(this.wing2.rotateAngleZ) * 43.0f;
        this.wing3.rotationPointX = this.wing2.rotationPointX + (float)Math.cos(this.wing2.rotateAngleZ) * 43.0f;
        this.mem3.rotateAngleZ = newangle * 2.0f;
        this.mem3.rotationPointY = this.wing3.rotationPointY;
        this.mem3.rotationPointX = this.wing3.rotationPointX;
        this.wingclaw2.rotateAngleZ = this.wingclaw3.rotateAngleZ = newangle * 3.0f / 2.0f;
        this.wingclaw1.rotateAngleZ = this.wingclaw3.rotateAngleZ;
        this.wingclaw2.rotationPointY = this.wingclaw3.rotationPointY = this.wing3.rotationPointY;
        this.wingclaw1.rotationPointY = this.wingclaw3.rotationPointY;
        this.wingclaw2.rotationPointX = this.wingclaw3.rotationPointX = this.wing3.rotationPointX;
        this.wingclaw1.rotationPointX = this.wingclaw3.rotationPointX;
        this.rwing1.rotateAngleZ = -newangle;
        this.rmem1.rotateAngleZ = -newangle;
        this.rwing2.rotateAngleZ = -newangle * 5.0f / 3.0f;
        this.rwing2.rotationPointY = this.rwing1.rotationPointY - (float)Math.sin(this.rwing1.rotateAngleZ) * 21.0f;
        this.rwing2.rotationPointX = this.rwing1.rotationPointX - (float)Math.cos(this.rwing1.rotateAngleZ) * 21.0f;
        this.rmem2.rotateAngleZ = -newangle * 5.0f / 3.0f;
        this.rmem2.rotationPointY = this.rwing2.rotationPointY;
        this.rmem2.rotationPointX = this.rwing2.rotationPointX;
        this.rwing3.rotateAngleZ = -newangle * 2.0f;
        this.rwing3.rotationPointY = this.rwing2.rotationPointY - (float)Math.sin(this.rwing2.rotateAngleZ) * 43.0f;
        this.rwing3.rotationPointX = this.rwing2.rotationPointX - (float)Math.cos(this.rwing2.rotateAngleZ) * 43.0f;
        this.rmem3.rotateAngleZ = -newangle * 2.0f;
        this.rmem3.rotationPointY = this.rwing3.rotationPointY;
        this.rmem3.rotationPointX = this.rwing3.rotationPointX;
        this.rwingclaw2.rotateAngleZ = this.rwingclaw3.rotateAngleZ = -newangle * 3.0f / 2.0f;
        this.rwingclaw1.rotateAngleZ = this.rwingclaw3.rotateAngleZ;
        this.rwingclaw2.rotationPointY = this.rwingclaw3.rotationPointY = this.rwing3.rotationPointY;
        this.rwingclaw1.rotationPointY = this.rwingclaw3.rotationPointY;
        this.rwingclaw2.rotationPointX = this.rwingclaw3.rotationPointX = this.rwing3.rotationPointX;
        this.rwingclaw1.rotationPointX = this.rwingclaw3.rotationPointX;
        f3 %= 360.0f;
        f3 = e.getActivity() != 0 ? (f3 *= 0.2f) : (f3 *= 0.55f);
        this.neck3.rotateAngleY = (float)Math.toRadians(f3) * 0.5f;
        this.head3.rotateAngleY = this.head4.rotateAngleY = (float)Math.toRadians(f3);
        this.head2.rotateAngleY = this.head4.rotateAngleY;
        this.head6.rotateAngleY = this.head7.rotateAngleY = (this.head1.rotateAngleY = this.head4.rotateAngleY);
        this.head5.rotateAngleY = this.head7.rotateAngleY;
        this.jaw4.rotateAngleY = this.jaw5.rotateAngleY = this.head1.rotateAngleY;
        this.jaw3.rotateAngleY = this.jaw5.rotateAngleY;
        this.jaw2.rotateAngleY = this.jaw5.rotateAngleY;
        this.jaw1.rotateAngleY = this.jaw5.rotateAngleY;
        this.tooth4.rotateAngleY = this.tooth5.rotateAngleY = this.head1.rotateAngleY;
        this.tooth3.rotateAngleY = this.tooth5.rotateAngleY;
        this.tooth2.rotateAngleY = this.tooth5.rotateAngleY;
        this.tooth1.rotateAngleY = this.tooth5.rotateAngleY;
        this.tooth9.rotateAngleY = this.tooth10.rotateAngleY = this.head1.rotateAngleY;
        this.tooth8.rotateAngleY = this.tooth10.rotateAngleY;
        this.tooth7.rotateAngleY = this.tooth10.rotateAngleY;
        this.tooth6.rotateAngleY = this.tooth10.rotateAngleY;
        this.tooth14.rotateAngleY = this.tooth15.rotateAngleY = this.head1.rotateAngleY;
        this.tooth13.rotateAngleY = this.tooth15.rotateAngleY;
        this.tooth12.rotateAngleY = this.tooth15.rotateAngleY;
        this.tooth11.rotateAngleY = this.tooth15.rotateAngleY;
        this.tooth19.rotateAngleY = this.tooth20.rotateAngleY = this.head1.rotateAngleY;
        this.tooth18.rotateAngleY = this.tooth20.rotateAngleY;
        this.tooth17.rotateAngleY = this.tooth20.rotateAngleY;
        this.tooth16.rotateAngleY = this.tooth20.rotateAngleY;
        this.tooth22.rotateAngleY = this.tooth23.rotateAngleY = this.head1.rotateAngleY;
        this.tooth21.rotateAngleY = this.tooth23.rotateAngleY;
        this.reye.rotateAngleY = this.leye.rotateAngleY = this.head1.rotateAngleY;
        if (e.getAttacking() != 0) {
            newangle = MathHelper.cos((float)(f2 * 0.85f * this.wingspeed)) * (float)Math.PI * 0.16f;
            newangle += 0.5f;
        } else {
            newangle = f2 * 0.7f * this.wingspeed % ((float)Math.PI * 2);
            if ((newangle = Math.abs(newangle)) < r.rf1) {
                r.ri1 = 0;
                if (e.getModelRandom().nextInt(20) == 1) {
                    r.ri1 |= 1;
                }
            }
            r.rf1 = newangle;
            if (r.ri1 != 0) {
                newangle = MathHelper.sin((float)(f2 * 0.85f * this.wingspeed)) * (float)Math.PI * 0.16f;
                newangle += 0.5f;
            } else {
                newangle = pi4 / 4.0f;
            }
        }
        this.jaw4.rotateAngleX = this.jaw5.rotateAngleX = newangle;
        this.jaw3.rotateAngleX = this.jaw5.rotateAngleX;
        this.jaw2.rotateAngleX = this.jaw5.rotateAngleX;
        this.jaw1.rotateAngleX = this.jaw5.rotateAngleX;
        this.tooth14.rotateAngleX = this.tooth15.rotateAngleX = newangle;
        this.tooth19.rotateAngleX = this.tooth20.rotateAngleX = newangle;
        this.tooth18.rotateAngleX = this.tooth20.rotateAngleX;
        this.tooth17.rotateAngleX = this.tooth20.rotateAngleX;
        this.tooth16.rotateAngleX = this.tooth20.rotateAngleX;
        this.tooth22.rotateAngleX = this.tooth23.rotateAngleX = newangle;
        this.tooth21.rotateAngleX = this.tooth23.rotateAngleX;
        float clawZ = 7.0f;
        float clawY = 21.0f;
        float clawZamp = 12.0f * pscale;
        float clawYamp = 6.0f * pscale;
        if (e.getActivity() == 0) {
            float t1 = 0.0f;
            float t2 = 0.0f;
            if ((double)f1 > 0.001) {
                newangle = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale));
                t1 = MathHelper.sin((float)(f2 * 0.75f * this.wingspeed / pscale));
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * f1;
                this.lclaw1.rotationPointY = clawY - t2;
            } else {
                this.lclaw1.rotationPointY = clawY;
            }
            this.lclaw6.rotationPointZ = this.lclaw7.rotationPointZ = (this.lclaw1.rotationPointZ = clawZ + clawZamp * newangle * f1);
            this.lclaw5.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw4.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw3.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw2.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw6.rotationPointY = this.lclaw7.rotationPointY = this.lclaw1.rotationPointY;
            this.lclaw5.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw4.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw3.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw2.rotationPointY = this.lclaw7.rotationPointY;
            this.llegspike.rotationPointZ = this.leftleg3.rotationPointZ = this.lclaw1.rotationPointZ;
            this.llegspike.rotationPointY = this.leftleg3.rotationPointY = this.lclaw1.rotationPointY;
            this.leftleg3.rotateAngleX = -0.61f + newangle * (float)Math.PI * 0.18f * f1;
            this.llegspike.rotateAngleX = -0.785f + newangle * (float)Math.PI * 0.18f * f1;
            this.leftleg1.rotateAngleX = -0.576f + newangle * (float)Math.PI * 0.18f * f1;
            this.leftleg2.rotateAngleX = 0.977f + newangle * (float)Math.PI * 0.18f * f1;
            this.leftleg1.rotationPointY = this.leftleg2.rotationPointY = this.leftleg3.rotationPointY - (float)Math.cos(this.leftleg3.rotateAngleX) * 17.0f + t2 / 2.0f;
            this.leftleg1.rotationPointZ = this.leftleg2.rotationPointZ = this.leftleg3.rotationPointZ - (float)Math.sin(this.leftleg3.rotateAngleX) * 17.0f;
            t1 = 0.0f;
            t2 = 0.0f;
            if ((double)f1 > 0.001) {
                newangle = MathHelper.cos((float)(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
                t1 = MathHelper.sin((float)(f2 * 0.75f * this.wingspeed / pscale + pi4 * 4.0f));
            } else {
                newangle = 0.0f;
                t1 = 0.0f;
                t2 = 0.0f;
            }
            if (t1 > 0.0f) {
                t2 = t1 * clawYamp * f1;
                this.rclaw1.rotationPointY = clawY - t2;
            } else {
                this.rclaw1.rotationPointY = clawY;
            }
            this.rclaw6.rotationPointZ = this.rclaw7.rotationPointZ = (this.rclaw1.rotationPointZ = clawZ + clawZamp * newangle * f1);
            this.rclaw5.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw4.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw3.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw2.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw6.rotationPointY = this.rclaw7.rotationPointY = this.rclaw1.rotationPointY;
            this.rclaw5.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw4.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw3.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw2.rotationPointY = this.rclaw7.rotationPointY;
            this.llegspike2.rotationPointZ = this.rightleg3.rotationPointZ = this.rclaw1.rotationPointZ;
            this.llegspike2.rotationPointY = this.rightleg3.rotationPointY = this.rclaw1.rotationPointY;
            this.rightleg3.rotateAngleX = -0.61f + newangle * (float)Math.PI * 0.18f * f1;
            this.llegspike2.rotateAngleX = -0.785f + newangle * (float)Math.PI * 0.18f * f1;
            this.rightleg1.rotateAngleX = -0.576f + newangle * (float)Math.PI * 0.18f * f1;
            this.rightleg2.rotateAngleX = 0.977f + newangle * (float)Math.PI * 0.18f * f1;
            this.rightleg1.rotationPointY = this.rightleg2.rotationPointY = this.rightleg3.rotationPointY - (float)Math.cos(this.rightleg3.rotateAngleX) * 17.0f + t2 / 2.0f;
            this.rightleg1.rotationPointZ = this.rightleg2.rotationPointZ = this.rightleg3.rotationPointZ - (float)Math.sin(this.rightleg3.rotateAngleX) * 17.0f;
            this.lclaw1.rotateAngleX = 0.0f;
            this.lclaw7.rotateAngleX = 0.0f;
            this.lclaw6.rotateAngleX = 0.0f;
            this.lclaw5.rotateAngleX = 0.0f;
            this.lclaw4.rotateAngleX = 0.0f;
            this.lclaw3.rotateAngleX = 0.0f;
            this.lclaw2.rotateAngleX = 0.0f;
            this.rclaw1.rotateAngleX = 0.0f;
            this.rclaw7.rotateAngleX = 0.0f;
            this.rclaw6.rotateAngleX = 0.0f;
            this.rclaw5.rotateAngleX = 0.0f;
            this.rclaw4.rotateAngleX = 0.0f;
            this.rclaw3.rotateAngleX = 0.0f;
            this.rclaw2.rotateAngleX = 0.0f;
        } else {
            clawZ = 7.0f;
            clawY = 9.0f;
            newangle = e.getAttacking() != 0 ? MathHelper.cos((float)(f2 * 0.85f * this.wingspeed / pscale)) * 0.2f : 0.0f;
            this.lclaw1.rotationPointZ = clawZ;
            this.lclaw1.rotationPointY = clawY + newangle * 30.0f;
            this.lclaw1.rotateAngleX = -0.7f + newangle;
            this.lclaw6.rotationPointZ = this.lclaw7.rotationPointZ = this.lclaw1.rotationPointZ;
            this.lclaw5.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw4.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw3.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw2.rotationPointZ = this.lclaw7.rotationPointZ;
            this.lclaw6.rotationPointY = this.lclaw7.rotationPointY = this.lclaw1.rotationPointY;
            this.lclaw5.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw4.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw3.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw2.rotationPointY = this.lclaw7.rotationPointY;
            this.lclaw6.rotateAngleX = this.lclaw7.rotateAngleX = this.lclaw1.rotateAngleX;
            this.lclaw5.rotateAngleX = this.lclaw7.rotateAngleX;
            this.lclaw4.rotateAngleX = this.lclaw7.rotateAngleX;
            this.lclaw3.rotateAngleX = this.lclaw7.rotateAngleX;
            this.lclaw2.rotateAngleX = this.lclaw7.rotateAngleX;
            this.llegspike.rotationPointZ = this.leftleg3.rotationPointZ = this.lclaw1.rotationPointZ;
            this.llegspike.rotationPointY = this.leftleg3.rotationPointY = this.lclaw1.rotationPointY;
            this.leftleg3.rotateAngleX = -0.61f + this.lclaw1.rotateAngleX;
            this.llegspike.rotateAngleX = -0.785f + this.lclaw1.rotateAngleX;
            this.leftleg1.rotateAngleX = -0.576f - this.lclaw1.rotateAngleX / 4.0f;
            this.leftleg2.rotateAngleX = 0.977f - this.lclaw1.rotateAngleX / 4.0f;
            this.leftleg1.rotationPointY = this.leftleg2.rotationPointY = this.leftleg3.rotationPointY - (float)Math.cos(this.leftleg3.rotateAngleX) * 17.0f;
            this.leftleg1.rotationPointZ = this.leftleg2.rotationPointZ = this.leftleg3.rotationPointZ - (float)Math.sin(this.leftleg3.rotateAngleX) * 17.0f;
            this.rclaw1.rotationPointZ = clawZ;
            this.rclaw1.rotationPointY = clawY - newangle * 30.0f;
            this.rclaw1.rotateAngleX = -0.7f - newangle;
            this.rclaw6.rotationPointZ = this.rclaw7.rotationPointZ = this.rclaw1.rotationPointZ;
            this.rclaw5.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw4.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw3.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw2.rotationPointZ = this.rclaw7.rotationPointZ;
            this.rclaw6.rotationPointY = this.rclaw7.rotationPointY = this.rclaw1.rotationPointY;
            this.rclaw5.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw4.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw3.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw2.rotationPointY = this.rclaw7.rotationPointY;
            this.rclaw6.rotateAngleX = this.rclaw7.rotateAngleX = this.rclaw1.rotateAngleX;
            this.rclaw5.rotateAngleX = this.rclaw7.rotateAngleX;
            this.rclaw4.rotateAngleX = this.rclaw7.rotateAngleX;
            this.rclaw3.rotateAngleX = this.rclaw7.rotateAngleX;
            this.rclaw2.rotateAngleX = this.rclaw7.rotateAngleX;
            this.llegspike2.rotationPointZ = this.rightleg3.rotationPointZ = this.rclaw1.rotationPointZ;
            this.llegspike2.rotationPointY = this.rightleg3.rotationPointY = this.rclaw1.rotationPointY;
            this.rightleg3.rotateAngleX = -0.61f + this.rclaw1.rotateAngleX;
            this.llegspike2.rotateAngleX = -0.785f + this.rclaw1.rotateAngleX;
            this.rightleg1.rotateAngleX = -0.576f - this.rclaw1.rotateAngleX / 4.0f;
            this.rightleg2.rotateAngleX = 0.977f - this.rclaw1.rotateAngleX / 4.0f;
            this.rightleg1.rotationPointY = this.rightleg2.rotationPointY = this.rightleg3.rotationPointY - (float)Math.cos(this.rightleg3.rotateAngleX) * 17.0f;
            this.rightleg1.rotationPointZ = this.rightleg2.rotationPointZ = this.rightleg3.rotationPointZ - (float)Math.sin(this.rightleg3.rotateAngleX) * 17.0f;
        }
        if (e.getAttacking() != 0) {
            tailspeed = 0.76f / pscale;
            tailamp = 0.25f;
        } else {
            tailspeed = 0.26f / pscale;
            tailamp = 0.08f;
        }
        this.tail1.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * (float)Math.PI * tailamp / 2.0f;
        this.tail2.rotationPointZ = this.tail1.rotationPointZ + (float)Math.cos(this.tail1.rotateAngleY) * 11.0f;
        this.tail2.rotationPointX = this.tail1.rotationPointX - 1.0f + (float)Math.sin(this.tail1.rotateAngleY) * 11.0f;
        this.tail2.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - pi4)) * (float)Math.PI * tailamp;
        this.tail3.rotationPointZ = this.tail2.rotationPointZ + (float)Math.cos(this.tail2.rotateAngleY) * 9.0f;
        this.tail3.rotationPointX = this.tail2.rotationPointX + (float)Math.sin(this.tail2.rotateAngleY) * 9.0f;
        this.tail3.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 2.0f * pi4)) * (float)Math.PI * tailamp;
        this.tail4.rotationPointZ = this.tail3.rotationPointZ + (float)Math.cos(this.tail3.rotateAngleY) * 9.0f;
        this.tail4.rotationPointX = this.tail3.rotationPointX + (float)Math.sin(this.tail3.rotateAngleY) * 9.0f;
        this.tail4.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * (float)Math.PI * tailamp;
        this.tail5.rotationPointZ = this.tail4.rotationPointZ + (float)Math.cos(this.tail4.rotateAngleY) * 9.0f;
        this.tail5.rotationPointX = this.tail4.rotationPointX + (float)Math.sin(this.tail4.rotateAngleY) * 9.0f;
        newangle = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * (float)Math.PI * tailamp;
        this.tail5.rotateAngleY = this.tail4.rotateAngleY + (newangle /= 2.0f);
        this.tail6.rotationPointZ = this.tail5.rotationPointZ + (float)Math.cos(this.tail5.rotateAngleY) * 9.0f;
        this.tail6.rotationPointX = this.tail5.rotationPointX + (float)Math.sin(this.tail5.rotateAngleY) * 9.0f;
        this.tail6.rotateAngleY = 0.174f + this.tail5.rotateAngleY + newangle;
        this.tailspike2.rotationPointZ = this.tailspike3.rotationPointZ = this.tail6.rotationPointZ;
        this.tailspike2.rotationPointX = this.tailspike3.rotationPointX = this.tail6.rotationPointX;
        this.tailspike2.rotateAngleY = this.tailspike3.rotateAngleY = this.tail6.rotateAngleY;
        this.tail9.rotationPointZ = this.tail6.rotationPointZ + (float)Math.cos(this.tail6.rotateAngleY) * 9.0f;
        this.tail9.rotationPointX = this.tail6.rotationPointX + (float)Math.sin(this.tail6.rotateAngleY) * 9.0f;
        this.tail9.rotateAngleY = this.tail6.rotateAngleY + newangle;
        this.tailspike1.rotationPointZ = this.tail9.rotationPointZ;
        this.tailspike1.rotationPointX = this.tail9.rotationPointX;
        this.tailspike1.rotateAngleY = this.tail9.rotateAngleY;
        this.tailpoint1.rotationPointZ = this.tail9.rotationPointZ + (float)Math.cos(this.tail9.rotateAngleY) * 9.0f;
        this.tailpoint1.rotationPointX = this.tail9.rotationPointX + (float)Math.sin(this.tail9.rotateAngleY) * 9.0f;
        this.tailpoint1.rotateAngleY = this.tail9.rotateAngleY + newangle;
        this.tail7.rotationPointZ = this.tail5.rotationPointZ + (float)Math.cos(this.tail5.rotateAngleY) * 9.0f;
        this.tail7.rotationPointX = this.tail5.rotationPointX + (float)Math.sin(this.tail5.rotateAngleY) * 9.0f;
        this.tail7.rotateAngleY = -0.174f + this.tail5.rotateAngleY + newangle;
        this.tailspike5.rotationPointZ = this.tailspike6.rotationPointZ = this.tail7.rotationPointZ;
        this.tailspike5.rotationPointX = this.tailspike6.rotationPointX = this.tail7.rotationPointX;
        this.tailspike5.rotateAngleY = this.tailspike6.rotateAngleY = this.tail7.rotateAngleY;
        this.tail8.rotationPointZ = this.tail7.rotationPointZ + (float)Math.cos(this.tail7.rotateAngleY) * 9.0f;
        this.tail8.rotationPointX = this.tail7.rotationPointX + (float)Math.sin(this.tail7.rotateAngleY) * 9.0f;
        this.tail8.rotateAngleY = this.tail7.rotateAngleY + newangle;
        this.tailspike4.rotationPointZ = this.tail8.rotationPointZ;
        this.tailspike4.rotationPointX = this.tail8.rotationPointX;
        this.tailspike4.rotateAngleY = this.tail8.rotateAngleY;
        this.tailpoint2.rotationPointZ = this.tail8.rotationPointZ + (float)Math.cos(this.tail8.rotateAngleY) * 9.0f;
        this.tailpoint2.rotationPointX = this.tail8.rotationPointX + (float)Math.sin(this.tail8.rotateAngleY) * 9.0f;
        this.tailpoint2.rotateAngleY = this.tail8.rotateAngleY + newangle;
        e.setRenderInfo(r);
        this.lclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.body2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leftleg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lclaw7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tail9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailpoint1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailpoint2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.llegspike.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tailspike6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.neck3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.leye.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.reye.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.jaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.head7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth11.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth12.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth13.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth14.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth15.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth16.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth17.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth18.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth19.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth20.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth21.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth22.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.tooth23.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rightleg3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.llegspike2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw4.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw5.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rclaw6.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wing3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.mem3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.wingclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.lshoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rshoulder.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwing3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rmem3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw1.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
        this.rwingclaw3.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
    
        matrixStack.pop();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void legacyAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
    }
}


}
