/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.xillysorespawn;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class XillysOrespawnModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public XillysOrespawnModElements() {
		sounds.put(new ResourceLocation("xillys_orespawn", "alien_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alien_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "alien_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alien_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "alien_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alien_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "alo_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alo_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "alo_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alo_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "alo_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "alo_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_dark"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_dark")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_death_boyfriend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_death_boyfriend")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_death_single"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_death_single")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_fight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_fight")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_happy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_happy")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_ow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_ow")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_rain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_rain")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_taunt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_taunt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_thunder"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_thunder")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_water"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_water")));
		sounds.put(new ResourceLocation("xillys_orespawn", "b_woohoo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "b_woohoo")));
		sounds.put(new ResourceLocation("xillys_orespawn", "basilisk_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "basilisk_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "bb_happy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "bb_happy")));
		sounds.put(new ResourceLocation("xillys_orespawn", "beebuzz"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "beebuzz")));
		sounds.put(new ResourceLocation("xillys_orespawn", "big_splat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "big_splat")));
		sounds.put(new ResourceLocation("xillys_orespawn", "birds"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "birds")));
		sounds.put(new ResourceLocation("xillys_orespawn", "caterkiller_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "caterkiller_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "caterkiller_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "caterkiller_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "caterkiller_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "caterkiller_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "chain_rattles"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "chain_rattles")));
		sounds.put(new ResourceLocation("xillys_orespawn", "chainsaw"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "chainsaw")));
		sounds.put(new ResourceLocation("xillys_orespawn", "chainsawshort"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "chainsawshort")));
		sounds.put(new ResourceLocation("xillys_orespawn", "clatter"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "clatter")));
		sounds.put(new ResourceLocation("xillys_orespawn", "cliffracer"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "cliffracer")));
		sounds.put(new ResourceLocation("xillys_orespawn", "creepinghorror_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "creepinghorror_dead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "creeperhorror_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "creeperhorror_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "creepinghorror_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "creepinghorror_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "cricket"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "cricket")));
		sounds.put(new ResourceLocation("xillys_orespawn", "crunch"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "crunch")));
		sounds.put(new ResourceLocation("xillys_orespawn", "cryo_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "cryo_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "cryo_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "cryo_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "cryo_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "cryo_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "dbdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "dbdead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "dbhit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "dbhit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "dragonfly_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "dragonfly_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "dragonfly_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "dragonfly_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "dragonfly_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "dragonfly_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "duck_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "duck_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "emperorscorpion_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "emperorscorpion_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "fart"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "fart")));
		sounds.put(new ResourceLocation("xillys_orespawn", "frog"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "frog")));
		sounds.put(new ResourceLocation("xillys_orespawn", "ghost_sound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "ghost_sound")));
		sounds.put(new ResourceLocation("xillys_orespawn", "glassdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "glassdead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "glasshit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "glasshit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "godzilla_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "godzilla_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "godzilla_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "godzilla_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "hammerhead_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "hammerhead_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "hammerhead_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "hammerhead_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "hercules_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "hercules_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "hover"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "hover")));
		sounds.put(new ResourceLocation("xillys_orespawn", "king_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "king_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "king_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "king_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "kraken_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "kraken_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "kyuubi_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "kyuubi_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "leaves_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "leaves_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "leaves_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "leaves_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "leon_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "leon_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "leon_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "leon_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "leon_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "leon_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "little_splat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "little_splat")));
		sounds.put(new ResourceLocation("xillys_orespawn", "lurkinghorror_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "lurkinghorror_dead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "lurkinghorror_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "lurkinghorror_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "lurkinghorror_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "lurkinghorror_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "molenoid_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "molenoid_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "molenoid_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "molenoid_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "molenoid_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "molenoid_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "mosquito"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "mosquito")));
		sounds.put(new ResourceLocation("xillys_orespawn", "mothrawings"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "mothrawings")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_dark"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_dark")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_death_girlfriend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_death_girlfriend")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_death_single"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_death_single")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_fight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_fight")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_happy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_happy")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_ow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_ow")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_rain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_rain")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_taunt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_taunt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_thunder"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_thunder")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_water"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_water")));
		sounds.put(new ResourceLocation("xillys_orespawn", "o_woohoo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "o_woohoo")));
		sounds.put(new ResourceLocation("xillys_orespawn", "peacockdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "peacockdead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "pitchblack_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "pitchblack_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "peacockhit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "peacockhit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "peacocklive"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "peacocklive")));
		sounds.put(new ResourceLocation("xillys_orespawn", "pitchblack_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "pitchblack_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "ratdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "ratdead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "rathit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "rathit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "ratlive"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "ratlive")));
		sounds.put(new ResourceLocation("xillys_orespawn", "roar"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "roar")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robot_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robot_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robot_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robot_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robot_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robot_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robot1_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robot1_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robotspider"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robotspider")));
		sounds.put(new ResourceLocation("xillys_orespawn", "robotspidermount"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "robotspidermount")));
		sounds.put(new ResourceLocation("xillys_orespawn", "rubybird"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "rubybird")));
		sounds.put(new ResourceLocation("xillys_orespawn", "scorpion_attack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "scorpion_attack")));
		sounds.put(new ResourceLocation("xillys_orespawn", "scorpion_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "scorpion_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "scorpion_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "scorpion_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seamonster_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seamonster_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seamonster_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seamonster_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seamonster_living1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seamonster_living1")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seaviper_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seaviper_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seaviper_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seaviper_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "seaviper_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "seaviper_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "squid_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "squid_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "squid_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "squid_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "terribleterror_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "terribleterror_dead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "terribleterror_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "terribleterror_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "terribleterror_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "terribleterror_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "trex_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "trex_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "trex_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "trex_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "triffid_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "triffid_dead")));
		sounds.put(new ResourceLocation("xillys_orespawn", "triffid_hit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "triffid_hit")));
		sounds.put(new ResourceLocation("xillys_orespawn", "triffid_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "triffid_living")));
		sounds.put(new ResourceLocation("xillys_orespawn", "vortexlive"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "vortexlive")));
		sounds.put(new ResourceLocation("xillys_orespawn", "waterdragon_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "waterdragon_death")));
		sounds.put(new ResourceLocation("xillys_orespawn", "waterdragon_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "waterdragon_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "wtf_hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "wtf_hurt")));
		sounds.put(new ResourceLocation("xillys_orespawn", "wtf_living"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("xillys_orespawn", "wtf_living")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("xillys_orespawn").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == XillysOrespawnModElements.ModElement.class)
						elements.add((XillysOrespawnModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(XillysOrespawnModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		XillysOrespawnMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final XillysOrespawnModElements elements;
		protected final int sortid;

		public ModElement(XillysOrespawnModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
